### ISSUE TITLE
Keymap for hotkeys

### ISSUE THREAD

**Issue by way2muchnoise** [lorddusk/HQM#102]
I need some help mapping keys.
Help is much appreciated.

Key | EditMode
----- | ------------
Backspace | Go Back (also works outside of edit mode)
N and Insert | New (general)
D and Del | Delete (general)
M | Move (general)
R | Rename (general)
S | Set swap And Select set to swap to
Space | Cursor

**Comment by Cazadorsniper** [comment]
S could be set change maybe.

**Comment by mezz** [comment]
People will be happy no matter what you choose as long as you register your hot keys with forge. That way people can change them and fix conflicts easily.

**Comment by way2muchnoise** [comment]
@mezz I don't plan on adding them to forge since they'll only work in the quest book. However I will work on making them changeable.

**Comment by lorddusk** [comment]
I think making them part of the editmode.cfg to change them will be a good choice...

**Comment by way2muchnoise** [comment]
That was my initial plan @lorddusk
