### ISSUE TITLE
Enchanted items in the quest book do not mask the item

### ISSUE THREAD

**Issue by SnowShock35** [lorddusk/HQM#106]
Hi @lorddusk,

I've got an issue to report, here are the details...

**Important Info**

* HQM Version | 4.4.2
* Forge Version | 10.13.4.1558
* ForgeModLoader log | https://paste.ee/p/hthkt

**Description**

http://prntscr.com/976g0k | Items in the quest book that have the 'enchanted glow' do not mask around the item like they should 

* How it looks: http://prntscr.com/976k5e
* How it **should** look: http://prntscr.com/976jzc

**How to: Reproduce**

1. Create an instance with hqm 4.4.2 (Using forge 10.13.4.1558
2. Load it up then close it
3. Change B:UseEditor=false to true in \config\hqm\editmode.cfg
4. save and close the file and relaunch the instace and create a world
5. Open the quest book, create a set followed by a quest and change the icon of the quest to something with the 'enchanted glow' E.g. enchanted book 
6. Result?
7. Fix the issue :stuck_out_tongue_closed_eyes:

**Comment by SnowShock35** [comment]
I'll pay someone if they fix it by tomorrow :stuck_out_tongue_winking_eye:

**Comment by lorddusk** [comment]
I fixed it... ish?

![screenshot_12](https://cloud.githubusercontent.com/assets/425207/11426852/1fd7ff7e-945f-11e5-9f4f-69346e0e410d.png)

**Comment by SnowShock35** [comment]
@lorddusk That's cheating!!! :-1:

**Comment by lorddusk** [comment]
Better?
![screenshot_13](https://cloud.githubusercontent.com/assets/425207/11427407/e994e6d0-9462-11e5-9b70-1d0aa9769995.png)

**Comment by SnowShock35** [comment]
@lorddusk Yup!

**Comment by SnowShock35** [comment]
:+1:

**Comment by lorddusk** [comment]
Release will be after I have my dinner :P

**Comment by SnowShock35** [comment]
okies =D

**Comment by KindarConrath** [comment]
Damn, I'm really impressed with how fast that got fixed! Great work @lorddusk

**Comment by lorddusk** [comment]
http://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2268197

**Comment by lorddusk** [comment]
Throwing up a useful bug report always helps...
