### ISSUE TITLE
[Request] Auto receive the reward if mob kill quest is done

### ISSUE THREAD

**Issue by Hazado** [lorddusk/HQM#110]
Could you add in a feature that rewards reputation when you kill a mob without having to open the book and complete a quest?

You kill the mob and it adds reputation. No clicking needed inside the book.

**Comment by way2muchnoise** [comment]
related to #139

**Comment by noobanidus** [comment]
Honestly, I'm inclined not to do this at all. The whole point of the quest system is the interaction with the book. Also, reputation is... annoying.
