### ISSUE TITLE
Crash when requesting NEI

### ISSUE THREAD

**Issue by Dream-Master** [lorddusk/HQM#111]
I get the Following crash using HQM Book and try to looking for a recipe in NEI.

Test case:
Join a game.
Don't open NEI inventory.
Open any quest in the HQM Quest book.
Try to open any recipe the HQM Quest book. with R button (this should trigger NEI opening).
Game will crash.

https://gist.github.com/Dream-Master/25b4041c4885fde37d8f#file-nei

http://openeye.openmods.info/crashes/9a8f82d382cb416f77ca038e853cfbac

**Comment by way2muchnoise** [comment]
Can you reproduce the bug with a vanilla item?

**Comment by Dream-Master** [comment]
Yes crash with Vanilla Item too.
I try Wood log.

https://gist.github.com/Dream-Master/0715be458509f059cef6#file-wood-log

**Comment by Dream-Master** [comment]
any news here ?

**Comment by way2muchnoise** [comment]
https://gist.github.com/Dream-Master/0715be458509f059cef6#file-wood-log-L12

Your vanilla item doesn't crash in vanilla NEI code

**Comment by Dream-Master** [comment]
yes but it crash if i look Vanilla Items and Way of Time not answering.

**Comment by way2muchnoise** [comment]
Well it doesn't crash in my env without bloodmagic soo I don't think I can do much here

**Comment by Dream-Master** [comment]
ok thanks hope blood magic people will change some thing then.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Make a new issue if it still happens.
