### ISSUE TITLE
Cooldown timers showing incorrect time

### ISSUE THREAD

**Issue by tgstyle** [lorddusk/HQM#112]
I have a few repeatable quests, and their cooldown time is set to 60 days. Immediately after completing a quest if you hover over it to see the cooldown time it says 44 days, wait a bit it will say 4 days, wait more it will say 27 days, and so on. I don't think the actual cooldown is problematic, it still seems to be 60 days, just the display of time.

**Comment by way2muchnoise** [comment]
I can't reproduce this issue. It works as intended for me. Just for reference is it still happening in the latest version? Could you make a small video or .gif ? What is the forge version you are using? Any other mods that could interfere?

**Comment by tgstyle** [comment]
It appears to be working fine in the latest version. You can probably close
this, I will post again if I see it come up.

**Comment by way2muchnoise** [comment]
Great! Love it when bugs fix them selves.
