### ISSUE TITLE
Search Item Not Working

### ISSUE THREAD

**Issue by xKillerbees** [lorddusk/HQM#116]
Started since 4.3.1 and above
Picture attached with log
forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
Just type something into the search bar

[fml-client-latest.txt](https://github.com/lorddusk/HQM/files/53105/fml-client-latest.txt)
![untitled](https://cloud.githubusercontent.com/assets/2941079/11612560/2bd81f30-9bc5-11e5-8288-ad414d741d8d.png)

**Comment by way2muchnoise** [comment]
I can't reproduce this in my dev env.
![](http://puu.sh/lLlls/40c8826b0b.jpg)

**Comment by lorddusk** [comment]
Neither can I in my live environment...

![screenshot_14](https://cloud.githubusercontent.com/assets/425207/11613389/cfb8f8f0-9c1e-11e5-8b03-01262ed3bdc8.png)
