### ISSUE TITLE
Packet Crash on Missing Items

### ISSUE THREAD

**Issue by xKillerbees** [lorddusk/HQM#118]
4.4.3a

forge-1.7.10-10.13.4.1566-1.7.10-universal.jar

Like with the botania update, it removed the petals. Well when you have hundreds of reward options with no search feature, it makes it hard to find every instance of an item that was removed to remove it before updating the mod. Any chance that we can get HQM to not crash and maybe add a ? or someway to clear quests/rewards or icons if the item can't be found. More so a feature than a bug report I guess since this is probably doing by design.

http://pastebin.com/6nV699xe

**Comment by lorddusk** [comment]
try downgrading your forge to the latest recommended version. See if that helps. Also, it should already change the missing items to undisclosed ones since 4.2...

**Comment by Saereth** [comment]
I have this same problem, tried with forge 1448 and 1558 singleplayer only was magical crops update for me.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten for 1.9+, this should resolve this issue
