### ISSUE TITLE
Trigger Quests button

### ISSUE THREAD

**Issue by BlakeBr0** [lorddusk/HQM#122]
When I have this tool selected and try to click on a quest, nothing happens. This is with version 4.4.3a.

**Comment by lorddusk** [comment]
Please read the Contribution paragraph. and add the additional info.

**Comment by canilsen** [comment]
Can confirm, trigger quest tool doesn't work in 4.4.3a for me neither.

**Comment by airbreather** [comment]
Fixed in 0e93d84.
