### ISSUE TITLE
[regrowth] hqm 4.4.3 complete item / task not working

### ISSUE THREAD

**Issue by megamanzteam** [lorddusk/HQM#124]
I recently changed my regrowth version from .8 to .86 and the version of hqm is 4.4.3. I had to reset my quest status and began the process of completing quests to get it back to where it was. I noticed that if I hold shift over an item to be in my inventory or crafting task it shows I can set just that part is complete. I go to click the item but it does not show 100% or even attempt to reset to 0%. Is this a bug or a feature not yet implemented?

**Comment by way2muchnoise** [comment]
That would only work in the OP book. If it shows up in the non-OP version of the book I should fix that.

**Comment by airbreather** [comment]
Hmm, testing this out, it seems to be hit-or-miss.  OP vs non-OP is working as intended w.r.t. this issue; the problem applies exclusively to the OP book.

I can confirm this issue.  Let me help @megamanzteam out here by providing more details:

- I'm using 4.4.4, but this has been an issue for longer than the changes specific to 4.4.4.  I can't remember exactly when, if ever, this worked.
- When in edit mode, I seem to be able to complete individual requirements for tasks with the OP book by Shift-clicking on them, which shows "Click to complete task" / "Click to reset task" in the tooltip.
- When **not** in edit mode, however, I cannot complete or reset individual task requirements using the OP book, though the "Click to complete task" / "Click to reset task" does show up in the tooltip while Shift is held.
