### ISSUE TITLE
[4.4.3a] Unable to set Trigger settings

### ISSUE THREAD

**Issue by thephoenixlodge** [lorddusk/HQM#127]
The Trigger quest tool seems to not be functional currently - when the tool is selected, clicking on a quest doesn't do anything at all.

**Comment by lorddusk** [comment]
already fixed, will be available first thing tomorrow morning.

**Comment by thephoenixlodge** [comment]
Awesome, thanks

**Comment by way2muchnoise** [comment]
Fixed in #125
