### ISSUE TITLE
"/hqm save bags" Is giving me a error within the console.

### ISSUE THREAD

**Issue by MJRLegends** [lorddusk/HQM#130]
I am in the single player world and im trying to export the reward bags.
When i type the "/hqm save bags" command in the chat ingame i get this error within game
![](https://i.gyazo.com/549643ebcd458798846b42e6816076ca.png)

When looking in the console im getting a " hardcorequesting.bag.GroupTier cannot be cast to hardcorequesting.reputation.Reputation" error. Here is the full error from the console http://pastebin.com/gbVrZ3p8

**Comment by cblair91** [comment]
Can confirm :+1:

**Comment by way2muchnoise** [comment]
I know about the issue and I fixed it in #134 , so next version it will be fixed

**Comment by MJRLegends** [comment]
Ok thanks
