### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by wormzjl** [lorddusk/HQM#131]
http://pastebin.com/ixXLAbgw
Sending the quest book to a creeper?

**Comment by lorddusk** [comment]
Did you die while having the book open?

**Comment by wormzjl** [comment]
just found it in the server log, no idea about what happened sorry

**Comment by wormzjl** [comment]
same crash but no creeper this time
http://pastebin.com/ixXLAbgw

seems someone opened the book, but nobody died

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten in 1.9+. This should have resolved this issue, make a new one if it still happens
