### ISSUE TITLE
[Request] Achivements as quest type

### ISSUE THREAD

**Issue by agowa338** [lorddusk/HQM#135]
Hello, I would weary appreciate an import of all the Minecraft achievements into to quest book. This would give it its one functionality without long quest line creation.

**Comment by bookerthegeek** [comment]
Actually, this is a brilliant idea...

**Comment by way2muchnoise** [comment]
And just why would you want a quest version of the achievements?

**Comment by vagaprime** [comment]
It would help with leading new players through a mod like the twilight forest by letting us set up the achievements as required tasks for a quest.

**Comment by MJRLegends** [comment]
Yeah i've always thought this would be a good idea and it would be great is a biome quest task could be implemented as well

**Comment by canitzp** [comment]
implemented in 5.4.0
