### ISSUE TITLE
Can't save bags to json in 4.4.4

### ISSUE THREAD

**Issue by Saereth** [lorddusk/HQM#136]
recently upgraded from 4.4.2 to 4.4.4 and ran into a bunch of issue, basically I exported all the quests to json and started with a fresh hqm file in 4.4.4 reimporting everything. The bags would not export so I manually re-entered several dozen bags and even with a fresh file the bags are still failing to export to json. /hqm save bags throws the error "An unknown error occurred while attempting to perform this command".

The console shows the following error:

[insert link to log here]

I'm not using the reputation system at all currently.

If I can provide anymore info let me know

**Comment by way2muchnoise** [comment]
If you would have followed the [contribution guidelines](https://github.com/lorddusk/HQM/blob/master/CONTRIBUTING.md) you would have noticed following things

- This issue was already posted #130 
- This issue was already fixed #134 
- You don't post logs in the issue you paste them somewhere and post the link

**Comment by Saereth** [comment]
I didnt see your contribution guidelines, sorry about that. It might be helpful to put a note in the readme so there is a notice when people first arrive. if you google search for this repo you wind up at; https://github.com/lorddusk/HQM

Not everyone know to click the contributing.md file, I literally didnt even notice it until going back with the link you provided.

Thanks for the quick response though, looking forward to the next update :)

**Comment by way2muchnoise** [comment]
There is a big bar at the top when you create a  new issue....

![](http://puu.sh/m4LmE/f830f5d926.png)

**Comment by Saereth** [comment]
Ohhh that's what's that's for XD
