### ISSUE TITLE
[Feature Request] Enchanted Quest Books as rewards

### ISSUE THREAD

**Issue by vagaprime** [lorddusk/HQM#137]
I was wondering if it would be possible to allow quest books to be given out as a reward. It would allow pack creators to give their players a book that has been enchanted with say soulbound as a reward for the very first quest instead of having to use another mod to do this.

**Comment by suprememiners** [comment]
So would you want the players stabbing mobs with a enchanted quest book, or where you implying that you could give out a item with encharntments set within the GUI of the quest book?

**Comment by way2muchnoise** [comment]
What about a setting to never loose the book on dead?

**Comment by vagaprime** [comment]
The option to keep the book on death would work better.

**Comment by way2muchnoise** [comment]
Option to not lose book on death added in #138
