### ISSUE TITLE
Corruption Collection

### ISSUE THREAD

**Issue by Slind14** [lorddusk/HQM#14]
@CannibalVox This is all I could come up with. I'll make sure to not delete upcoming corruptions on 1.7 so we have more to work with. It does not include the "can't open questbook" corruption due to null teams as I hooked the save handler to clear them out before the save.
http://www.mediafire.com/download/86faeky9mme5t1l/HQM-SaveCorruptions.zip

**Comment by Slind14** [comment]
@CannibalVox here is an up to date one. Already happened with 2 different packs within the last 5 days: http://collaboration.mym.li/issues/463

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten for 1.9+, this should resolve this issue
