### ISSUE TITLE
Crash when opening the quest book in edit mode

### ISSUE THREAD

**Issue by JasonMcRay** [lorddusk/HQM#141]
I am writing quests for my modpack, but after some time of writing them when i close and try to reopen the Quest Book my client crashes: http://pastebin.com/QA2y9FNV

Using HQM 4.4.4

**Comment by JasonMcRay** [comment]
Also most of the quest i was working on that session gets removed (even with me saving it manually after i write each quest). The quests icons remains, but contents get replaced by bedrock.

I was working on two quest lines this session. Logistics Pipes and Applied Energistics. All LP items in Logistics Pipes quest were replaced by Bedrock. AE quest were fine.

**Comment by JasonMcRay** [comment]
Did little bit more testing... Not sure if the crash is related to it, but every Logistics Pipes item get replaced by bedrock when i restart minecraft. I can see this in logs:
[15:06:18] [Client thread/ERROR] [HQM]: Attempted to read an item that doesn't exist LogisticsPipes:logisticsSolidBlock
[15:06:18] [Client thread/INFO] [HQM-EDIT]: Changed invalid item to bedrock.

Not sure if its something to do with LP or HQM.

**Comment by vagaprime** [comment]
Just had the same crash happen as well. Though my crash happened in a super flat world that I created to fix quest rewards and create quests in. It sucks cause I was in the middle of writing up a new quest for my pack. We need an auto save option for the quest book when in edit mode.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. make a new issue if it still happens.
