### ISSUE TITLE
Minecraft name change resets all progress

### ISSUE THREAD

**Issue by Jagholin** [lorddusk/HQM#144]
While playing FTB Regrowth(survival themed modpack using HQM) i decided to change my old minecraft name via mojang's website. But very quickly i noticed that all my progress in HQM disappeared.

Considering that i can only revert the name change after 30 days(mojangs policy), this makes it kinda gamebreaking issue.

I think that all minecraft profiles have an unique permanent id attached to them. Shouldn't it be used to save the user info, instead of Minecraft nickname?

**Comment by lorddusk** [comment]
https://github.com/lorddusk/HQM/blob/master/CONTRIBUTING.md

**Comment by Jagholin** [comment]
I wouldn't suggest to change your data model now, you can probably do it for MC 1.8 or 1.9, where nobody would expect backward compatibility anyway.

Also the "common issues" part belongs more to readme file, don't you find?

**Comment by lorddusk** [comment]
No not really.
Since you made an issue for it. And if you would've read the contribution
file, you would've known.

I will change it over for 1.8, while I'm still working on it atm.
