### ISSUE TITLE
/hqm load all breaks quest connections of quests 

### ISSUE THREAD

**Issue by BrizzleMFD** [lorddusk/HQM#146]
The load all command breaks the quest connections of quest lines other then the top most quest line. 
This is using hqm 4.4.4

**Comment by MJRLegends** [comment]
Are the connections for quest across different quest lines/sections? if so this might be because its not loading them in the correct order.

**Comment by BrizzleMFD** [comment]
Yea load all does that on quests for some reason.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. As networking and saving is rewritten for these versions the issue should be resolved.
