### ISSUE TITLE
ArrayIndexOutOfBoundsException in DataReader.readData()

### ISSUE THREAD

**Issue by ryankoppenhaver** [lorddusk/HQM#150]
Seen when loading an existing world after updating from 4.2.2 to 4.3.3 (Marooned modpack 1.1.0 -> 1.1.1).  I think this would still be an issue with current master, but haven't tested it.

`DataReader.readData()` is getting called (from `Team.loadData()`, line 857) with -1 as the argument.  This becomes the initial value of `bitsLeft`, which in turn is not a valid index into the`BIT_MASK` array.

- Forge v10.13.2.1307
- [crash report](https://gist.github.com/ryankoppenhaver/146c61a46c07d7e06832)
- players.dat [hex dump](https://gist.github.com/ryankoppenhaver/1ade451546eaf0dafd9b) / [base64](https://gist.github.com/ryankoppenhaver/2e2c1a323d8e6649ebd2)

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. As networking and saving is rewritten for these versions the issue should be resolved.
