### ISSUE TITLE
Feature Request/Question Adding UUID support

### ISSUE THREAD

**Issue by MJRLegends** [lorddusk/HQM#152]
Hello,

I was just wondering if UUID support could be added because when my friend, that plays on my server for my mod pack changed his username via mojang he no longer had his quest progress and i had to use /hqm edit to complete the quest he already done.

Adding UUID support would fix this because it would be looking for the UUID of the player not the username so nothing would go wrong when changing your username via mojang.

Its just a suggestion so you dont have to add it but it would be nice to see in the mod

**Comment by bookerthegeek** [comment]
Untill/if this is fixed you can change the data file name.

**Comment by MJRLegends** [comment]
What data file?

**Comment by lorddusk** [comment]
read the contribution file. it tells you how to fixit.

**Comment by MJRLegends** [comment]
Ok but this was really to request uuid support

**Comment by lorddusk** [comment]
and break every single quest progress out there. the 1.8 hqm will have only
uuid support. And that ia still a while away since I'm extremely busy with
school...

**Comment by MJRLegends** [comment]
Yeah but wouldn't it be possible to add a built in converter to change current quest progress files ?or add a way to detect and support the old way and the uuid way?

**Comment by lorddusk** [comment]
nein

**Comment by lorddusk** [comment]
The old names don't have an UUID attached to them so it would break, since
I cant do a future search for the new name. hence it would break. For
existing ones, maybe. But I want to focus on releasing 1.8 over fixing this
"bug" in 1.7

**Comment by MJRLegends** [comment]
Ok or why not just add it but have it under a config option and have it turned off by default

**Comment by lorddusk** [comment]
no

**Comment by MJRLegends** [comment]
Ok it was just a thought
