### ISSUE TITLE
Issue - Can't Edit Quest on Server!

### ISSUE THREAD

**Issue by DPxKnightxZero** [lorddusk/HQM#153]
So I summoned an op book and I can't seem to edit quests while on the server; is that intentional?

**Comment by lorddusk** [comment]
check contributing.md

**Comment by DPxKnightxZero** [comment]
I am confused what?

**Comment by way2muchnoise** [comment]
https://github.com/lorddusk/HQM/blob/master/CONTRIBUTING.md

**Comment by DPxKnightxZero** [comment]
Oh thank you : D
