### ISSUE TITLE
Crash - Client Side

### ISSUE THREAD

**Issue by DPxKnightxZero** [lorddusk/HQM#154]
When players are attempting to activate quests 3+ people have had issues with this crash including myself.

Crash Log -> https://gist.github.com/DPxKnightxZero/46b1368e8978b7a6ffc4

Client Log -> https://gist.githubusercontent.com/DPxKnightxZero/e985a2abc0dff2e5d6b7/raw/f8c358da293ae904a2f533dd18a0a6402d1ff3fb/gistfile1.txt

**Comment by lorddusk** [comment]
disable edit mode
