### ISSUE TITLE
NullpointerException on closing the Quesbook while in Edit Mode

### ISSUE THREAD

**Issue by kainortmann** [lorddusk/HQM#158]
When i am in edit mode and then want to close the Questbook with Esc im getting [This Nullpointerexception](http://pastebin.com/6RbYGkAm) and here is what the [Serverlog](http://pastebin.com/7bDSUmkF) says...

**Comment by lorddusk** [comment]
Nice of you to post a German log. anyhow.
Read the contribution.md and you would see that you can't use editmode on
servers.

**Comment by kainortmann** [comment]
Okay, then the Bugreport will become a Feature Request. Is it possible for you to implement this?
