### ISSUE TITLE
[4.4.4] Quest showing edit only tooltip

### ISSUE THREAD

**Issue by JasonMcRay** [lorddusk/HQM#162]
I dont think it is intended, but if a quest will unlock a quest in different set, it will show it in the tooltip.
![2016-02-25_19 22 19](https://cloud.githubusercontent.com/assets/4236895/13329609/285530b2-dbf5-11e5-9f76-8b24573d49c7.png)

**Comment by lorddusk** [comment]
Intended

**Comment by JasonMcRay** [comment]
Thanks for fast reply.
