### ISSUE TITLE
[4.4.4] Crafting task not counting crafts properly

### ISSUE THREAD

**Issue by JasonMcRay** [lorddusk/HQM#163]
I stumbled on this randomly, but I can recreate the issue consistently.
I Have a quest to craft 32 Blocks.
If I craft 1 and put it into my inventory, it counts as 1 craft - Expected Behaviour
If I shift click craft lets say 5 at the time, it counts as 5 - Expected Behaviour
If I craft 2 (still hold the crafted item, and craft another one) and then put those two into my inventroy, it counts as 3 - wrong
If I craft 5 and then put them into my inventory, it counts as 15 - wrong

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. If this still happens in 1.9+ please make a new issue.
