### ISSUE TITLE
[4.4.4] Worlds not remembering questing mode status after closing

### ISSUE THREAD

**Issue by elder-sign** [lorddusk/HQM#164]
Custom mod pack, the first two worlds that I created started in questing mode and maintained that status. However any worlds that I have made since do not start in questing mode, no book is given when the world is created and even after manually setting the world to quest mode after closing and reopening the mode is reset to inactive and all progress is reset. Checked and double checked the config and questing mode is set to true.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version.
