### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by ElijahKSmith** [lorddusk/HQM#166]
**HQM Version:** 4.4.4

**Forge Version:** 1.7.10-Forge10.13.4.1558-1.7.10

**ForgeModLoader log:** http://pastebin.com/ZtwYJ163

**Crash log:** http://pastebin.com/QngbDesQ

**Detailed description of the bug:** Clean install of Minecraft and Forge, other mods work well but when HQM is added or ran as a standalone error occurs.

**Ways to reproduce the bug:**
1. Install Forge
2. Install HQM
3. Run Minecraft

**Comment by lorddusk** [comment]
You are using Java 6. HQM is build against 8 and supports 7. So please update your java to a higher version.
