### ISSUE TITLE
Lore not playing when book is filled with quests

### ISSUE THREAD

**Issue by Maxwelljones** [lorddusk/HQM#169]
HQM: 4.4.4
Forge: 10.13.4.1614
FML Logs: http://pastebin.com/VCw4cAjb - trunkated - can upload full logs when needed
No Crash
Same on client standalone and on server

At some point while developping  the modpack, the lore stopped playing. I tried the same lore on a questbook that doesn't have any quests, and it works fine. As soon as my quests are in the book, the lore doesn't play anymore.

The modpack is private, I can invite you to check it out on server or locally. Please let me know.

Thanks!

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version.
