### ISSUE TITLE
Quests Resetting upon re-joining a level? 

### ISSUE THREAD

**Issue by RyuuDZ** [lorddusk/HQM#178]
For some reason, hardcore questing mode wants to "reset" your quest progress, and I'm not understanding why.
I'm tinkering with edit mode, but noticed this happened. I can't fully confirm that HQM stops resetting quests upon re-entering the map you're on when you set the config file of edit to false. Could someone tell me if quests don't reset while doing so? Or am I doing something wrong?

**Comment by lorddusk** [comment]
In edit mode it will reset progress. It wont outside of it.
