### ISSUE TITLE
Expected stackmap frame at this location.

### ISSUE THREAD

**Issue by Benedictum** [lorddusk/HQM#179]
HQM Version - 4.4.4
Forge Version - 10.13.4.1558
ForgeModLoader log - http://paste.ee/p/9AwhI
Crash log if applicable - http://paste.ee/p/dOXqn
Server log if applicable - single player
Detailed description of the bug and pictures if applicable - Crash at launch of MC, never reaches menu.
Ways to reproduce the bug - install multi mc instance with above forge, install mods listed, launch multimc instance, crash at load.

Oh and there should be an openeye report floating around, i forgot to grab it off of the local disk.

**Comment by Benedictum** [comment]
Oh and there should be an openeye report floating around, i forgot to grab it off of the local disk.

**Comment by lorddusk** [comment]
Could you fill this in please : https://github.com/lorddusk/HQM/blob/1.8/CONTRIBUTING.md

**Comment by Benedictum** [comment]
updated above to your format, thanks for the help / feedback

**Comment by lorddusk** [comment]
Is that with a filled in quest file?

**Comment by Benedictum** [comment]
I believe so, its from the blightfall modpack deved by Tlanos. I can try and .old out the quest file and relaunch to see if thats part of it. Sorry im new to mod pack building and trying to wrastle this beast.

**Comment by Benedictum** [comment]
same result after i .olded the entire HQM folder in config and let it recreate - http://paste.ee/p/7J1w7

i also .olded the player.dat i had kicking around in case that was causing issues. fresh start and all that

**Comment by lorddusk** [comment]
Could you try turning serversync to false in the configs?

**Comment by Benedictum** [comment]
current config shows false - http://paste.ee/p/Ly6LF

**Comment by lorddusk** [comment]
Hmm... Could you try just HQM in the pack?

I think it's another mod that is messing with it.

**Comment by Benedictum** [comment]
I just reverted it to 4.2.3 to test something and got it to load to menu. should i continue testing or just go forward with 4.2.3?

**Comment by lorddusk** [comment]
Always use the latest version.

**Comment by Benedictum** [comment]
stepped forward hqm to 4.3, crashed - http://paste.ee/p/BPdxT
4.4 loads with no other mods, ill start doing a binary add of mods (half and half and half and half) to see if i can find whats not playing nicely.

**Comment by lorddusk** [comment]
It must be. Can't think of anything else it could be.

**Comment by Benedictum** [comment]
It will just take a bit so please bear with me, i appreciate all the help so far. I just need to chew through 114 mods.

**Comment by lorddusk** [comment]
Yay modpacks!

**Comment by Benedictum** [comment]
Oh while i am doing this, if you dont mind answering a couple of general mod questions. 

I noticed in this pack originally, inside the mod folder Tlanos put a 1.7.10 folder and had some of the mods in there instead of the base mod folder. Can you just.... folder up mods like that? Specifically I would love to bundle mods that have dependencies into folders for my own sanity, such as putting all of the thermal mods and cofh core into a single folder, etc etc. 

Second, again for my own sanity, but can mod files be renamed from what the author originally named them? So for instance, yours is hqm-the journey-4.4.4.jar While i am building the pack, if i wanted to, could i rename that to HQM - 4.4.4.jar just so i can more easily read version numbers? Once the pack is done, id rename all the files back to their authors designations for clarity, but that way it was a little easier on my eyes to read them.

Third, ive noticed from looking over the multimc launch logs that a lot of my mod files dont have version metadata, is there anything preventing me from just, yknow, going and adding that version metadata? It seems to me it might speed up the load process by a few cycles, not noticable to a person mind you, but....

thanks in advance.

**Comment by lorddusk** [comment]
The first one, never tried.
The second one, yes.

**Comment by Benedictum** [comment]
So i had a moment of clarity, suspected something, and my suspicions proved correct. Notimefix, which is supposed to be a bug patch for other mods, is the one causing the stack error.  I would say close at this point but we may want to alert CannibalVox and possibly notate HQM that versions 4.3+ are not compatible with notimefix.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. As this was caused by compat I don't even know if it is relevant anymore.
