### ISSUE TITLE
Internal Server Error on certain player

### ISSUE THREAD

**Issue by callum-cummins** [lorddusk/HQM#181]
I believe a user on my server is causing Null Exceptions to passing deaths to his/her HQM book, leading to Ticking Entities that cause a server crash. The server only does this when this user is online and is completely fine otherwise, leading me to believe that their questbook is corrupted somehow. It may be worth also noting that the user in question can't open their book. It seems this is also linked to that player, as I also crash when opening a book linked to that player. 

Everyone else on the server seems to be fine, is there anything that can be done to fix the user? They've tried reinstalling the modpack and reinstalling the quest files but to no avail. 

Thanks for any help in advance!

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Also provide logs and so on in issue. I advice reading [CONTRIBUTING.md](https://github.com/lorddusk/HQM/blob/1.9/CONTRIBUTING.md)
