### ISSUE TITLE
Quests not showing when added new ones

### ISSUE THREAD

**Issue by JasonMcRay** [lorddusk/HQM#183]
Newly added quests doesn't seem to unlock if player already completed the required quest before the new quest was added. This makes hard to add new quests, quest sets over time.

Reproduce steps:
1) Start with edit mode enabled
2) Add a new quest to for example consume 1 dirt
3) Save and restart with edit mode disabled (to simulate propper playthrough by player)
4) Complete the quest and then exit game.
5) Start again with edit mode enabled
6) Add new quest with the dirt quest as prereq
7) Again restart with edit mode disabled
8) The new quest will not show in the book.

Only workaround is to spawn creative quest book (/hqm edit) and reset the prereq quest and complete it again.

Using HQM v4.4.4

**Comment by way2muchnoise** [comment]
Quests will always reset in edit mode.
