### ISSUE TITLE
[1.10.2/1.11.2] Russian language is displayed in wrong encoding

### ISSUE THREAD

**Issue by itskun** [lorddusk/HQM#185]
Russian language is displayed in wrong encoding
![2016-04-24_23 18 24](https://cloud.githubusercontent.com/assets/9961535/14797434/75c69672-0b3b-11e6-8f3d-53e91069477c.png)
![2016-04-25_23 13 22](https://cloud.githubusercontent.com/assets/9961535/14797433/75c48094-0b3b-11e6-84e5-0948e04de140.png)

**Comment by canitzp** [comment]
Can you check if this is a problem in 1.11.2 and do you have font mods installed that chages the fonttype? Cause we are using the default vanilla method to render a string.

**Comment by Terpo** [comment]
Sry if I put my question here but its also font / language related: some of our german special letters are missing in the latest 1.11.2 version of HQM. I did not test it with older versions so far: 
Missing: ß , ä , ö and ü
There letters are replaced by a "?"

Minecraft signs are working so far. No other resource pack involved.
![2017-02-24_12 45 08](https://cloud.githubusercontent.com/assets/4256058/23302469/1a65e460-fa8f-11e6-92e8-13c502488af1.png)

**Comment by canitzp** [comment]
Can you look what is written inside the description.txt file and if this is also happening at quest descriptions

**Comment by Terpo** [comment]
Ok, description.txt looks like ingame with missing letters: Wilkommen im Questbuch von Nameless No I. Du kannst diese Quests als Leitfaden nutzen oder einfach normal vor dich hinspielen. Durch etliche Anpassungen bei Rezepten und Drops kann es nat?rlich vorkommen das man im Spielverlauf ohne Questbuch ein wenig h?ngen bleibt. Ich w?nsche viel Spa?. 


Quests itself + their descriptions seem to work.
![2017-02-24_12 58 11](https://cloud.githubusercontent.com/assets/4256058/23302856/fab4fbc2-fa90-11e6-805b-5b320ef24351.png)
![2017-02-24_12 58 20](https://cloud.githubusercontent.com/assets/4256058/23302857/fab6b994-fa90-11e6-8720-711ded10274e.png)

**Comment by canitzp** [comment]
okay thx, I'll take a look into this, but is isn't a gamebreaking problem, so it may take some time

**Comment by Terpo** [comment]
Could be the form how the description.txt is being saved. When I edit the description whe missing letters are displayable. After world reload the letters are missing. Maybe the coding for the .txt is ASCII or ANSI.

**Comment by madkort** [comment]
How is it going guys? Any news about Russian language? Russian servers are waiting for your awesome mod!

**Comment by Terpo** [comment]
Short update for the newest 1.11 version (alpha3). description.txt still does not save äöüß ;). (still a very minor thing)

**Comment by Terpo** [comment]
Short update:
after putting the alpha3 into a real server <-> client environment the good old ä,ö,ü values are replaced. I think its a problem because the server is running on a linux system and the client was on a windows system. Maybe I can solve it myself when changing the default language table from english to german on the root system. All quests are saved as ANSI, maybe UTF8 would help here too.
