### ISSUE TITLE
Client crash 1.9 

### ISSUE THREAD

**Issue by cauliflower69** [lorddusk/HQM#186]
I tried to import a vanilla quest line from a json file

http://pastebin.com/mF1m7pR5

**Comment by lorddusk** [comment]
For testing purposes it would be amazing if you could post the .hqm it came from and the .json files.

Also this : https://github.com/lorddusk/HQM/blob/1.9/CONTRIBUTING.md

**Comment by lorddusk** [comment]
Actually, if I look at the log, did you open a lan game? If so, could you just try to make a creative world to see if that DOES work?

**Comment by cauliflower69** [comment]
Yeah sure

 Here is the json http://pastebin.com/aCBwRn0X it was from my previous pack on 1.7.10

http://technicpack.net/modpack/requiem-hqm.759053

Here is the client log http://pastebin.com/2WdCLeZq

Forge is version 1.9-12.16.1.1887

Tried to load the json and it failed to load

If you need any further information please let me know and I apologise for not noticing the contribution info

**Comment by way2muchnoise** [comment]
I guess this is related to #194

**Comment by way2muchnoise** [comment]
@cauliflower69 Is this also fixed now?
