### ISSUE TITLE
Item search panel is empty.

### ISSUE THREAD

**Issue by IMarvinTPA** [lorddusk/HQM#187]
I have two versions of my quests file.  One before the issue, and another after the issue starts.  This is the only difference (other than the number of quests I have made.)  The issue is simply that the item search area is empty with or without a keyword when trying to set items.  I can only see items in my inventory.

This is for HQM 4.4.4 on Forge 1614.
The files for my instance of this issue are at http://www.imarvintpa.com/Netherdeep.
Specifically, I can search when my quest file is http://www.imarvintpa.com/Netherdeep/quests.hqm.yessearch but I cannot use the item search using http://www.imarvintpa.com/Netherdeep/quests.hqm.nosearch
FML logs are
http://www.imarvintpa.com/Netherdeep/fml-client-latest.log
and
http://www.imarvintpa.com/Netherdeep/latest.log
The screenshot in https://github.com/lorddusk/HQM/issues/116 matches my experience.

I am trying to add/remove quests to find which one it is that breaks it.  So far, I have gotten the search panel back when I have reloaded after deleting almost all of the quest.  So it may take a bit of binary searching with a full Minecraft reload between changes to nail it down to a specific quest (or type of quest.)

Update:
I have narrowed it down to the 3 quests in "The End!" group.  I am going to bed.  I'm wondering if using items from TabulaRasa is having some weird effect on it.  Not sure what it is about them.  It might be only the first quest, I removed them from the bottom up, one at a time and kept the issue.  It only appeared after I added these quests back in.

Thank You,
IMarv

**Comment by IMarvinTPA** [comment]
The only thing I can consistently prove is that at 61+ quests, you lose the ability to search for items.  It makes no sense otherwise.  I have added a 61st quest, saved, quit, reloaded and the search panel fails. I delete a different quest, relog, and the search works again.

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version
