### ISSUE TITLE
Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by vagaprime** [lorddusk/HQM#188]
https://github.com/MageTech-gate/Release/issues/20
Sent to me through yampst

**Comment by lorddusk** [comment]
Need extra information.
Please fill in the information specified here : https://github.com/lorddusk/HQM/blob/1.9/CONTRIBUTING.md

**Comment by vagaprime** [comment]
Its the 1.7 version of HQM, and as for extra info you have all the info I have. I have to rely on yampst for crash reports and problems.

**Comment by lorddusk** [comment]
Then I can't help you with this, Sorry.
