### ISSUE TITLE
Front logo size

### ISSUE THREAD

**Issue by RoteMinecraftIL** [lorddusk/HQM#189]
What is the _recommended_ size for the `config/hqm/front.png` file?

**Comment by lorddusk** [comment]
the size the default is.

**Comment by RoteMinecraftIL** [comment]
Thanks.

**Comment by relsqui** [comment]
For anyone else searching for this answer later who doesn't want to unpack the jar or dig through the source tree to find the assets: It's a 512x512 pixel image of which only the top left corner, 280 wide x 360 high, will be rendered in the book. Don't let anyone make you feel silly for not figuring that out.
