### ISSUE TITLE
Crash upon completing quests - 1.9

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#191]
HQM Version: HQM-New Heights-5.0.0alpha2
Forge Version: forge-12.16.1.1907
Detailed description of the bug and pictures if applicable:
When I try to complete quest I keep getting "NullPointerException" and the game freezes/crashes.
It doesn't actually crashes so there's no crash log but here is the Game Output up until "crash"
http://pastebin.com/h9Wnauh6
This is what it looks like when it does the freezing:
http://i.imgur.com/wxHnCbd.png
Ways to reproduce the bug: Just complete some quest.
If needed I could add the questlines too.

**Comment by way2muchnoise** [comment]
I guessed this would happen at some point in time. If you have a small vanilla line to share that would be nice.

**Comment by McJty** [comment]
Hmm sounds like what I experienced a while ago and for which I fixed the networking issues in the messages. Are there other spots in HQM where there is this kind of thread related stuff going on perhaps?

**Comment by mobehun** [comment]
Here's a part of the questline: http://pastebin.com/u032Di2G
If needed I could paste the whole one too.
And I don't think there is other stuff like that, or at least I haven't noticed.
