### ISSUE TITLE
Editing doesn't work; don't spawn with book or questing on

### ISSUE THREAD

**Issue by benserwa** [lorddusk/HQM#192]
When I have UseEditor=true typing in /hqm edit tells me "That player does not exist."

When I have UseEditor=false typing in /hqm edit gives me the OP Edition book for myself but it doesn't let me edit anything.

Also, I've got "Auto-start questing mode"=true and SpawnBook=true but I start without a book and without /hqm quest on.

**Comment by benserwa** [comment]
Whoops, forgot the versions. 

HQM 1.9.4-5.0.0alpha2
forge1.9.4-12.17.0.1935

**Comment by way2muchnoise** [comment]
You have to open the regular quest book at least once to init the data before you can use the OP book. Also you don't need an OP book for creating quests. Just activating edit mode and using the regular quest book is enough (and activation quest mode so you can open the book ofc `/hqm quest` will do that for you).
