### ISSUE TITLE
Quest order always alphabetical - 1.9

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#193]
HQM Version: HQM-New Heights-5.0.0alpha2
Forge Version: forge-12.16.1.1907
Detailed description of the bug and pictures if applicable:
The quest order keeps reverting to alphabetical, even though I import them in a different one.
This is the order I'm importing the quests:
http://i.imgur.com/ATagKa8.png
~~After restarting the client it's like this:~~
Exiting the map is enough to cause this:
http://i.imgur.com/K3cYQTT.png

**Comment by way2muchnoise** [comment]
Once a new build is there will be a file called `sets.json`. Just launch the world with the new build and it will be generated. This array is the order of the quests sets. Unload you world (go back to the main menu) and change the file to the correct order. Join the world again and they will be sorted.

**Comment by mobehun** [comment]
Thank you!

**Comment by way2muchnoise** [comment]
No problem, I thank you for testing and providing a proper issue report. :D
