### ISSUE TITLE
Issue when trying to load previous quests from json

### ISSUE THREAD

**Issue by cauliflower69** [lorddusk/HQM#194]
When I try /hqm load I get "you not have permission to use this command"

Forge 1.9 - 12.16.1.1934
HQM Version HQM-New Heights-1.9.4-5.0.0alpha2

**Comment by way2muchnoise** [comment]
You need cheats to be enabled and have opened the quest book at least once, with the player you are doing the load with.

**Comment by cauliflower69** [comment]
Oh ok cheats were enabled but I may not have opened the book. I'll report back

**Comment by cauliflower69** [comment]
I have done as you suggested but receive load failed. I looked at the client log and this is the error

http://pastebin.com/jPETEKSc

Updated to the latest Beta for 1.9.4.

Here is the json http://pastebin.com/aCBwRn0X it was from my previous pack on 1.7.10

I exported the quests in 1.7.10

**Comment by way2muchnoise** [comment]
It seems that I changed one name during the changes of saving. In your export there is a field called `reputation` all the way on the bottom. I changed that to be `reputationBar` and then it loads fine. I will how ever push a change so that it still supports the old name to make it easier.

**Comment by way2muchnoise** [comment]
Also want to note that it seems potions changed from meta data to NBT data to save the type. So you'll see some bad import here and there because of that.

**Comment by cauliflower69** [comment]
Thanks
