### ISSUE TITLE
[Request] Navigating Text

### ISSUE THREAD

**Issue by cauliflower69** [lorddusk/HQM#197]
Is there any way to navigate the text faster? If I paste in a description for example I have to keep clicking the arrow key over and over to get it to move one space at a time. Can we just hold it down so it moves?

**Comment by way2muchnoise** [comment]
I just tested this and can't reproduce it. Are you using the latest version?

**Comment by way2muchnoise** [comment]
To put in other words I can hold my key and the cursor moves.

**Comment by evilmrhenry** [comment]
Works for me as well. What I would like, however, is the ability for home/end/pgup/pgdn/up/down to do things, as well as clicking to move the cursor.

**Comment by noobanidus** [comment]
Home, end are implemented. Up and down are somewhat less feasible. Potentially holding control/shift to move 5/10 spaces instead would be an option. Otherwise I'd need to delve quite deeply into the math of it. (No setCursorPositionAtX/Y).
