### ISSUE TITLE
Quests doesn't sync

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#198]
HQM Version: HQM-New Heights-5.0.0beta2
Forge Version: forge-12.16.1.1907
Detailed description of the bug and pictures if applicable:
Every time I create a new world the already made quests are gone. I've created them in one of my world, exported them and then created a new world. When I open the quest book it's empty.
I've set the config to auto-start questing mode (it doesn't do it) and I've enabled ServerSync.
The same thing happens when I export the whole modpack(on Curse) and then install it.
hqmconfig file:
http://pastebin.com/kzQwEhgR

**Comment by way2muchnoise** [comment]
Hmm guess I should not make quests world dependant. Wasn't really thinking there. I shall move them to a better location.

**Comment by mobehun** [comment]
Thank you :) Keep up the great work!
