### ISSUE TITLE
Can't change reward tier likelihoods or make rewards in groups

### ISSUE THREAD

**Issue by benserwa** [lorddusk/HQM#200]
The blank icon to add a reward to a group isn't there. Changing the numbers in a reward tier doesn't take. The save thing says "Changed tiers: 1" and I can save the change but when I go back into the reward tier it says they're all 0.

**Comment by lorddusk** [comment]
Please provide information according to the [Contribution.MD](https://github.com/lorddusk/HQM/blob/1.9/CONTRIBUTING.md)

**Comment by benserwa** [comment]
Right, sorry. Duhh.

HQM mod: 5.0.0alpha2
Forge: 12.17.0.1935

**Comment by way2muchnoise** [comment]
You might want to update to the [latest build](http://minecraft.curseforge.com/projects/hardcore-questing-mode/files) first.

**Comment by benserwa** [comment]
OK, done. Still the exact same.

**Comment by benserwa** [comment]
I have produced a gif/gfy to better demonstrate my problem: https://gfycat.com/EminentGrandGermanwirehairedpointer

Please excuse the watermark.

**Comment by way2muchnoise** [comment]
That gif makes it quite clear. Also if on windows, https://screentogif.codeplex.com/, this one doesn't watermark :D

**Comment by lorddusk** [comment]
or licecap
