### ISSUE TITLE
Can't change logo, description resets

### ISSUE THREAD

**Issue by benserwa** [lorddusk/HQM#201]
No matter what I put in config/hqm/front.png including logos from other packs, I can't get the logo to display. Also, whenever I exit and re-enter the game, the description is reset.

I feel like I'm having some kind of directory permissions problem?

HQM: 5.0.0beta3
Forge: 12.17.0.1940

**Comment by way2muchnoise** [comment]
It might be that I don't save that :D whoops

**Comment by Carrots4U** [comment]
I hate to be that guy but do you have any clue when you might update with this fix? Our modpack was hoping to release a quest update when this fix is out. No rush or anything, just curious!

**Comment by way2muchnoise** [comment]
When this issue gets closed :D . I guess it'll be somewhere this week.
