### ISSUE TITLE
QDS task selection not working - 1.9

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#202]
HQM Version: HQM-New Heights-5.0.0beta2
Forge Version: forge-12.16.1.1907
Detailed description of the bug and pictures if applicable:
The Select Task and Manual Submit buttons doesn't work. 
http://i.imgur.com/vvL7f0F.png
http://imgur.com/VJJC0pH.png
And here's the code for it:
http://pastebin.com/askfYjiE

**Comment by way2muchnoise** [comment]
@McJty Could you add blockstates (with meta) and needed texture things. Cause there is no "active" texture for when you have a quest bound to the QDS.

![](https://cloud.githubusercontent.com/assets/5518998/15807016/30fc27fa-2b52-11e6-8bf2-738d028eb3ce.png)
