### ISSUE TITLE
Server is not listening to config

### ISSUE THREAD

**Issue by Carrots4U** [lorddusk/HQM#203]
My server is having a problem having quests show up in-game. Both client and server hqm config are identical, and the quests show up in SSP, but in SMP there are none. We've tried enabling/disabing server sync also. I believe it's related to this issue, https://github.com/lorddusk/HQM/issues/198 but it was closed and resolved in the latest update.

**Comment by Carrots4U** [comment]
I've just learned the server does not only not look at the quests, but it doesn't look at the entire config. For example, hardcore mode is disabled in the config, but on the server it is still enabled, enough though in SSP (with the same config), it's disabled.

**Comment by way2muchnoise** [comment]
Guess I'll have to work on the syncing

**Comment by superdave4054** [comment]
Has there been a resolution to this issue? Im currently having the same issue. All the sets, and their respective quests, are not showing up on server quest books even though the config shows they are there.

**Comment by canitzp** [comment]
which mc version

**Comment by superdave4054** [comment]
Sorry, assumed the post was in regard to 1.10.2, the one my server is
using.

On Mar 2, 2017 9:17 PM, "canitzp" <notifications@github.com> wrote:

which mc version

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lorddusk/HQM/issues/203#issuecomment-283854100>, or mute
the thread

**Comment by way2muchnoise** [comment]
Could you try [HQM-New Heights-1.10.2-5.1.0alpha2](https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2396680), which got released this morning and should fix quite some issues.

**Comment by way2muchnoise** [comment]
Also you might want to remove your hqmedit.cfg cause I changed some defaults as full server sync doesn't really work atm. (It needs some fragmenting, cause sending over all quests is a bit much for MC/Forge packet system)

**Comment by canitzp** [comment]
Any updates @superdave4054

**Comment by superdave4054** [comment]
Negative. I just stopped using it altogether.
