### ISSUE TITLE
Game-breaking Dupe Bug

### ISSUE THREAD

**Issue by Carrots4U** [lorddusk/HQM#204]
When you try crafting somethin in a single-player world the crafted item goes into your inventory like it should, but the items you used to craft are dropped on the ground, essentially giving you twice of what you started with. This does not happen on on multiplayer, but that might be because configs don't sync to the server still, making it so quests don't appear. Disabling quests does not fix the dupe bug, only disabling HQM does. This happens on the latest hqm update with the latest forge by the way.

**Comment by lorddusk** [comment]
Extra information is needed.
Please fill in the information specified here : https://github.com/lorddusk/HQM/blob/1.9/CONTRIBUTING.md

**Comment by Carrots4U** [comment]
What more info is needed? I have the HQM version, forge version, there is no log, no crash, nothing abnormal happens in the serverlog. The description is in the main post, and I cannot show the bug without making a video, which I can't do unfortunately. How to reproduce the bug, go into SSP and craft an item.

**Comment by lorddusk** [comment]
Forge version change rapidly. so saying latest is not a very good demeanor.
(also my reaction was a default reaction for anyone that doesn't follow the
contribution guidelines so no harm no foul)

**Comment by Carrots4U** [comment]
Yes, sorry you're right about forge. We're on version 12.17.0.1954

**Comment by Carrots4U** [comment]
Is there any word on a fix coming? Sorry to bug you, but it's been a week and no word back.

**Comment by way2muchnoise** [comment]
Well, I'm in the middle of finals and I like to pass them instead of fixing bugs. So you'll have to wait for that to end first

**Comment by Carrots4U** [comment]
Ah I understand. Wish you good luck!

**Comment by whatthedrunk** [comment]
I found out how to fix this finally. Curse / Minecraft use a default Java 8 version 25. If you tell curse to use your own Jar version 91+ tested the dupe bug goes away, Switch back to native the bug comes back.

**Comment by canitzp** [comment]
comments to the referenced issue please
