### ISSUE TITLE
Quest order resets

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#206]
HQM Version: HQM-New Heights-5.0.0beta3
Forge Version: forge-12.17.0.1960
Detailed description of the bug and pictures if applicable:
The original quest order looks like this: http://i.imgur.com/s25NS1s.png
After changing the sets.json to this: http://pastebin.com/sSBU1SUU and starting up the game again, it reverts to the original one.

**Comment by canitzp** [comment]
Please try it with newer version
