### ISSUE TITLE
Auto-start questing

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#207]
HQM Version: HQM-New Heights-5.0.0beta3
Forge Version: forge-12.17.0.1960
Detailed description of the bug and pictures if applicable:
Auto starting the questing mode doesn't work even though it's enabled in the config file. http://pastebin.com/JdYDZix1
http://i.imgur.com/C5SAqQt.png

**Comment by way2muchnoise** [comment]
Did you close this with a reason?

**Comment by mobehun** [comment]
Yes. Edit mode was enabled. Probably that caused the issue because when it's disabled I got the book.
