### ISSUE TITLE
Missing mob-drops

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#208]
HQM Version: HQM-New Heights-5.0.0beta3
Forge Version: forge-12.17.0.1960
Detailed description of the bug and pictures if applicable:
This is a rather tricky issue here. We've been testing this for a couple days and couldn't figure out the cause. When I have HQM enabled in my modpack the mobs doesn't drop anything but once I disable it, they do. I've made a separate pack with only HQM in it and the mobs did drop items. So what we thought is that there might be an another mod that is conflicting with HQM some way. So I went and tested that. None of the mods caused this issue when I put them in the pack.
I'm not sure if you guys could help, but it would be really appreciated.
Here is a complete modlist: http://pastebin.com/YXRjMGPX

**Comment by way2muchnoise** [comment]
Did you close this with a reason?

**Comment by mobehun** [comment]
Yes. It got solved by one of the mods getting updated. I've got no idea which one though.
