### ISSUE TITLE
[Question] where is the load after [*] coming from

### ISSUE THREAD

**Issue by Slind14** [lorddusk/HQM#21]
Hey,
I'm wondering where the * load after is coming from. I looked for 20 minutes and couldn't find anything.
`FMLMod:HardcoreQuesting{The Journey (4.2.4)} : before: [], after: [*]`

**Comment by lorddusk** [comment]
It seems like the pack you are playing has HQM load after everything else. We do not force this in any way, shape or form.

**Comment by Slind14** [comment]
you are right, it is related to one of the mods. Just tested it with the minimum amount of mods and there is no loading queue issue.
