### ISSUE TITLE
Client Crash - 1.9.4 v5.0.0beta3

### ISSUE THREAD

**Issue by yepidoodles** [lorddusk/HQM#210]
I was adding a reputation reward to a quest when I got this crash

http://www.codesend.com/view/6ed51dd78185b989c96fb0f178d5c04c/
- Alice 
  DragonTechMC

**Comment by yepidoodles** [comment]
I also get this sometimes when loading an already saved world

http://www.codesend.com/view/87594d402b7af4b50ba610ed06482c5e/

**Comment by Bartz24** [comment]
I can confirm this

**Comment by Elvarion** [comment]
Confirm this happening on
HQM-New Heights-1.9.4-5.0.0beta3
Forge 1.10.2-12.18.1.2045

Can easily be reproduced by creating a new quest > Edit reputation reward > Create New = Crash

After you crash this way you wont be able to load the world anymore.
Getting this crash http://pastebin.com/mfSmkBMt

**Comment by canitzp** [comment]
fixed it
