### ISSUE TITLE
Ticking player crash - 1.9.4

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#211]
HQM Version: HQM-New Heights-5.0.0beta3
Forge Version: forge-12.17.0.1987
Detailed description of the bug and pictures if applicable:
Entering the nether causes this crash http://pastebin.com/WzumfKbi . In the quest book there is a location quest for the nether.

**Comment by mobehun** [comment]
Location tasks and killing tasks causes crashes like this one.

**Comment by mobehun** [comment]
Issue still exist!
HQM Version: HQM-New Heights-1.10.2-5.0.0beta4
Forge Version: forge-12.18.1.2061
Detailed description of the bug and pictures if applicable:
Killing task: http://pastebin.com/shh2CHjQ
Location task: http://pastebin.com/sEri6MZa

**Comment by lorddusk** [comment]
Different issue, unfortunately.

**Comment by mobehun** [comment]
Good to know, Should I start a new issue then?

**Comment by lorddusk** [comment]
no.

**Comment by canitzp** [comment]
The second issue has been fixed. If you can reproduce it with 1.11.2 then reopen the issue please
