### ISSUE TITLE
Not saving quests

### ISSUE THREAD

**Issue by xXJamieXx** [lorddusk/HQM#213]
Hey guys,

I'm using the 1.9.4 version 5.0beta3 and when I create some quests in edit mode, then leave the game/quit, it doesn't save. I've tried using /hqm save, it doesn't return anything and i've used the save feature inside the book but whenever I leave the game/quit the game all my quests are gone. In the sets folder in the world (in the saves folder) everything gets removed once i've left...

Please help, I want to make a cool modpack :P

**Comment by canitzp** [comment]
Try it in 1.11.2 please

**Comment by xXJamieXx** [comment]
Yep! As far as i can tell, it appears to be fixed. I tried leaving the world, when i went back in all my changes were still there. I did the same by quitting the game completely, all saved. Whilst testing though, I found that you could create quests outside of the GUI image for example this image:
![image](https://cloud.githubusercontent.com/assets/11248045/22981585/ba42f5c4-f394-11e6-9992-67d1aa0b23a0.png)
Thanks for the help!

**Comment by canitzp** [comment]
That outside of the gui bug has no priority, but I noticed it
