### ISSUE TITLE
Girlfriend can't open book on LAN

### ISSUE THREAD

**Issue by Ryokuakki** [lorddusk/HQM#214]
Hello LordDusk,

**HQM Version**
4.4.4
**Forge Version**
10.13.4.1614
**ForgeModLoader log**
http://paste.ee/p/iKjrO
**Other Details**
Don't know if it matters but we are using MultiMC as you can see in the first line of the logs.
Also we are playing the Simply Magic FTB Third Party Pack

**Detailed description of the bug and pictures if applicable.**
Any LAN game she tries to open the book in just freezes her for a few moments and then continues with the book not opened.

**Ways to reproduce the bug**
See above.

If you could get back to me with a solution or help me try to find one that would be greatly appreciated. In the mean time I will just be giving her the quest rewards as she completes them.

Thanks

**Comment by clienthax** [comment]
This is a common bug with the old versions of hqm, i recently backported the latest version to 1.7.10, if thats merged that version should fix these issues

**Comment by canitzp** [comment]
1.7.10 is no longer supported. sry

**Comment by clienthax** [comment]
@canitzp yep even though i backported everything and you closed my pr without bothering to even leave a reply.
