### ISSUE TITLE
Any change you can fix this small 1.7.10 bug/problem

### ISSUE THREAD

**Issue by MJRLegends** [lorddusk/HQM#215]
Link to issue on my mod packs issue tracker for this issue https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/398

**Comment by lorddusk** [comment]
1.7.10 is no longer supported

**Comment by Dream-Master** [comment]
Using Better Questing Mod.

**Comment by MJRLegends** [comment]
Yeah i would like to but i dont want to lose everyone's progress on the quest book for the worlds they currently have

**Comment by MJRLegends** [comment]
@lorddusk would you be open to releasing a version if i make a pull request to fix it?

**Comment by lorddusk** [comment]
We always said that we are open for PR's. We just don't support it ourselves anymore. Too many versions to keep track off (3 currently)

**Comment by MJRLegends** [comment]
@lorddusk ok but will you then build a version containing it because i cant use unofficial versions in my mod pack so i need you to do the release

**Comment by lorddusk** [comment]
Ofcourse. if you PR it, I will personally build it, (most likely also port it to later versions if not already fixed there ) and release it.

**Comment by MJRLegends** [comment]
Ok
