### ISSUE TITLE
1.10 crash, conflicting with another mod?

### ISSUE THREAD

**Issue by jawsawn** [lorddusk/HQM#216]
http://pastebin.com/cMDFUDsZ

**Comment by jawsawn** [comment]
in fact disabling the armory mod or the hqm fixes the solution so i think there is a conflict

**Comment by way2muchnoise** [comment]
This log should have been on a paste service see https://github.com/lorddusk/HQM/blob/1.8/CONTRIBUTING.md#list-of-paste-services
