### ISSUE TITLE
[1.7.10] Can't load quests from config in game

### ISSUE THREAD

**Issue by noahprice-dev** [lorddusk/HQM#217]
While trying to load quests into my world using the in-game guide (using /hqm load all), I receive the chat message "You not have permission to use this command" [https://gyazo.com/9104bb8187abf4d79d91eaffec7f3e65](url) So I guess first off, you are missing the word 'do' in your error message! :smile:  

Anyway though, the bigger issue is that I have tried a few different methods of making the load work. I have tried copy and pasting the HQM config from a differnt modpack, I have tried the exporting method using /hqm save all and that works perfectly, but I am not sure how to load it back in afterwards? I have tried the methods such as opening the book first then trying, doing it in creative mode, i have moved to a LAN server to ensure I have OP capabilities with cheats enabled and in creative mode, still same error. I have tried with both the OP book and the normal book. I have changed the config to give me edit powers, still doesn't work. Any idea or way I could fix this? 

I can upload more screenshots or my logs if needed.

**Comment by way2muchnoise** [comment]
You have to be in edit mode. This can be set in the config file (it is a separate one)
