### ISSUE TITLE
HQM (1.10.2) not loading my manual editing quest JSONS

### ISSUE THREAD

**Issue by Sasikaa** [lorddusk/HQM#220]
My problem. Try put my HQM quest config DEFAULT folder, the other modpack questline JSONS.
Blood Magic.
I'm edit mode. Make the Blood Magic page. Save it.
The default folder see this file.
Close minecraft, and editing manually this file. ANYTHING copy-paste the other JSON-s text in this blood magic.json
Save the file, start minecraft, start my world. When starting my world, this file is empty. When load the world, deleting this file, and make EMPTY blood magic.json. WHY????
**Any way importing OTHER .json file in my quest book???**

Oh, and try the /hqm load, and not working. Paste my default folder Botania.json, and my starting minecraft. Type /hqm load, says not file. Try /hqm load Botania, NOT WORKING...

**Comment by lorddusk** [comment]
what version are you using and any errors?

**Comment by Sasikaa** [comment]
Up to date version. (HQM-New Heights-1.9.4-5.0.0beta3 )Not crashing or other error. Only not load the manually editing jsons.
Other way inport other modpack jsons???
Oh, i importing OTHER 1.10.2 modpack HQM files!!!!
Not 1.7.10 versions...

**Comment by Sasikaa** [comment]
HM? Not way this problem solved? Or this feature not implemented YET???

**Comment by lorddusk** [comment]
Could you supply me with the Pre-Edit json and the After-Edit json?

**Comment by Sasikaa** [comment]
Yes, wait a minute!

**Comment by Sasikaa** [comment]
When open the new created Blood Magic Page opened it, and copy paste ALL "other modpack created file text" save the my created json. The file size is change, and the opened my created, all text seeing.
When starting my modpack, and open my world, this file is changing, and the file is "new created" (not seeing the paste texts" and the file size is changed the "new created" size...

**SEE THIS PICTURES:**
http://imgur.com/a/Nrk0y

This is the new crated Blood Magic page:
http://pastebin.com/STX1R50n

This is OTHER modpack created Blood Magic json:
http://pastebin.com/uVmwuVcS

**Comment by lorddusk** [comment]
I'll also need your edit.

**Comment by Sasikaa** [comment]
Of course the main EDIT MODE Work for when doing quests ...
If you do not know what's wrong, do not be silly Scrap please ...

**Comment by Sasikaa** [comment]
Why saving my world SAVE folder the quest jsons? This is problem. The editing HQM config folder, copy my save folder, and work or not??? Please answer this option

**Comment by way2muchnoise** [comment]
And if you would use the import feature? If you export it in the original pack (using the command) and then import it into the new pack (also using the command). Does it work that way?

**Comment by canitzp** [comment]
Try this in 1.11.2 please

**Comment by Dilnu** [comment]
Is 1.10.2 not being maintained?

**Comment by way2muchnoise** [comment]
@Dilnu the 1.10.2 was updated for the Invasion modpack. All but LAN worlds should work.
