### ISSUE TITLE
NPE on login

### ISSUE THREAD

**Issue by BlayzerQ** [lorddusk/HQM#221]
Created branch of quests in the single-player game, threw on the server when entering the player kicked from server to server "Internal Server Error", and in the server log:
http://pastebin.com/vtegPfeh

**Comment by way2muchnoise** [comment]
MC version, HQM version and a log that isn't just a cut of the crash would be helpful

**Comment by BlayzerQ** [comment]
MC Version: 1.7.10
Server Core: Thermos:1.7.10-1614.57
HQM Version: HQM-The Journey-4.4.4
Full Server Log: https://www.dropbox.com/s/sseilqzo9bkydf0/fml-server-latest.txt?dl=0
HQM file: https://drive.google.com/file/d/0ByTj4356v7S5b2c0VFItTHVrNnM/view
Client crash (sometimes) https://drive.google.com/file/d/0ByTj4356v7S5UWdhLUVzWVdmWlE/view

If disable ServerSync - all work, but quest files req on client side.

**Comment by BlayzerQ** [comment]
Any news?

**Comment by way2muchnoise** [comment]
1.7.10 is kind of unsupported at the moment, maybe once #218 is reviewed and merged in. There are quite some issues with networking and saving in general in the 1.7.10 version. In the rewrite for 1.8+ most of these got solved.

**Comment by BlayzerQ** [comment]
How get Backport 5.0.0beta3 for 1.7.10? (Compiled jar file)

**Comment by way2muchnoise** [comment]
You'll need to build it yourself, I don't think there is any build so far

**Comment by BlayzerQ** [comment]
Compiled jar: https://yadi.sk/d/jjWm3upju7dff

**Comment by AshIndigo** [comment]
I was able to build it myself easily. But since this isnt mine I'm going to upload it sorry, Just run "gradlew build" with the files in place.

**Comment by BlayzerQ** [comment]
i`am compile this (https://github.com/clienthax/HQM), but there dont work ServerSync. How fix this?

**Comment by clienthax** [comment]
@BlayzerQ stop commenting.

**Comment by lorddusk** [comment]
ServerSync is a feature that works only for MINOR edits in the hqm file.
Not the complete file. A client will ALWAYS need a VERY/EQUAL similar hqm
file to the server.

It is NOT a feature that allows the client to join a server with NO hqm
file present. These files are WAY to big to be sent over the network.

**Comment by BlayzerQ** [comment]
Ok, sorry. I am understud.
