### ISSUE TITLE
HQM Code Request.

### ISSUE THREAD

**Issue by HeroIsBoss354** [lorddusk/HQM#222]
So my home network, MineYourMind (MyM) uses this mod in most of our modpacks. When we (the players and staff) use the quest book, it won't say that we've completed the quest. Which the player will either make a forum thread (or ticket) saying they need an Administrator+ to reset it. (Or just wait for a server restart.) Meaning...unhappy players, results into an unhappy community.

As I've done coding/programming for about 2 1/2 years. I request access to the HQM code, in order to fix the problem.
Grazie
-Hero

**Comment by lorddusk** [comment]
The code is opensource.

**Comment by HeroIsBoss354** [comment]
Either I was looking in the wrong area or I'm blind. I can't seem to find it, sorry.

**Comment by bookerthegeek** [comment]
https://github.com/lorddusk/HQM

**Comment by HeroIsBoss354** [comment]
Thank you for giving me the homepage Booker.

But when I was looking through the page it had 1.8+. So I don't know if I'm looking in the wrong area, as I can't find 1.7.10. Sorry to be a bothersome person.

**Comment by bookerthegeek** [comment]
https://github.com/lorddusk/HQM/tree/master?files=1

**Comment by HeroIsBoss354** [comment]
Sì, that was what I was looking for. You and your links make life easier, thank you.
