### ISSUE TITLE
[1.7.10] HQM Not Opening - Client Side Issue

### ISSUE THREAD

**Issue by MarilynAnn** [lorddusk/HQM#223]
**Forge Version: 7.99.4.1614 ( Soon to be updated - will try updating this soon and see if this fixes the problem )
Minecraft Version - 1.7.10
HQM Version - 4.4.4
This is the issue that shows up on my client-side console when I try to right click the book on my server : [http://pastebin.com/zE0zEMGw](url)
As a side note, nothing shows up on the server console when I right click the HQM Quest Book**

Hey all! Im currently on a 1.7.10 Pack, and suddenly it seems like none of the players can open the quest book. The config for HQM has the editing off, the actual server config says that HQM is fine (We dont have the hardcore enabled - just questing. But that hasn't been an issue since we started)
Tried removing HQM and then re-adding it entirely. No luck there. Also no luck with maybe the player-side and server-side being different sizes, they're exactly the same. Everything I try to google is turning me up nowhere, so im at a dead end now.
Whats weird is that its throwing an exception for an Array out of Bounds, but nobody has touched anything either client-side or server-side, so it doesn't make much sense that it suddenly stopped working for every player on our server (20-30 people)
I can post any logs or configs or anything if anyone needs it and any help at all is appreciated!

**Comment by canitzp** [comment]
1.7.10 gets not updated anymore. sry
