### ISSUE TITLE
[Crash] Reputation crash, Breaking worlds

### ISSUE THREAD

**Issue by Elvarion** [lorddusk/HQM#224]
HQM-New Heights-1.9.4-5.0.0beta3
Forge 1.10.2-12.18.1.2045

http://pastebin.com/bPFkJE8i

How to replicate:
Create a Quest with a Reputation task > Click edit reputation and then on the Rep Bar = Crash
Your world is now also broken and wont load. (Crash log from that is in #210 )

Similar to #210

**Comment by canitzp** [comment]
Fixed it
