### ISSUE TITLE
missing read at REPUTATION_TASK_ADAPTER of QuestTaskAdapter

### ISSUE THREAD

**Issue by krakel** [lorddusk/HQM#227]
The REPUTATION_TASK_ADAPTER contains only a write implementation. The read code is missing!

**Comment by lorddusk** [comment]
Yes. It would be amazing if you can also include the parts where you are looking, because this, however helpful you think it is, it isn't without the places.

**Comment by krakel** [comment]
HQM/src/main/java/hardcorequesting/io/adapter/QuestTaskAdapter.java - Line 216 - all branches
