### ISSUE TITLE
Suggestion: Better Handling for Correcting mistakes with OP book.

### ISSUE THREAD

**Issue by mellamokb** [lorddusk/HQM#23]
Having recently had to fix a corrupt HQM book in a single-player world (again!) I am finding a couple of things that would be really awesome to improve this process.

1. Add an option that when you mark a quest complete, to discard the rewards if they've already been collected.  e.g., mark it as though the reward has already been collected as well (maybe another button press or something).
2. Add an option to partially complete a quest that has multiple steps.  For example, if a quest has 3 steps, and I know before the corruption I had completed 1 of 3, and it's a crafting quest, I want to mark the 1st one completed.  The only options currently are to mark all 3 sub-quests complete, or to recraft the items that are already completed.

Of course, ideally it would not get corrupted in the first place :)

**Comment by hilburn** [comment]
Do you have any ideas what lead to the book getting corrupted?

**Comment by mellamokb** [comment]
It most certainly corrupted because my computer froze and I had to hard reset it.  I understand that means I/O was halted "mid-sentence" so to speak, but MineCraft itself rarely gets corrupted under those circumstances.  There should be a properly transactional way to handle writes to disk so that it is very rare for even a random computer freeze to make your game unplayable.
