### ISSUE TITLE
[1.10.2] Current - Repeatable Quest

### ISSUE THREAD

**Issue by chris-gauth** [lorddusk/HQM#230]
For repeatable quest, it will consume all items and only register as completed once. For example: Repeatable quest with no cooldown: submit 10 bones for 1 wood. If I have 50 bones in my inventory, it will consume all the bones and only allow me to claim the reward once.

**Comment by noobanidus** [comment]
If this is still an issue for 1.11.2, please open a new issue, as HQM is no longer under development for this version of Minecraft.
