### ISSUE TITLE
HQM book wont open

### ISSUE THREAD

**Issue by mrsaminus** [lorddusk/HQM#232]
Server Version       : Thermos-1.7.10-1614-server
Minecraft Version : 1.7.10
HQM Version        : HQM-The Journey-4.4.4.jar

Gets no error in Server or Client console. On the screen it looks like it tryes to place it on the ground.
My settings for the mod is : http://imgur.com/CorBgU5  and : http://imgur.com/P3J7lYl

I'm OP on the server and in GM1 on SP.

In SP i get to open the book. But only like this : http://imgur.com/upSOpUm

Dont get to edit anything.

**Comment by lorddusk** [comment]
Your SMP is in edit mode, it won't open how ever you try...

Your SP, click the button "Click here to start" and edit away.

**Comment by mrsaminus** [comment]
when i click "Click here to start" in SP i get : http://imgur.com/siUr9dy and next page : http://imgur.com/ZRSdBqL

**Comment by mrsaminus** [comment]
same on the server.... and i want qests on my server... so.... am i wrong? edit mode is not how to make quest? have everything changed? How do i make quests?

can't use Quest book or Quest book - op edition
