### ISSUE TITLE
Crashing in the nether [1.10.2]

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [lorddusk/HQM#238]
Was in the nether, and out of no were i crashed!

Wasn't even holding the HQM nor looking through it. Here is a crash report!

http://pastebin.com/ExKFSYaj

**Comment by TheBritishBrotherhood** [comment]
This reset the book as if i didn't do any quests and also corrupted my world.... mass amounts of entity's and loads of blocks got replaced with random blocks from various mods

**Comment by canitzp** [comment]
Test it in 1.11.2 please

**Comment by TheBritishBrotherhood** [comment]
Sure thing.

Ill come back with some reports shortly.

**Comment by TheBritishBrotherhood** [comment]
So i couldn't test it with my current mod pack as its 1.10.2.

But i quickly threw a mod pack together, added a few quests and went ahead and tested.

Was roaming the nether for a good ten minutes. With no issue nor console errors.

So as far as i can see, The bug is fixed!

If it re occurs for some strange reason i will re-open this case.
