### ISSUE TITLE
FTB Utilities causes HQM Corruption

### ISSUE THREAD

**Issue by MapleSight** [lorddusk/HQM#244]
Hiya,

I set up my server to reboot every 12 hours or so a good week ago with FTB Utilites. Every couple of days I'd have to rollback HQM due to crashes. I disabled FTB Utilites' restart and restart the server by hand and it resolves this issue. For now I've disabled FTB restarts, but I would love to be able to use this feature. I've narrowed it down to be caused by FTB Utilities' restart. Something is happening the the process that's causing this corruption. Some advice on how to resolve this would be appreciated. I've pastebined one of the crash logs.

http://pastebin.com/yGwyzinj

**Comment by canitzp** [comment]
Sorry we don't fix 1.7.10 anymore.
