### ISSUE TITLE
[1.10.2] Players on Server has no Quests

### ISSUE THREAD

**Issue by DaNeo61** [lorddusk/HQM#249]
There are no quests at all.

Own private Modpack.
forge-1.10.2-12.18.2.2125-universal
HQM-New Heights-1.10.2-5.0.0beta4

- Fresh generated World on Server.
- Quests are on /config/hqm/default

single error:
`[20:34:26] [Server thread/INFO] [HQM/HardcoreQuesting]: Failed to load questing state`

Current editmode.cfg on Server
https://gist.github.com/DaNeo61/325c65c937d61d96a1a156890a642106

Current hqmconfig.cfg on Server:
https://gist.github.com/DaNeo61/a23efb95b30f771374aef58e38304f5c

Screenshot of /config/hqm/default on server:
http://puu.sh/skqQp/55dad53cec.png 

Screenshot of /world/hqm/ on server:
http://puu.sh/skrrl/8ef41b1377.png

state.json
`{"questing":true,"hardcore":false}`

sets.json
`["The Beginning","Industrial science","Blood science","Get more Storagespace"]`

**Comment by AshsToAshs** [comment]
I am having the same issue when trying to make a server based on the "Curse of Gaia" modpack found on Curse. 

Glad to see its an issue with the mod. I thought I was losing my mind!

**Comment by Saereth** [comment]
Also having this issue as well, here is our complete HQM config server side and client side match
https://github.com/breakinblocks/nutsandbolts2/tree/master/config/hqm

**Comment by Elvarion** [comment]
Same here, Just spent half a week in Singleplayer setting up about 100+ Quests. Then moved the config files over to the server and it just wont load. Tried placing it all over in every HQM map there is to see if that helps, but no luck with that.

Started the server with Blank configs, Made 1 quest with Edit mode on (In multiplayer)
Restarted the server and the quest is there. However! I have NO clue where it saves these quests. I cannot find them anywhere

**Comment by InjuredWolf** [comment]
Check your client config folder. They might be saved there. Not sure how to make the server work with it...

**Comment by royalcw** [comment]
I had this problem also but figured it out.  I removed the entire HQM subfolder from the config folder on the server.  Next I booted up the server so that it could rebuild it's config for HQM.  The config is actually slightly different when a server builds it and it also creates an additional folder called exports that isn't made in single player.  Next I dragged all my quests from my client folder to the server Export folder and typed /hqm load all from in game as an OP.  This loaded all the quests and now each player can see the quests.  Hope this helped.

**Comment by DV666** [comment]
> I had this problem also but figured it out. I removed the entire HQM subfolder from the config folder on the server. Next I booted up the server so that it could rebuild it's config for HQM. The config is actually slightly different when a server builds it and it also **creates an additional folder called exports that isn't made in single player.** Next I dragged all my quests from my client folder to the server Export folder and typed /hqm load all from in game as an OP. This loaded all the quests and now each player can see the quests. Hope this helped.
> 

I didn't get this folder "exports" when i delete hqm folder on server :( Just Default and Remote.
I have also this issue : very annoying on multiplayer... I don't know how to avoid this :/ Maybe i will send MP to authors on Curse to fix it asap.

**Comment by EverNife** [comment]
I spent about 4 hours trying a lot of things...

If someone could solve this, it would be really helpfull :/

**Comment by DV666** [comment]
No update since September.... pretty sad : maybe send MPs to authors on Curse ? I can do that but English is not my native language ahah ^^

Meanwhile, i use Better Questing for my upcoming modpack but i prefer HQM sincerely... :/

**Comment by EverNife** [comment]
Better questing seems not to support offline server (bungecoord needs that) 

Sadly :/

**Comment by DV666** [comment]
> Better questing seems not to support offline server (bungecoord needs that)
 Sadly :/
> 

No no, it's work perfectly on dedicated server with Better Questing, i just try now and it's perfect ! Functionalities on this mod is very similar at HQM but as i said, i prefer HUD, editing mode and loot bag system from this last.

I am very bad to explain some things in English x) But i think i will send somes MPs on Curse to alert author, hope we get an update asap :(
Moreover, i wonder how royalcw has succeeded to use HQM on multiplayer !

**Comment by DV666** [comment]
I send a MP to McJty/Lorddusk/Way2muchnoise on Curse : hope we get an answer quickly.

**Comment by way2muchnoise** [comment]
I don't have time to look into it right now, as I am in the middle of finals. I'll give it go in February, unless someone else can figure it out.

**Comment by DV666** [comment]
> I don't have time to look into it right now, as I am in the middle of finals. I'll give it go in February, unless someone else can figure it out.
> 

Thanks for the reply way2muchnoise ^^ I understand your situation : no problem ! Hope another person will react about this topic.

PS : GL for yours finals !

**Comment by canitzp** [comment]
Can anyone please give a up-to-date picture of the server side folder structure for the hqm folder? I test it currently and for me the client side created quests are without a problem server side loaded.

**Comment by DV666** [comment]
If i remember, you can create quest with edit mode when you are on a server but it's impossible to do quests (the book can't detect block or whatever, nothing to validate...)

I will give you picture asap if you want :)

**Comment by canitzp** [comment]
This gets fixed with the 1.11.2 release. I reworked the folder structrure of the quests. If anyone want to copy the quests to a server, there is a readme file inside the config folder of hqm
