### ISSUE TITLE
[1.10.2] Quest book not spawning

### ISSUE THREAD

**Issue by addrever** [lorddusk/HQM#250]

**Comment by addrever** [comment]
Sorry about the premature submit.  I will get a proper entry here in a second.

**Comment by addrever** [comment]
I have HQM installed on a 1.10.2 pack, but when I load a world the book doesn't spawn.  In the config it says SpawnBook=true.  Doesn't matter if I have Auto-start questing mode set to true or not.


[hqmconfig.txt](https://github.com/lorddusk/HQM/files/614060/hqmconfig.txt)

**Comment by way2muchnoise** [comment]
Is edit mode off?

**Comment by addrever** [comment]
Either on or off no book spawns.

**Comment by rckymtnrfc** [comment]
Same issue here with HQM-New Heights-1.10.2-5.0.0beta4.jar.  Edit mode is false.

I have SpawnBook set to true.  If I cheat in a book and try to open it, it informs me that questing mode is not turned on. Even though I have Auto-start questing mode as true also.

**Comment by royalcw** [comment]
try typing /hqm quest in your server console.  Will set questing mode to active and all clients joining should receive the book.

**Comment by canitzp** [comment]
This gets fixed with #235

**Comment by addrever** [comment]
This still isn't fixed in 1.10.2.  Unless I am missing something.



[hqmconfig.txt](https://github.com/lorddusk/HQM/files/841651/hqmconfig.txt)
[editmode.txt](https://github.com/lorddusk/HQM/files/841652/editmode.txt)

**Comment by canitzp** [comment]
Lord Dusk backports the 1.11.2 version, where I fixed it, to 1.10.2, be patient

**Comment by addrever** [comment]
No worries.  Thank you!  I just wasn't sure if I was derping.  I realize now the response was kind of cold so I apologize.
