### ISSUE TITLE
[1.7.10 possible 1.10.2] Upon removing of ban from player there is a chance to get 255 lives.

### ISSUE THREAD

**Issue by MaxineBean** [lorddusk/HQM#253]
Like the title says, I was playing Project Ozone 2 and I removed a ban and 1 player came back with 0 lives, another came back with 255 lives. I have not been able to figure out what causes this issue. My idea would be the difference is caused by unbanning while the server is offline and while server is online. 
Note: The maximum amount of lives set on the server is 40

Modpack: Project Ozone 2 version 3.1.9(BETA)  and Project Ozone 2 3.1.8
Forge version: 10.14.4.1614
HQM version: 4.4.4
Server Log: I do not have the logs unfortunately, and I do not think client log applies.

**Comment by canitzp** [comment]
Can you test this with the 1.11.2 version pls

**Comment by way2muchnoise** [comment]
Pretty sure this won't happen in the new save system. As it isn't saved as a byte any more.
