### ISSUE TITLE
Double string at 72 line

### ISSUE THREAD

**Issue by BlayzerQ** [lorddusk/HQM#255]
if (quest != null && task > -1 && task < quest.getTasks().size())
                quest.getTasks().get(task).onUpdate(player);
            quest.getTasks().get(task).onUpdate(player);

==>

            if (quest != null && task > -1 && task < quest.getTasks().size())
                quest.getTasks().get(task).onUpdate(player);

**Comment by canitzp** [comment]
Can you can write the class, where I can find this

**Comment by way2muchnoise** [comment]
[`hardcorequesting.client.ClientChange`](https://github.com/lorddusk/HQM/blob/1.11/src/main/java/hardcorequesting/client/ClientChange.java#L70-L72)
