### ISSUE TITLE
Loading failed trying to load hqm json

### ISSUE THREAD

**Issue by mrdeadlocked** [lorddusk/HQM#26]
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraft.command.CommandException: Loading failed.
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.commands.CommandLoad.load(CommandLoad.java:39)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.commands.CommandHandler.func_71515_b(CommandHandler.java:232)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#328]  [09:02:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I saved https://www.reddit.com/r/TestPackPleaseIgnore/comments/3ieifr/aaronhowser1s_hqm_pack/ into json format, and did some edits (Just switching out items). When trying to /hqm load all i get the above error.

**Comment by lorddusk** [comment]
For the love of god, use pastebin to post logs. Also, I would need your complete log, this doesn't say much.

**Comment by lorddusk** [comment]
Also, single or multi player?

**Comment by lorddusk** [comment]
Also, did you remove the quests before loading? It won't allow you to load already existing quest sets...

**Comment by mrdeadlocked** [comment]
Ah it was the fact that the quests were already loaded in book. I thought it would update with the changes to the quests. Sorry!
