### ISSUE TITLE
[Question][Feature] Tiered progression with recipe blocking\block interaction etc

### ISSUE THREAD

**Issue by maxiride** [lorddusk/HQM#262]
There used to be a great mod called [Progression](https://minecraft.curseforge.com/projects/progression) which did a different job from HQM, instead of quest it allowed modpack creators to further customize the gameplay with set of rules and conditions. I'll leave a deeper description to the curse page itself.
The addon, as told by his dev, have been abandoned:
>WARNING this mod currently has no maintainer. And I have zero interest in developing it anymore. So use at your own risk. If anyone would like to take over, just send me a message. Keep in mind Progression uses asm so you may need to know that. Also let me know what you've worked on before. Don't really want to hand it over to a beginner modder.

Do you guys, developers of HQM, think that would be interesting for you to pick up the project and keeping it up?

HQM has a different approach so I don't think the two mods should be merged, but pairing them together surely deepens  and enhance the experience a modpack could offer, either in an hardcore setting or not.

I'd like to hear some thoughts about it! =)

**Comment by canitzp** [comment]
It is a mod that does nearly the same thing, so as a hqm dev it wouldn't be good to dev at it. But good luck to find one who does it and the new dev should thinking about dropping the asm and try to use events for it, asm is bad.
