### ISSUE TITLE
Quest Not Showing on Server 

### ISSUE THREAD

**Issue by CluelessPhil** [lorddusk/HQM#266]
Hello, so I've created a modpack and it uses Hardcore Questing Mode and the quests work fine they show up on single player. But once i created a server for it (having HQM installed the the Quest files in the config) the quest didn't show up and neither did the description. So i tried to enable hardcore mode and it said it was enabled but I opened the book and it didn't show the hearts. So i tried one last thing ServerSync and that didn't work when i enabled it from the config. Can someone help me?

**Comment by canitzp** [comment]
duplicate of #249
