### ISSUE TITLE
[1.11.2] Ticking player and Item Duping

### ISSUE THREAD

**Issue by whatthedrunk** [lorddusk/HQM#269]
This crash happened while trying to craft a normal crafting table. The old dupe bug happens still where you get the items you crafted with and the crafting item. After a few times crafting crafting tables I got this crash.

http://pastebin.com/GCKs1v31

**Comment by canitzp** [comment]
#233

**Comment by canitzp** [comment]
It would help a lot if you can try it without any other installed mod. I can't reproduce it.
