### ISSUE TITLE
Crash While Viewing Completed Kill Quest

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#271]
Hello, 

I just opened my quest book up to the page where I had a completed killing quest, the pack froze up for a few seconds and then crashed with the following report:

Log: http://pastebin.com/eebAgjkw

HQM: 5.0.0 beta4
Forge: 2221
MC: 1.10.2

Thank you very much for looking  at this!
Darkosto

**Comment by canitzp** [comment]
This is a known bug and LordDusk is doing the backport and would try to fix it

**Comment by lorddusk** [comment]
This is not a known bug ;)
And this IS fixed in the version I have in my environment, the known bug is that it won't complete properly. I'll keep this one open though, just for reference, and so I can notify you when I have a version ready for release.

**Comment by Darkosto** [comment]
Thanks for checking it out, I appreciate your work on the mod :)

**Comment by way2muchnoise** [comment]
Should be fixed as of 5.1.0alpha2
