### ISSUE TITLE
[Feature Request] Enable quest mode for player automatically?

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#273]
Is it possible to enable the questing mode for players without them having to Open To Lan and then activate themselves?

MC: 1.10.2
Forge:2221

I appreciate your consideration!
Darkosto

edit: The config option does not seem to activate it properly

**Comment by canitzp** [comment]
I have fixed it alrwady with the 1.11.2 release. Wait for the backport to 1.10.2
