### ISSUE TITLE
Crash During Client Load

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#274]
Crash on client load after updating the mod.

Log: http://pastebin.com/QkL9K8yw 

HQM: 5.1.0 alpha 2
MC: 1.10.2
Forge: 2221

Thank you :)
Darkosto

**Comment by canitzp** [comment]
where do you get a 1.10.2 version of the latest 1.11.2 version?

Edit:
I was a bit confused, cause I didn't know about the testing version

**Comment by lorddusk** [comment]
From me. for testing purposes.

**Comment by Darkosto** [comment]
Tried out the newer version and I think I'm still getting the same crash: http://pastebin.com/SMsdpmZE

**Comment by MokahTGS** [comment]
Would I be able to test out the 1.10.2 version?  I'd like to do what I can to get that version officially updated.

**Comment by way2muchnoise** [comment]
@MokahTGS I've been working with @Darkosto the past few days and a public alpha should be out soon
