### ISSUE TITLE
java.lang.NullPointerException: Rendering screen (HQM-New Heights-1.11.2-5.1.0alpha2)

### ISSUE THREAD

**Issue by SDUBZ** [lorddusk/HQM#275]
clicked unkown because i thought it was to change item to blank and got this crash
[crash-2017-02-17_10.48.34-client.txt](https://github.com/lorddusk/HQM/files/781854/crash-2017-02-17_10.48.34-client.txt)

forge:1.11.2-2230
hqm version:HQM-New Heights-1.11.2-5.1.0alpha2

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM

**Comment by iSansho** [comment]
[crash-2017-09-10_19.41.34-client.txt](https://github.com/lorddusk/HQM/files/1290762/crash-2017-09-10_19.41.34-client.txt)
Same problem 

forge-1.11.2-13.20.1.2393
HQM-New Heights-1.11.2-5.1.0alpha3.jar
