### ISSUE TITLE
crash on load (1.11.2)HQM-New Heights-1.11.2-5.1.0alpha2

### ISSUE THREAD

**Issue by SDUBZ** [lorddusk/HQM#276]
forge: 1.11.2-2232
minecraft: 1.11.2
hqm: HQM-New Heights-1.11.2-5.1.0alpha2

crash on loading
crash report:
[crash-2017-02-18_14.05.10-client.txt](https://github.com/lorddusk/HQM/files/784729/crash-2017-02-18_14.05.10-client.txt)

**Comment by ThomasAunvik** [comment]
I might be wrong, but i think the solution to the problem is to delete the HQM configs.
Meaning it needs to regenerate its config to default.

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM
