### ISSUE TITLE
Continuosly disconnected from server

### ISSUE THREAD

**Issue by lightning02** [lorddusk/HQM#277]
http://pastebin.com/rvFZyT4r
a player continue to being disconnected from server, even if his hqm config folder is exactly the same of the server hqm config folder

**Comment by canitzp** [comment]
The quest book is to long or there is to much hqm data that has to be synced with the client. Poorly for you, 1.7 is no longer supported. sry

**Comment by lightning02** [comment]
isn't there something I can do myself to 'fix' this? (except to make the questbook lighter) 
also, is possible that this lead to world corruption? just asking
