### ISSUE TITLE
[1.10.2] Config Issue (Please read)

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [lorddusk/HQM#278]
Hello.

So a while back i fixed a bug with HQM and it was forked into the 1.10.2 version of HQM.

As from the fix there hasnt been an update, Just wondering if you are soon to release a 1.10.2 update that fixes the issue i fixed?

The issue is the config for 'HQM Quest mode = enabled' wasnt working correctly.

**Comment by lorddusk** [comment]
This is in the build I'm currently trying to fix. It's already in the 1.11.2 release. Next time, just comment on the PR ;)

**Comment by TheBritishBrotherhood** [comment]
Mucho love lorddusk and sure thing :D <3
