### ISSUE TITLE
Quest not showing on a server

### ISSUE THREAD

**Issue by Shahhubminecraft** [lorddusk/HQM#280]
The quest book works fine in single player but when it is put on a server the quests don't show up at all.

I am using the latest version of hqm from today 25/02/2017

**Comment by canitzp** [comment]
which hqm and minecraft version?

**Comment by Shahhubminecraft** [comment]
Hqm version 5.00beta4 on Minecraft 1.10.2

**Comment by canitzp** [comment]
This is a know bug in 1.10.2 and was fixed in 1.11.2. You have to wait for the backport of the 1.11.2 version.

**Comment by Shahhubminecraft** [comment]
When will that version be available

**Comment by canitzp** [comment]
@LordDusk

**Comment by lorddusk** [comment]
When I have time...
