### ISSUE TITLE
Invalid book

### ISSUE THREAD

**Issue by Pokemonpurson** [lorddusk/HQM#281]
I am having an issue where, after I successfully created and am running a private server, I spawn in with a quest book, but there are no quests! I know this has been happening, but when I right click the book on a block, it disappears! I can only open it in Single player, it won't open in multiplayer! When I go into creative on the server, it says "there is no such item with id 27332" in one of the files, it says "Invalid book!" in another, it says "Another OP is already accessing this player's quests" followed by "You don't have permission to use this book!" If you read this and can help, please do! Thank you for reading this (if you did)!

**Comment by canitzp** [comment]
Wich minecraft/forge version? Any log files? Since 1.8 you cannot give a item with a integer id, they are now text ids.

**Comment by Pokemonpurson** [comment]
I believe I am using Minecraft 1.6.4, and Forge 9.11.1345. The server is running, but I can't use the quests. I just tried to load Single Player, and it said that id 745 and 746 are missing. I have not changed any item ids that I know of. What log file do you want and where could I find it, and what is the difference between an integer id and a text id? I can give myself other items though... Sorry, I'm new at this... Thank you for responding!

**Comment by canitzp** [comment]
If you're new to this, why the hell are you using 1.6.4? I don't know how this old version works, so I can't help. I also don't think that @lorddusk does remember, it's now 2,5 years old

**Comment by Pokemonpurson** [comment]
It's for a modpack... Magic Island HQM (different name on Curse) sorry if I'm bothering you... Should I go?

**Comment by canitzp** [comment]
You can wait for a answer of @lorddusk, I can't help.

**Comment by Pokemonpurson** [comment]
Ok... Sorry. Do you know how soon they can help? I won't rush them, I'm just curious...

**Comment by lorddusk** [comment]
This is a LOOOOOOOONG time ago, I suggest you move to a newer version,
because if we don't support 1.7 anymore, we sure won't support 1.6 anymore.

On a different note, I have no idea. that code is way out of my system, and
I don't think I even have it anymore...

**Comment by Pokemonpurson** [comment]
How would I update? Sorry, I'm really stupid...

**Comment by lorddusk** [comment]
If you use Curse pick another pack mate ;)
