### ISSUE TITLE
[BUG] [1.7.10] Quests and Reward Bag tiers which ends on unicode symbol corrupts after reload.

### ISSUE THREAD

**Issue by fa1ntl1ght** [lorddusk/HQM#282]
Very interesting bug, it seems like it is because quests saved in wrong encoding. Really need solution, because i making a modpack on russian language.

Any quest name that contains a unicode symbol on its end becomes corrupted:

ТЕСТ ТЕСТ ТЕСТ ТЕСТ ТЕСТ ТЕСТ

will be merged into something like this:

ТЕСТ ТЕСТ ТЕСТ Т⍰

What i can do? Java version is 8 latest (reinstalled 2 hours ago)
This bug occurs even if only hqm is installed.

**Comment by canitzp** [comment]
This is a hqm bug, but 1.7 is no longer supported, so sorry about that. You can't do anything, except avoiding such symbols
