### ISSUE TITLE
1.11.2 crash when pick up the items of the quest

### ISSUE THREAD

**Issue by Raffy43** [lorddusk/HQM#283]
the crash report:

[crash-2017-02-28_14.06.36-server.txt](https://github.com/lorddusk/HQM/files/806856/crash-2017-02-28_14.06.36-server.txt)

**Comment by British89** [comment]
I am also having this problem, When ever i create a quest then try and pick up an item my server crashes, I also have the same crash while on singleplayer

crash report

[crash-2017-02-28_12.06.18-server.txt](https://github.com/lorddusk/HQM/files/807394/crash-2017-02-28_12.06.18-server.txt)

**Comment by canitzp** [comment]
This is a already fixed bug, but there is no released version with the fix
