### ISSUE TITLE
HQM-5.0.0beta4 & Immersive Engineering; Fluid NPE

### ISSUE THREAD

**Issue by BluSunrize** [lorddusk/HQM#284]
Heya Dusk and team!

I hope I didn't miss this issue in my search, but I had yet to see it reported.
Basically, this part of code:
https://github.com/lorddusk/HQM/blob/42109aa090d7c917d834e96f130b4b4a214d7fdc/src/main/java/hardcorequesting/client/interfaces/edit/GuiEditMenuItem.java#L502
passes null to the Fluid.getLocalizedName(FluidStack) method. There is a method of the same name that omits the stack, which might be more appropriate, since me personally assumed that FluidStack to not be null.

It caused the issue here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1926
Forge Version and other mods are found in the crashlog of that issue, but as far as I can see, this is between IE and HQM, and the null being passed.
I'll be adding a nullcheck there myself, but I'd encourage changing that method to the version without parameters :V

**Comment by Malus-Lupo** [comment]
I think this crash is related. Just thought I would post it and ask if there is a work around?

[crash-2017-03-14_18.12.37-client.txt](https://github.com/lorddusk/HQM/files/842935/crash-2017-03-14_18.12.37-client.txt)

**Comment by BluSunrize** [comment]
Yeah that's basically the result of the issue. Null passed to a method where some users might not expect a null.

**Comment by MidnightsFX** [comment]
Also seeing this error, but on ticking entity.
[NPE](https://pastebin.com/LtxmQbFJ)

I can provide more from the log if required.
