### ISSUE TITLE
[1.10.2] [Request] Update the 1.10.2 version with the Multiplayer Fixes from 1.11

### ISSUE THREAD

**Issue by MokahTGS** [lorddusk/HQM#285]
Please update the 1.10.2 version of the mod with the multiplayer fixes you added to the 1.11 version.  Most players and the mod community are working on 1.10.2 and since this mod is geared for mod packs it makes sense to fully support the most popular version.

**Comment by canitzp** [comment]
This is already planned and LordDusk started it.

**Comment by canitzp** [comment]
@MokahTGS one question I have now, do you have checked if it works in 1.11.2? For me it worked, but I don't know if it works for other peoples too
