### ISSUE TITLE
1.10.2 Crash Clicking in book.

### ISSUE THREAD

**Issue by MokahTGS** [lorddusk/HQM#286]
http://pastebin.com/zyNvGYJj

**Comment by canitzp** [comment]
This has been fixed in 1.11.2. You have to wait for @LordDusk s backport

**Comment by way2muchnoise** [comment]
Could you try [HQM-New Heights-1.10.2-5.1.0alpha2](https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2396680), which got released this morning and should fix quite some issues.

**Comment by MokahTGS** [comment]
I have been running the latest alpha for 1.10.2 and so far haven't crashed with this issue.  To be fair though, it wasn't automatically crashing before.  It was a bit random.

**Comment by way2muchnoise** [comment]
Then I'll close this for now feel free to reopen if it happens again.
