### ISSUE TITLE
[1.11.2] Crash while saving

### ISSUE THREAD

**Issue by Terpo** [lorddusk/HQM#287]
HQM-New Heights-1.11.2-5.1.0alpha2

https://gist.github.com/Terpo/b27be993a3564b0e85bccf76c6e86a49

I changed an icon of a crafting task. Then, without explicit saving I moved to the next task but I wanted to change it from crafting to detecting task. While I was trying to click on detecting the game crashed. I tried to reproduce it but wasn't able to do it^^.

After trying to reproduce I also saw that it is not possible to change the type of a quest atm.
That happens if you try to:
https://gist.github.com/Terpo/f2acfd71844c05f62fdbf3b60b6b98fe

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM

**Comment by Terpo** [comment]
I think this one can be closed for now. In the last weeks I added and changed a lot of quests without such a crash. If it happens again, I will call for help^^
