### ISSUE TITLE
[1.10.2] adding a reputation reward Crashing client

### ISSUE THREAD

**Issue by spr3n1x** [lorddusk/HQM#288]
I am trying to build a modpack that uses the reputation feature as a "currency" but when i try and add a reward for the reputation but when i click add new, It crashes and breaks the respective world that I am in.
Here is the crash log if needed
[http://pastebin.com/HLaSek2h](http://pastebin.com/HLaSek2h)

**Comment by way2muchnoise** [comment]
Could you try [HQM-New Heights-1.10.2-5.1.0alpha2](https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2396680), which got released this morning and should fix quite some issues.

**Comment by BrewingCoder** [comment]
I just experienced this issue on  Beta4, was unable to move past it and perform any sort of reputation reward.  The game was crashing with the same exception, which is what led me here.  Updating to Alpha4 has corrected my issue.

**Comment by BrewingCoder** [comment]
FYI am attaching my crash log under Beta4 so you can validate it is the same.  
[crash-2017-05-11_23.18.26-client.txt](https://github.com/lorddusk/HQM/files/994986/crash-2017-05-11_23.18.26-client.txt)

**Comment by canitzp** [comment]
Can't reproduce on latest 1.12.2 version anymore
