### ISSUE TITLE
Unable to add Chapter Titles with punctuation

### ISSUE THREAD

**Issue by Thenosis** [lorddusk/HQM#289]
Copied from my post on the project page's comments. 

 I don't really think this is a bug, I just think it needs to be said. Don't try to save ANY sets with punctuation in 1.10. I'm not sure about other versions but when trying to save Sets of quests, if you have any punctuation in the set title it won't save it, due to it being saved as a JSON file. Since files like that can't have punctuation it just plain won't save them. 

(And I know I sound derpy with this especially since I should know better being a programmer. It just never crossed my mind when trying to save my sets.)

Maybe have a warning in the editor's GUI that says "Do not try to save sets with punctuation. You will lose all progress." I swear I'm not this stupid. :P

Last edit: I hope I didn't come off as a jerk. I hate text.

**Comment by way2muchnoise** [comment]
Could you give and example of what punctuation you used? Makes it easier for me to test.

**Comment by Thenosis** [comment]
Sure. Two of my set titles were

 Blood for the Blood God!!! 
WOOT!!!!!

Just like that. And it would not save the set. Every time I would check the folder or exit the game. I also had one with a ? But that title changed so I don't remember what the full set title was.

**Comment by way2muchnoise** [comment]
I'm pretty sure ! since Invasion (darkosto's pack) uses that. But I can see the question mark or a slash being an issue.

**Comment by Thenosis** [comment]
I'll do some more testing with the ! and make a video if I run into anymore problems. I'll let you decide for when this issue is closed.
