### ISSUE TITLE
Reputation tasks do not detect the correct reputation instantly

### ISSUE THREAD

**Issue by DrasticDemise** [lorddusk/HQM#29]
When reputation detection is not the first task in a quest list (happens most often when it is the last quest part), it often requires players close and reopen their quest book for the reputation task to detect properly even if the player has the required reputation to start. This issue doesn't occur when reputation detection is the first quest in the line.

In case this is a unique instance to my pack, the files are in the mod pack Banished on the ftb launcher. If you need any extra information just poke me.

**Comment by way2muchnoise** [comment]
Does this still happen in 1.9+?

**Comment by canitzp** [comment]
Test this in 1.11.2 please. If it is still a bug, reopen the issue.
