### ISSUE TITLE
[1.10] Exception in server tick loop

### ISSUE THREAD

**Issue by Thenosis** [lorddusk/HQM#290]
Here is a copy of the crash log through Pastebin. It didn't cause any loading errors. I think it just caused an infinite loop somehow.

http://pastebin.com/y3uvCyqq

If this is not related to HQM please let me know which mod it is related too. You'll notice in lines 28-53(when using notepadd++) that it mentions HQM and that was the only mod that I could tell was mentioned. Hope this helps kill another bug.

**Minecraft** V _1.10.2_

**Forge** V _12.18.3.2221_

**Hardcore Questing Mode** V _HQM-New Heights-1.10.2-2.2.3-beta-4bd2a01-universal.jar_

**Comment by way2muchnoise** [comment]
Could you try [HQM-New Heights-1.10.2-5.1.0alpha2](https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2396680), which got released this morning and should fix quite some issues.

**Comment by Thenosis** [comment]
Okay. I have updated to 5.1.0alpha2. If I run into this again I will post the crash log as well as the version info like I did for this time. Personally, I'll consider the matter closed as I have not been able to replicate the error since updating to 5.1.0
