### ISSUE TITLE
Dropping HQM book and picking it back up causes crash

### ISSUE THREAD

**Issue by ThomasAunvik** [lorddusk/HQM#292]
Sometimes while editing in the HQM book, and when i drop it and right before picking it up it crashes the client.

[Crash](https://gist.github.com/ThomasAunvik/94cf725a9bac9c5fd1154c677ca32df0)

HQM: 5.1.0alpha2

**Comment by ThomasAunvik** [comment]
Seems this also happens when picking up other items too. And it seems to be a server crash, as the file name is: `crash-2017-03-30_13.09.14-server.txt`

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM

**Comment by Terpo** [comment]
Report is duplictate to #308
Should be fixed.
