### ISSUE TITLE
HQM Book Rendering is weird

### ISSUE THREAD

**Issue by ThomasAunvik** [lorddusk/HQM#293]
![img](http://i.imgur.com/Jp6Y1hz.png)
![img2](http://i.imgur.com/c9tMo5M.png)
HQM: 2-5.1.0alpha2

**Comment by canitzp** [comment]
As long as I can remember, these rendering bugs happened

**Comment by TwitchtvCarbs** [comment]
I think just an outline on the texture of the book should give it a clean black finish :) I've had this issue with my mod items too it seems to clip them sometimes around the edges.

**Comment by ThomasAunvik** [comment]
F

**Comment by canitzp** [comment]
This isn't a real issue, since the book looks like this since it existed. We can change the icon, if we get a suitable one, but it isn't a important feature.

**Comment by ThomasAunvik** [comment]
One reason could be alpha values on the border, for example if the outer alpha is between 0 and 1.
