### ISSUE TITLE
[1.10.2] Crash on death when running out of lives

### ISSUE THREAD

**Issue by ryvn** [lorddusk/HQM#295]
I was under the impression that this was a known bug, but I couldn't find an issue about it. If my search fu was weak, feel free to close this.

In version HQM-New Heights-1.10.2-5.1.0alpha2, running out of lives reliably causes a crash, at least in local singleplayer. I encountered this bug in the Invasion modpack, and on their git they indicated this was an HQM bug. I came here to track the issue and couldn't find it, so I thought I'd submit my crash log: https://pastebin.com/hhPhT6aJ

**Comment by way2muchnoise** [comment]
Likely a bug with HQM trying to delete the world or something like that, since you ran out of lives anyway. I should turn that off.

**Comment by way2muchnoise** [comment]
Fixed as of 4c7cf5b6de07ab4c95090e7901f519d8c6f20379
