### ISSUE TITLE
HQM 5-0-0 beta "saving" crash

### ISSUE THREAD

**Issue by redgoblin88** [lorddusk/HQM#296]
yesterday i was doing some work on my pack through the HQM as most/all recipes are going to be changed and this mod is going to help guide players through, however upon loading the same world that i left yesterday i was faced with this crash report.

in the pack i am using minetweaker, crafttweaker and modtweaker which are used to change recipes. one quest is affected as it uses a modified tinkers tool flint pickaxe with a wooden binding and wooden tool rod which is a shapeless recipe of all three parts, and yields it with only 16 durability compared to the regular 190 that you would get from the tool station, but this quest was successful at saving, unloading and loading back up before.

no new mods were added or removed

info for the "guidelines"

HQM - 1.10.2-5.0.0beta
forge - 12.18.3.2254
forge mod loader log - (dont know where it is located)

crashlog - https://pastebin.com/PDZ1r99x

**Comment by redgoblin88** [comment]
update: i have contacted mcjty a si have noticed he has contributed but he pointed out that i was not on the latest version, apparently the curse client showed that 5.0.0beta2 was the very latest however curseforge says otherwise as there was an update just five days ago

**Comment by way2muchnoise** [comment]
Yeah, the latest might be tagged as alpha and you can not always see that on the Curse client (it is a setting to see alpha iirc)
