### ISSUE TITLE
[1.11.2] Crash while selecting Bag Group in the HQM Book

### ISSUE THREAD

**Issue by ThomasAunvik** [lorddusk/HQM#297]
[Crash Log](https://pastebin.com/Cc5pwivY)
[Full Client Log](https://gist.github.com/ThomasAunvik/4bd3afab5f4190d67c2cce3d96d8b582)
HQM; 5.1.0alpha2

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM

**Comment by ThomasAunvik** [comment]
Fixed, Thank You.
