### ISSUE TITLE
[1.10.2 client crash when inviting a player to your team]

### ISSUE THREAD

**Issue by Saereth** [lorddusk/HQM#300]
crashlog:
https://gist.github.com/Saereth/a4bb7f28d54b24a2365da8c6679546aa

version: HQM-New Heights-1.10.2-5.1.0alpha2

**Comment by canitzp** [comment]
Please try it with a newer version of HQM

**Comment by Badger-One** [comment]
I had the same crash on version HQM New Heights (1.10.2-5.1.0Alpha4) on the modpack HQM
Crashlog: https://gist.github.com/CyberColonel/9fa14af214144271ff7177cbeb87f874

**Comment by canitzp** [comment]
@CyberColonel You posted the start of a log file. Please post the whole log file or the crash report file
