### ISSUE TITLE
[1.10.2 Op edit book crashes upon completing a quest]

### ISSUE THREAD

**Issue by Saereth** [lorddusk/HQM#302]
crashlog: https://hastebin.com/enotiqufoz.sql

HQM-New Heights-1.10.2-5.1.0alpha2

steps to reproduce: do /hqm edit, get op book, go into quest (in this case, bucket quest detection) click to complete the quest manually, game crashes with this error.

**Comment by canitzp** [comment]
Please try it with a newer version of HQM
