### ISSUE TITLE
[1.10.2] Severe FPS drop on opening of a page of quests.

### ISSUE THREAD

**Issue by Boomflex** [lorddusk/HQM#303]
Version: HQM-New Heights-1.10.2-5.1.0alpha3

When opening a page with a lot of quests on there such as (https://gyazo.com/6ff6a0c76292b70bca50673134716cb0) it drops from 200+ FPS to 6/7 FPS.

Before: https://gyazo.com/6f3318ac0affb2bf00b9083167a46fc8
After Opening: https://gyazo.com/ecb2c7487533efa866b432a9d949c760

This is on Invasion 1.0.2 pack with latest Forge.

Thanks.

**Comment by canitzp** [comment]
Probably one of the items in your quests, that needs a lot of rendering time
