### ISSUE TITLE
[1.10.2 Question/bug updating quests on a sever]

### ISSUE THREAD

**Issue by Saereth** [lorddusk/HQM#304]
After updating quests I copied the new quest files to the server from ssp into the config/hqm folder. When the server restarted it shows zero quests. Only by deleting the hqm folder in the world save on the server did it fully rebuilt and the quests started working. This is problematic as it obviously resets all teams and progress.

What is the proper way to update your quests on a server or is this just a bug?

**Comment by canitzp** [comment]
Try it with the help of #310
