### ISSUE TITLE
[1.10.2] Quests wiped on enabling Hardcore mode (Invasion Pack 1.0.4)

### ISSUE THREAD

**Issue by Boomflex** [lorddusk/HQM#306]
Forge Version: forge-12.18.3.2254
MC Version: 1.10.2
Modpack: Invasion 1.0.4.
HQM Version: 5.1.0alpha

When you start a party and set it to Hardcore mode, the quest book wipes itself on relogging.

See video for evidence.

https://youtu.be/OSYvqEv_NmA

This has been done 3 times in a row on fresh server installs.

Thanks.

**Comment by way2muchnoise** [comment]
That is strange, also you have zero lives left when you log in. Strange

**Comment by Boomflex** [comment]
Yeah I did notice that too...

It works in SSP, but SMP it does not.

**Comment by shashankgarg92** [comment]
Actually It doesn't work on single player too. But you can fix it. Just downgrade mod to Beta 4. That fixed it for me.

**Comment by canitzp** [comment]
Tra in latest version
