### ISSUE TITLE
Crash when inviting player who changed their Minecraft IGN recently

### ISSUE THREAD

**Issue by justin-munyer** [lorddusk/HQM#307]
Hey, I have a player who just changed their minecraft name yesterday and joined the server today.  When attempting to invite them to a party, or when they attempt to start their own party, the game crashes to menu (An existing connection was forcibly closed by the remote host).

Experienced and replicated on HQM-New Heights-1.10.2-5.1.0alpha4.jar within the Invasion modpack on FTB/Curse

**Comment by way2muchnoise** [comment]
Any errors in the logs?

**Comment by justin-munyer** [comment]
https://pastebin.com/kMxRfBDU

**Comment by way2muchnoise** [comment]
That crash log seems a lot like #284
