### ISSUE TITLE
1.11.2 HQM 5.1.0alpha2 Crash when picking up items

### ISSUE THREAD

**Issue by arfink** [lorddusk/HQM#308]
Running HQM with a few 1.11.2 mods, I made some quests in creative, and switched to survival to test. All was well, until I tried to pick an item up off the ground, causing the following crash:

FML crashlog: https://pastebin.com/uTwWWRdK

This seems to happen regardless of other mods as well. Could it be my quests?

**Comment by canitzp** [comment]
Please test it with the latest 1.11.2 version of HQM

**Comment by Terpo** [comment]
Seems to be fixed. My pack has something like 130 quests in 1.11.2 (alpha3) with a lot of detecting quests and so far I could not reproduce the crash anymore.
