### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by Shahhubminecraft** [lorddusk/HQM#309]
When will you be updating 1.10.2 of hqm because a lot of modpacks are using 1.10.2 and the 1.10.2 version of the pack atm is highly buggy and I have losts the quests multiple times and it be nice if the mod would be updated to fix a lot of the errors

~Shahhubminecraft

**Comment by way2muchnoise** [comment]
What version are you currently on? there have been a couple new alpha in like the past month?

**Comment by Shahhubminecraft** [comment]
Well there is no update available on curse for 1.10.2

**Comment by Shahhubminecraft** [comment]
All I want is for hqm to work on a server and not just single player

**Comment by way2muchnoise** [comment]
They are marked as alpha, you might want to set your launcher to show those as well.

This is the version Darkosto uses for Invasion and does work in both SP and MP.
https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2402526

**Comment by HermoidIronoak** [comment]
@way2muchnoise its isn't working in LAN though.... :(

**Comment by beringtom** [comment]
I'll just leave this here ;)

https://github.com/Darkosto/InvasionIssues/issues/179

**Comment by canitzp** [comment]
@beringtom Can you open a seperate issue for it
