### ISSUE TITLE
Migration guide from alpha2 -> alpha3 for 1.11.2 and alpha3 -> alpha4 for 1.10.2

### ISSUE THREAD

**Issue by Terpo** [lorddusk/HQM#310]
Hello!
This is NOT a bug report but a small guide how to migrate your hqm data from alpha2 to alpha3 in the 1.11.2 version of HQM.

_**EDIT by canitzp:**
This guide should also work for the migration from alpha3 to alpha4 of th 1.10.2 HQM version_

Make a backup folder of your old hqm config folder for safety.

**1st: the folder "quests" in config does not exist anymore**
the folder "remote" contains: 
data.json
deaths.json
state.json
teams.json
Old files are stored in the quests folder.

**2nd: there is a new folder "default**
it contains:
bags.json
description.txt
reputations.json
sets.json
and all your quest sets (like "the_beginning.json")

**3rd: in every quest set json you have to change up something small**
Open the quest set json, for example "the_beginning.json" in a text editor.
Then do a search -> replace operation
Search for: "fluidStack":
Replace with: "item":
That should to the trick

**4th: questdata in world files**
HQM is saving the questdata also in your world folder (a copy of the default)
As files are read from there first, you may want to remove them in case of crashing
"com.google.gson.JsonSyntaxException: java.lang.IllegalStateException"

I hope that helps everyone who needs to migrate from alpha2 to alpha3

**Comment by noobanidus** [comment]
Moved to a [Wiki](https://github.com/lorddusk/HQM/wiki/Migration-guide-from-alpha2----alpha3-for-1.11.2-and-alpha3----alpha4-for-1.10.2-%23310) page.
