### ISSUE TITLE
[1.11.2] NoSuchMethod crash - team related

### ISSUE THREAD

**Issue by Terpo** [lorddusk/HQM#311]
Alpha3 with forge 13.20.0.2278
https://gist.github.com/Terpo/be77fa41689e7593fec5ee1cc90f1321

I was trying some blocks, and when breaking the block the game crashed.

Crash is related to team stuff. I'm editing with the OP book but did not joined a team so far (why should I ^^)

**Comment by way2muchnoise** [comment]
As background info, a player is always in a team (some in memory team when not actually in a party).

But that seems like a client method called on the server side.

**Comment by Terpo** [comment]
Happened in SP without opened lan server if that helps.

**Comment by plunginghornets** [comment]
Exact same bug. I just started a fresh world and broke a single block of wood and crashed. No team stuff, not even opened to lan. [crash report](https://gist.github.com/plunginghornets/a459979b831e011f5801aac9ced58fd2)

**Comment by TwitchtvCarbs** [comment]
This bug still exists using forge 13.20.0.2282 Mc1.11.2 Hqm Alpha3

https://github.com/TwitchtvCarbs/The-Collection-Issues/issues/30

**Comment by way2muchnoise** [comment]
@TwitchtvCarbs ~~you could at least try the latest alpha which is 4. https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2402526~~

EDIT: didn't see the 1.11.2, my bad

**Comment by TwitchtvCarbs** [comment]
I wonder did forge git rid/ change that method in 1.11.2? Perhaps that's why it can't be found? I'm presuming the mod is ported from 1.10 to 1.11 using the same-ish code which in 1.11.2 can cause issues with item handling being different.

**Comment by way2muchnoise** [comment]
I changed that method to be server side only, my guess is that it still gets called client side in 1.11.2 somewhere. aka regression

**Comment by TwitchtvCarbs** [comment]
Yeah its pretty bad, It only seems to happen in local single player worlds but breaking a block or picking up an item seems to cause the crash repeatedly. I did have some luck opening the book then I could play but Im not sure having to open the book everytime you log is convenient XD It's also not guaranteed to work which makes testing things in the single player world right now a little hard for making my updates D: Especially when I die and then i cant even pick up the book to open it after a crash lol

**Comment by Terpo** [comment]
It seems that this problem only happens in SinglePlayer worlds. After some testing in a dev environment I can confirm that a server<->client system works. 

Deleting @SideOnly(Side.SERVER) on getPlayerMP() solves the problem for the SP part.

**Comment by way2muchnoise** [comment]
@Terpo but isn't a solution as I assume that there is server access in that method. Which is obviously not the case on the client side.

**Comment by TwitchtvCarbs** [comment]
Any progress on this issue? :3

**Comment by way2muchnoise** [comment]
I have progress on my thesis, but not on this issue. I'll be done once my finals are over, which should be mid or end of june.

**Comment by TwitchtvCarbs** [comment]
Gotcha gotcha, sorry I asked lol was just wondering :/

**Comment by ghost** [comment]
Similar crash also happens when picking up items with NBT...

**Comment by canitzp** [comment]
Pls test with current versions
