### ISSUE TITLE
[1.11.2] Changing quest type not possible

### ISSUE THREAD

**Issue by Terpo** [lorddusk/HQM#313]
Alpha3 with forge 13.20.0.2278
https://gist.github.com/Terpo/f2acfd71844c05f62fdbf3b60b6b98fe

Simply create a quest and try to change its type to something different. It does nothing but puts out the log above. No crash and just a minor problem.

**Comment by noobanidus** [comment]
Presumably this was fixed. HQM is no longer under active development for 1.11. If the issue still occurs in 1.12.2, please open a new issue.
