### ISSUE TITLE
[1.10.2][Bug] TIC Ranged Weapons and Kill Monster Quests

### ISSUE THREAD

**Issue by Utildayael** [lorddusk/HQM#314]
I'm not sure if this is a Tinkers issue or a HQM issue so I apologize in advance.

Testing out the pack I'm working on last night and I have a section with all the kill x <insert creature> quests, for example, kill 10 zombies.

I spawn the zombies with mob eggs and then shot them with a Tinkers longbow. Looked at my quest book and said my kill count for the quest was still 0. Ok figured it didn't like me being in creative so I tried again in survival. Same deal. 0 kills. On a whim I grabbed a sword and proceeded to stab the zombies to death and THAT worked fine.

So... for some reason ranged kills with TIC weapons aren't registering as kills in HQM yet they register with FTB Utils and the vanilla Minecraft statistics. 

Workaround of course is to just use a vanilla bow or a sword so it isn't game-breaking but something I'll have to note on the quest chapter for the players.

**MC 1.10.2
Forge 12.18.3.2281
HQM 1.10.2-5.1.0alpha4
Tinkers 1.10.2-2.6.3**

Thanks!

**Comment by noobanidus** [comment]
HQM is no longer under active development for 1.10. If the issue still occurs in 1.12.2, please open a new issue.
