### ISSUE TITLE
Resetting Quests

### ISSUE THREAD

**Issue by NathanConnors** [lorddusk/HQM#315]
I'm having an issue where the quest book gets reset on the Invasion Mod Pack every time I restart the client. I have been using /HQM edit to get the cheat book and redo the done quests but it is getting annoying.

Thank you,

**Comment by way2muchnoise** [comment]
Are you playing single player or multiplayer?

**Comment by NathanConnors** [comment]
single player

**Comment by NathanConnors** [comment]
In the current update of Invasion pack this has been addressed, apologies thought it was a HQM issue not the pack issue.
