### ISSUE TITLE
[1.10.2] Reputation requirements not being saved to JSON

### ISSUE THREAD

**Issue by arfink** [lorddusk/HQM#316]
In 1.10.2-5.1.0alpha4, when adding a reputation requirement with the in-game editor, it will not save correctly. Regardless of what settings I pick for the reputation requirement, the resulting JSON file will not save the required data. For example, I make a quest that requires 64 cookies and a reputation level, and the JSON only shows:

"tasks":[{"type":"CONSUME","items":[{"item":{"id":"minecraft:cookie"},"required":64}]},{"type":"REPUTATION","reputation":[]}],

**Comment by tethlah** [comment]
I'm running into this issue as well.  Since it was first reported 2 months ago, is there any update on a plan of action to fix it?

**Comment by canitzp** [comment]
Reputation isn't a thing I can fix nor do I really care about it. We also already decided that when a rewrite happens in the future, the reputation are droped completly
