### ISSUE TITLE
[1.10.2] Some complex items do not save NBT data correctly in loot bags or quest rewards

### ISSUE THREAD

**Issue by arfink** [lorddusk/HQM#317]
I have found two kinds of items which do not save NBT data correctly when placed in loot bags or quest rewards, namely, enchanted items with colored runes from Quark mod, and custom blocks from Chisel and Bits. Could this be a future feature if this isn't a bug?

**Comment by arfink** [comment]
FYI, right now I am trying to work around this issue using the quest command feature, although that is also not behaving the way I think it should. I have not yet determined that behavior to be a bug, and is probably just me being dense.

**Comment by canitzp** [comment]
Can you provide some more information about your MC-Instance like versions or log files
