### ISSUE TITLE
Can not open quest book after changing editmode to true

### ISSUE THREAD

**Issue by Antonwinther99** [lorddusk/HQM#32]
title says it all.

**Comment by lorddusk** [comment]
Multiplayer?

**Comment by Antonwinther99** [comment]
Yes

**Comment by Antonwinther99** [comment]
I have to eat now, but reply as soon as i can after i'm done eating.

**Comment by lorddusk** [comment]
That's why. We don't support quest editing in multiplayer.

**Comment by Antonwinther99** [comment]
Oh, derp, thank you.

**Comment by theonlyjohnny** [comment]
Do you think this will change ever? I am trying to make a modpack with a group and we'd all like to work on the quests at the same time.
