### ISSUE TITLE
[1.10.2] Kills Counting as Multiple

### ISSUE THREAD

**Issue by Utildayael** [lorddusk/HQM#320]
Odd one for ya. We have some kill x of y type quests in our pack and as I was testing I noticed that killing say, 1 pig, results in HQM saying I've killed 4 pigs! This was using a vanilla stone sword so nothing special. Chickens, cows, sheep, etc all have the same issue. The quest was set to kill 15 pigs but after killing 4 it was marked done as it thought you had killed 16. 

MC 1.10.2
Forge 12.18.3.2281
HQM 1.10.2-5.1.0alpha4

**Comment by noobanidus** [comment]
HQM is no longer under active development for 1.10. If the issue still occurs in 1.12.2, please open a new issue.
