### ISSUE TITLE
[1.10.2] HQM Questbook blank for other player in LAN connection

### ISSUE THREAD

**Issue by RaineAndrews** [lorddusk/HQM#321]
In the latest Nuts and Bolts: Torqued modpack.  Issue was originally reported at their github at

[https://github.com/breakinblocks/nutsandboltstorqued/issues/174#issuecomment-299496717](url)

**Comment by canitzp** [comment]
Can you provide further information about your MC-Instance like MC-version, forge-version, log files, etc

**Comment by RaineAndrews** [comment]
Nuts and Bolts Torqued 1.6.4.7
Minecraft 1.10.2
Forge 12.18.3.2254

I'm not sure log files would be created.  There isn't a crash, it just doesn't have any quests for the second player in the LAN.

**Comment by resinate** [comment]
HQM configs dont push to NON cheat mode single player worlds

**Comment by canitzp** [comment]
fixed in 5.4.0 (eta feb next year)
