### ISSUE TITLE
[1.10.2] HQM cannot detect Thermal Expansion Machines

### ISSUE THREAD

**Issue by Redlotus99** [lorddusk/HQM#323]
I have crafting quests to craft each Thermal Expansion machine, but I cannot get HQM to recognize the machines. I have tried Fuzzy detection and also tried it as a crafting quest and a detection quest to no avail. Any idea how I can make this work or possibly what I'm doing wrong?

**Comment by way2muchnoise** [comment]
For what version of mc, hqm and te is this?

**Comment by Redlotus99** [comment]
MC - 1.10.2
HQM - HQM-New Heights-1.10.2-5.1.0alpha4.jar
TE - ThermalExpansion-1.10.2-5.0.4.90-universal.jar
Forge - 1.10.2 - 12.18.3.2281

**Comment by noobanidus** [comment]
HQM is no longer under active development for 1.10. If the issue still occurs in 1.12.2, please open a new issue.
