### ISSUE TITLE
[1.10.2] invasion mod versions 1.0.5-1.0.7 new players unable to create teams

### ISSUE THREAD

**Issue by lolman2810** [lorddusk/HQM#324]
Hi, i have been scouring both your github the invasion github and been unable to find a solution to this problem.

i have set up a multiplayer invasion server (started with 1.0.5 and has now been updated to 1.0.7)
modpack uses HQM-New Heights-1.10.2-5.1.0alpha4

in 1.0.5

- when the server was started we were able to make 1 team (the initial 3 players)
- we were then unable to add new players once we had started questing, invites appeared to send but did not show up in other players books
- deleted all server files and reinstalled - could then start a new team and have 4 people in it.
- still could not add any more players once we started questing
- new players could also not create new teams

now in 1.0.7

- original 4 player team can access their quest books and complete quests as usual
- new players are unable to see anything in their quest books
- even when /op'ed /hqm quest and /hqm edit do not allow them to start quests themselves
- new players are still unable to make teams

any suggestions would be greatly appreciated
if you needs any specific info / logs / config etc just ask
if you have a nodecraft account you could even look at the console / files if needed

kind regards

**Comment by canitzp** [comment]
teams and parties are fixed in 5.4.0 (eta feb next year)
