### ISSUE TITLE
Reward bags not working!

### ISSUE THREAD

**Issue by GameroftheUndead** [lorddusk/HQM#327]
I'm making a modpack and using HQM for the quest book and rewards! I released a new update of the modpack and I found out that reward bags were no longer droping loot! I've tried looking for solutions but can't find any! The config is right too! Also, reward bags were working fine before I made an update!

Any help is appreciated thank you!

**Comment by way2muchnoise** [comment]
MC version? HQM version? any mods that might interfere? This report is rather incomplete.

**Comment by GameroftheUndead** [comment]
Oh right sorry!
The MC version is 1.7.10
The HQM version is "HQM The Journey (4.4.4)"
I do not beleive there are any mods that would interfere, the only other questing mod I have in the modpack are Better Questing and Better Questing - Standard Expansion but HQM was not working before those mods were in! I only added BQ because the reward bags weren't working so I was going to try to replace them with BQ's loot chest but there were a lot of quests w/ reward bags that had to be changed so I thought I'd look for a fix before removing all of them! 

Sorry for the lack of detail earlier! If you need more please ask! Ty!

**Comment by canitzp** [comment]
to old, won't fix
