### ISSUE TITLE
Adding quests

### ISSUE THREAD

**Issue by beeger33** [lorddusk/HQM#329]
ok i have the 800+ quests and i found a few more quests .jsons i would like to add how do i do it so they show up in the book

**Comment by way2muchnoise** [comment]
Version of mc and HQM? But usually use the `/hqm load <name of the json>` command.

**Comment by beeger33** [comment]
1.7.10 and 4.4.4

**Comment by beeger33** [comment]
how do i read the quests.hqm file

**Comment by beeger33** [comment]
it sez i do not have permission
