### ISSUE TITLE
[1.11.2] Task with multiple crafting steps not working

### ISSUE THREAD

**Issue by Terpo** [lorddusk/HQM#331]
Alpha 3 for 1.11.2
I have a crafting task where a player has to craft multiple tools, see gist:
https://gist.github.com/Terpo/23a87eab61be52334e2f2ffe45e228cf

The first tool (shovel) is recognized. All other tools stay at 0%.

Tested on server <-> client environment.

**Comment by Terpo** [comment]
I've uploaded a cleaned fml server log from the last 24h for you. There are serval HQM crafting event errors.
https://gist.githubusercontent.com/Terpo/c1feca98c59a03fb7318602258fb5ce8/raw/0515d7f2a0febb0463595dd7eae5314a598ad9fb/gistfile1.txt

another side effect is, that you will get your item from crafting, but when closing the crafting table you also get back your items.

also verified this with just JEI and HQM alpha 3 for 1.11.2 installed

**Comment by noobanidus** [comment]
There's no active development for HQM in 1.11.
