### ISSUE TITLE
[1.10.2] SpawnBook=true seemingly not working

### ISSUE THREAD

**Issue by Cavin-V** [lorddusk/HQM#332]
I am trying to make a modpack that includes some small quests to help people figure out mods that might have changed from how most people understood them, or mods that are just in general hard to understand. however as the config setting for spawning the book is set to true the book does not spawn on the player upon a new world creation. I am unsure as to why this has happened and It has always been the case since the modpack was first created.
HQM version: "HQM-New Heights-1.10.2-5.0.0beta4.jar"
Forge version: "forge-12.18.3.2281"
I am not 100% sure a FML log would be of any assistance, along with that I cannot seem to FIND the FML log in the first place, so if the FML log is truly needed I will find it wherever its hiding

**Comment by canitzp** [comment]
This happens if a different mod overwrites the default spawn items. This isn't uncommon for Modpacks. The feature works as intended in the latest versions
