### ISSUE TITLE
[1.11.2] Quest Gate blocks do not work

### ISSUE THREAD

**Issue by Dominance** [lorddusk/HQM#334]
Pretty much as the subject states. I cannot get the quest block to function at all. outside being a unbreakable block. It shows that you can assign the quest to the block. How ever after multiple attempts, on quest completion the linked gate does not do anything. I have tested this in edit mode, then edit mode link gates quit game, turn off edit mode. reload and go back to world and complete quest. Just cannot get it to function.

**Comment by canitzp** [comment]
#362
