### ISSUE TITLE
[Request] Modify world border on quest completion feature

### ISSUE THREAD

**Issue by blu0191** [lorddusk/HQM#336]
I was wondering if you could add a feature for modpack/questbook makers to modify the world border when a quest is completed? Would be awesome

**Comment by Cavin-V** [comment]
the same outcome could come from just making a quest do the command to change the world border

**Comment by noobanidus** [comment]
As noted above, it's possible to use a /command to change the world border as a result of a quest being completed. I think this would be feature creep as the possibility already exists.
