### ISSUE TITLE
[1.10.2] Server side quests not loading

### ISSUE THREAD

**Issue by Cavin-V** [lorddusk/HQM#337]
As I am making a modpack that includes quests it is only natural I would try to make a working server for the modpack for people to play with their friends in the modpack.
however when I open the questbook on the server even though the quests work perfectly fine in singleplayer, when the quest configs are copied over to the server, it does not seem to load at all.
The strangest part is that when I go and make a new quest in the empty questbook and restart the server it saves the quest and loads that perfectly fine, now sure this could mean I could just re-make the quests on the server itself, however that would take 2x the amount of time to do and I would not really want to do this. I have looked around in the json files for quests in both the config and the server used world itself, and the new quest is nowhere to be found, only the old quests copied over from singleplayer. I have looked around a bit for any other location the mod might be storing the quest but I cannot seem to find any traces of the new quest anywhere in the files for the server.
HQM version: "HQM-New Heights-1.10.2-5.0.0beta4.jar"
Forge version: "forge-12.18.3.2281"

**Comment by resinate** [comment]
yep can confirm quests do not load server sided, or pushed to modpacks on curse.

this is for version 1.10.2 only tho.

**Comment by canitzp** [comment]
server side syncing is fixed in 5.4.0 (eta feb next year)
