### ISSUE TITLE
[1.11.2] Random client-side crashes

### ISSUE THREAD

**Issue by TheLimePixel** [lorddusk/HQM#339]
The client randomly crashes whenever the player Right-clicks or left-clicks in the world: https://pastebin.com/xCngj9Ky I'd suggest fixing this fast as it makes packs with the mod practically unplayable and otherwise a few thousand people won't be happy.

**Comment by CruzBishop** [comment]
Going to attempt a patch soon, just setting up the workspace :)

**Comment by TheLimePixel** [comment]
Woops. Welp, now I'd just rather have the mod update to 1.12, as  i don't plan on spending 3 whole days again making quests for the new progression line of my pack, when it's only going to get updates for 1 more week.
