### ISSUE TITLE
[1.11.2] Bags randomly delete themselves

### ISSUE THREAD

**Issue by TheLimePixel** [lorddusk/HQM#340]
So I worked on the bags for my pack for 2h just to have them randomly delete themselves. This has happened to me 3 times already. I create the tiers with the groups, run the game a few times, everything is alright and then out of a sudden, the next time I load up the pack they are gone and the ones in the remote folder are empty.

**Comment by noobanidus** [comment]
1.11 is no longer being actively developed for HQM.
