### ISSUE TITLE
1.10.2 Incompatibility between Geographicraft and Hardcore Questing mode

### ISSUE THREAD

**Issue by Dilnu** [lorddusk/HQM#341]
Hi there, I'm working on a modpack and I've noticed there seems to be an incompatibility between Geographicraft and Hardcore Questing mode. Specifically the HQM data fails to be copied from default into the save directory of the new world when Geographicraft is enabled.

If I then manually enable Questing Mode with /hqm quest I get a blank quest book. 

If it helps I can upload any of the config files but I'm running with geographicraft unconfigured and a very simple set of dummy quest data.

I'm on Minecraft version 1.10.2
Forge Mod Loader version 12.18.3.2297
GeographiCraft 0.8.7
HQM-New Heights 1.10.2 5.0.0beta4
jei 1.10.2 3.14.7.420

My FML log is here: https://pastebin.com/YMBnFCqb

**Comment by canitzp** [comment]
There is nothing in the log and the error doesn't make any sense at all
