### ISSUE TITLE
Tinkers' tools not setting off completion

### ISSUE THREAD

**Issue by tethlah** [lorddusk/HQM#342]
For some reason when I create quests with Tinkers', it seems to have a 50/50 chance of detecting a tool as a detection task.  I tried to make a trigger quest so that when they break a tinkers tool, it shows a quest line, but for some reason it doesn't trigger unless you manually detect it.  Which is a problem because it's invisible so they can't manually detect.

**Comment by canitzp** [comment]
They have a lot of nbt, so you need to do a nbt independent or fuzzy detection, problem then is that they are all the same no matter wich materials they are made of if you're using nbt independent detection.
