### ISSUE TITLE
Seared Brick won't register

### ISSUE THREAD

**Issue by KCFly1OH** [lorddusk/HQM#347]
When I pull a seared brick from my furnace, my HQM Quest Book doesn't register the item in my inventory. I've tried it on two different worlds now. Not sure what information I need to provide to possibly find a fix. Not seeing anyone else have this issue in a google search. I'm using ATLauncher Console 3.2.3.7 and running R&Q's Endless Modpack. I didn't find anyone having this issue on the webpage for the Modpack either (although I may have just not known how to look). The Modpack runs Minecraft 1.7.10 mods. I haven't added anything or removed anything from the pack.

Thanks for any feedback. 👍

**Comment by canitzp** [comment]
1.7.10 is outdated, sorry
