### ISSUE TITLE
Crash on item pickup single and mp

### ISSUE THREAD

**Issue by James-Webb554** [lorddusk/HQM#349]
java.lang.NullPointerException: Ticking player
	at hardcorequesting.team.Team.createQuestData(Team.java:402)
	at hardcorequesting.team.Team.getQuestData(Team.java:407)
	at hardcorequesting.quests.QuestingData.getQuestData(QuestingData.java:118)
	at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:96)
	at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:92)
	at hardcorequesting.quests.task.QuestTaskItemsDetect.countItems(QuestTaskItemsDetect.java:79)
	at hardcorequesting.quests.task.QuestTaskItemsDetect.onItemPickUp(QuestTaskItemsDetect.java:46)
	at hardcorequesting.event.EventHandler.onEvent(EventHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_498_EventHandler_onEvent_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:409)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

Crash happens on both mp and single player upon picking up any item modded or vanilla. 

Multiplayer crash 

Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.EntityItemPickupEvent@747b58c:
15.07 23:51:29 [Server] INFO java.lang.NullPointerException
15.07 23:51:29 [Server] INFO at hardcorequesting.team.Team.createQuestData(Team.java:402) ~[Team.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.team.Team.getQuestData(Team.java:407) ~[Team.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.QuestingData.getQuestData(QuestingData.java:118) ~[QuestingData.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:96) ~[QuestTask.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:92) ~[QuestTask.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTaskItemsDetect.countItems(QuestTaskItemsDetect.java:79) ~[QuestTaskItemsDetect.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTaskItemsDetect.onItemPickUp(QuestTaskItemsDetect.java:46) ~[QuestTaskItemsDetect.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.event.EventHandler.onEvent(EventHandler.java:86) ~[EventHandler.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_345_EventHandler_onEvent_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:409) [ForgeEventFactory.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:370) [yk.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578) [zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570) [zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) [zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
15.07 23:51:29 [Server] Server thread/ERROR [FML]: Index: 9 Listeners:
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 0: HIGHEST
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 1: ASM: cofh.thermalfoundation.util.EventHandlerLexicon@71c265ef handleEntityItemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 2: NORMAL
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 3: ASM: ic2.core.IC2Achievements@2c28c0a2 onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 4: ASM: WayofTime.bloodmagic.util.handler.event.WillHandler@6bd037bb onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 5: ASM: vazkii.botania.common.item.ItemFlowerBag@6a376822 onPickupItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 6: ASM: mod.chiselsandbits.items.ItemBitBag@5b7cc9e7 pickupItems(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 7: ASM: com.brandon3055.draconicevolution.achievements.Achievements@77b4c2d8 entityPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 8: ASM: forestry.core.EventHandlerCore@3d7fa9ea handleItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/ERROR [FML]: 9: ASM: hardcorequesting.event.EventHandler@1b5fc0fc onEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
15.07 23:51:29 [Server] Server thread/WARN Failed to handle packet for /109.153.169.36:57176
15.07 23:51:29 [Server] INFO net.minecraft.util.ReportedException: Ticking player
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
15.07 23:51:29 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
15.07 23:51:29 [Server] INFO Caused by: java.lang.NullPointerException
15.07 23:51:29 [Server] INFO at hardcorequesting.team.Team.createQuestData(Team.java:402) ~[Team.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.team.Team.getQuestData(Team.java:407) ~[Team.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.QuestingData.getQuestData(QuestingData.java:118) ~[QuestingData.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:96) ~[QuestTask.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTask.getData(QuestTask.java:92) ~[QuestTask.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTaskItemsDetect.countItems(QuestTaskItemsDetect.java:79) ~[QuestTaskItemsDetect.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.quests.task.QuestTaskItemsDetect.onItemPickUp(QuestTaskItemsDetect.java:46) ~[QuestTaskItemsDetect.class:?]
15.07 23:51:29 [Server] INFO at hardcorequesting.event.EventHandler.onEvent(EventHandler.java:86) ~[EventHandler.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_345_EventHandler_onEvent_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
15.07 23:51:29 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:409) ~[ForgeEventFactory.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:370) ~[yk.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578) ~[zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570) ~[zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
15.07 23:51:29 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
15.07 23:51:29 [Server] INFO ... 9 more
15.07 23:51:29 [Disconnect] User _Zerys has disconnected, reason: Internal server error
15.07 23:51:29 [Server] Server thread/INFO _Zerys left the game

**Comment by AWolters-ru** [comment]
Can confirm this is a problem, it seems like the mod tries to send the data to your team, even if you are not in one. No idea whether that is right, but creating a one person team fixed the issue for me.

**Comment by canitzp** [comment]
Old version, pls update to 1.12 and reopen when it happens again
