### ISSUE TITLE
Configs dont load on single worlds

### ISSUE THREAD

**Issue by resinate** [lorddusk/HQM#354]
HQM configs dont read/load when using worlds that dont have cheat mode enabled

Version 1.10.2 running latest version of the mod

**Comment by way2muchnoise** [comment]
Which configs?

**Comment by resinate** [comment]
hqmconfig.cfg none of the settings work

i flagged stuff like:
    # Use this if you want the book to spawn on create world
    B:SpawnBook=true

    # If set to true, new worlds will automatically activate Questing mode
    B:"Auto-start questing mode"=true

makes new world, says HQM is not enabled

**Comment by way2muchnoise** [comment]
Sure it says that? And not that hardcore questing is not enabled? Cause you can have questing without the lives AKA questing mode.
