### ISSUE TITLE
Party Data Corruption

### ISSUE THREAD

**Issue by JieSheng03** [lorddusk/HQM#355]
So on a particular server, with a particular mod pack The Simple Life 2, when creating a party, the player's data and quest just go missing. It shows 0 quest in total as such although it starts with a single quest. For this, the player could not even see if he/she was in the party. Is there a fix for this?

**Comment by way2muchnoise** [comment]
MC version, forge version, HQM version? This is a rather incomplete report.

**Comment by JieSheng03** [comment]
MC Version// HQM 1.10.2 5.1.0 Alpha 4// Forge 12.18.3.2254

**Comment by JieSheng03** [comment]
Doing /hqm edit just says that the player does not exist, as I have a edit book before that, it says that I have no permission when I open it.

**Comment by way2muchnoise** [comment]
To use an edit book you need to OP on the server, are you?

**Comment by JieSheng03** [comment]
I am, after I did /hqm enable, it reset all data and worked suddenly. But is there a way without /hqm enable?

**Comment by lorddusk** [comment]
No, because that would mean you could use the mod, without enabling it first. If you want to edit quests, go into edit mode (change the config settings outside of the game).

**Comment by JieSheng03** [comment]
Is there to reset one's quest data?

**Comment by way2muchnoise** [comment]
Just remove the json files that keep track of it. It should be in your world folder.

**Comment by JieSheng03** [comment]
What about on a server?

**Comment by lorddusk** [comment]
Uses the same method, you can remove the relevant data from the world folder on a server.
