### ISSUE TITLE
Crash when picking up blocks?

### ISSUE THREAD

**Issue by Malus-Lupo** [lorddusk/HQM#356]
[crash-2017-09-19_09.09.48-server.txt](https://github.com/lorddusk/HQM/files/1314572/crash-2017-09-19_09.09.48-server.txt)

I Keep crashing when picking up blocks that are needed for a quest.  Minecraft 1.11.2  Latest HQM on Curse.

Any work around would be nice to?

**Comment by canitzp** [comment]
Impossible bug. Probably different versions between client and server or a corrupted hqm jar file.
