### ISSUE TITLE
No progress being saved on a server?

### ISSUE THREAD

**Issue by DeadSix27** [lorddusk/HQM#357]
(This is on 1.10.2)

Edit mode is off on client and server.

B:ServerSync is set to true on both, client and server.

Both client and server have the default config subfolder with all the quests in etc.

Remote folder is empty on both.

So I join the server, all quests appear fine, however once I complete one, then shut down and restart both client and server and rejoin, my progress is not saved (nor are parties)

What am I doing wrong?

**Comment by canitzp** [comment]
I have to check this, but for me your description sounds right, so idk if it doesn't work

**Comment by DeadSix27** [comment]
Uh, that's from 2017, and on 1.10, I moved to 1.12 quite a while back, you'll need to check if it still appears in 1.12 otherwise feel free to just close this.
