### ISSUE TITLE
Gates no longer function 1.11/1.12

### ISSUE THREAD

**Issue by Dominance** [lorddusk/HQM#362]
The GUI no longer works as well as the assignment of quest to a gate.

**Comment by canitzp** [comment]
I can confirm that Quest Delivery Systems aren't working everytime. They are voiding every item you pump into and if you pump the needed items in it, they sometimes don't react, so you have to push a second time -> fixed after reassigning the Task to the QED

**Comment by canitzp** [comment]
I fixed gates more or less some time ago with one of the already released versions (1.12.2 only)
