### ISSUE TITLE
HQM Items in Creative Tabs

### ISSUE THREAD

**Issue by Cazadorsniper** [lorddusk/HQM#363]
In HQM New Heights (1.12.x-5.2.0Alpha1) the items are leaking into every creative tab, modded and vanilla.

Its actually just the reward bags in every tab.

**Comment by canitzp** [comment]
This bug was fixed an hour after the release. It isn't it worth to put out a new one for only such an issue, but maybe you find one of the other new bugs too xd

**Comment by theDaleighChronicle** [comment]
This bug has not been fixed. It is still leaking the bags into every creative tab.
