### ISSUE TITLE
simplified Chinese problem

### ISSUE THREAD

**Issue by StarZxz** [lorddusk/HQM#364]
Hello, my game version is: 1.10.2, but when I am in the main page (the first page to open the task of the book) set the text (simplified Chinese), exit games into the text and mark all become garbled, encoding seems to be wrong, what should be how to set up the simplified Chinese。
THANK YOU
： ）

**Comment by canitzp** [comment]
The non-rewrite version and also the rewrite version only supports UTF-8 characters and they should work. For the rewrite on the other hand I plan to use external localization files for the questbook texts
