### ISSUE TITLE
(Question) Is there a way to enable HQM on some worlds and not others? / Multiverse Support?

### ISSUE THREAD

**Issue by xWhatsherfacex** [lorddusk/HQM#365]
I'm running a Modded 1.7.10 Server using Multiverse and was wondering if it is possible at all to enable the Hardcore functionality on only some worlds. Meaning that, if Players ran out of Lives they wouldn't be banned from the server itself, but rather banned from that particular world in the server until they earn more lives. Is this possible in any way, or is it just wishful thinking?

**Comment by canitzp** [comment]
Not in the non-rewrite versions. For the rewrite I plan to have a dimension blacklist/whitelist and support for multiple quest books per instance
