### ISSUE TITLE
[1.10.2] Crash on 2nd load

### ISSUE THREAD

**Issue by Krougal** [lorddusk/HQM#367]
Crash when opening a world (so start new game, then exit to menu/desktop, try to open world again)
This is happening from my own pack I'm trying to make 
[crash-2017-11-03_20.37.37-server.txt](https://github.com/lorddusk/HQM/files/1442786/crash-2017-11-03_20.37.37-server.txt)
but it happens to me with Nuts and Bolts Torqued as well.

**Comment by Krougal** [comment]
Seeing this happening in 1.12.2 as well, realized it is because the config files are very touchy and default and remote need to be in sync. Are there any good rules on editing by hand? Much as I appreciate the ingame editor, it is a bit clunky when you've got 100+ quests you want to implement.

Solution to saves not loading is to delete the HQM files from the save and then let them be regenerated on next load.

**Comment by canitzp** [comment]
I can't reprocuce the error in my local DEV environment. Would you please test it with the latest 5.3.1 version and then provide? Is you HQM right configured at the server? quests only in config/hqm/default and the ServerSync config to true?

**Comment by noobanidus** [comment]
This is a year old and for a version of MC HQM is not in active development for.
