### ISSUE TITLE
[Suggestion/Request] Voice-over mode/Read it out loud button for dyslexic people.

### ISSUE THREAD

**Issue by ghost** [lorddusk/HQM#369]
Lots of people are dyslexic and I make modpacks, I would love it if HQM had a voice mode which plays on when you click on a button in a quest. This would be really great for dyslexic people and for people wanting to do voice overs with their quests.

**Comment by ghost** [comment]
Hello?

**Comment by way2muchnoise** [comment]
There isn't any active development going on right now for the mod. So you'll have to be patient.

**Comment by mirairoses** [comment]
This could also just be fixed with a mod for bigger fonts in Minecraft. But I like how you thought about those people too.

**Comment by noobanidus** [comment]
While this is a really great idea, I think it's beyond the scope of the mod. Compatibility with another mod that includes Text-to-Speech is certainly an option though.
