### ISSUE TITLE
Crash 4.3.2

### ISSUE THREAD

**Issue by SvEgiiVEteR** [lorddusk/HQM#37]
http://pastebin.com/Qb6UG7RB

**Comment by lorddusk** [comment]
Yes. That's a crash.

**Comment by SvEgiiVEteR** [comment]
the error was due to mod
https://github.com/CannibalVox/NoTimeFix/releases

**Comment by lorddusk** [comment]
you don't need that mod anymore, it's implemented into HQM directly.
