### ISSUE TITLE
Questbook Crashing and No Response to Issue Tickets

### ISSUE THREAD

**Issue by Boolyman** [lorddusk/HQM#371]
The Questbook is unusable at this point.  After a certain number of quests the questbook becomes fragile... crashing the game back to the main menu after clicking on an icon or hitting escape.  Messages to the dev haven't been responded to, and other tickets for the same thing have been left untouched.  I have a pack coming out soon, and will be forced to switch to the Better Questing Mod, which has a history of being supported even less than this mod is.  Really disappointing.

MC 1.12.2
Forge 14.23.0.2531

**Comment by lorddusk** [comment]
We are planning a complete rewrite very soon.
