### ISSUE TITLE
Parties not working

### ISSUE THREAD

**Issue by TechnicLab** [lorddusk/HQM#372]
Hello!
Looks like parties system is completely broken: invited player is not seeing any invites and game crashes sometimes on creation of party.
[crash-2017-11-24_19.42.26-client.txt](https://github.com/lorddusk/HQM/files/1502455/crash-2017-11-24_19.42.26-client.txt)

**Comment by canitzp** [comment]
The crash is fixed in the upcominf 5.3.5 release of HQM for 1.12.2.
I can't test the invite problems for now, so I keep the issue open

**Comment by canitzp** [comment]
Parties are working in 5.4.0 (eta feb next year)
