### ISSUE TITLE
[1.12.2] - Cannot search for most items when changing quest icons/item requirements

### ISSUE THREAD

**Issue by Spearkiller** [lorddusk/HQM#374]
There seems to be a bug where you cannot search for most items when changing icons for quests, and items required for quest tasks. The only items that show up are 5 blocks/items from the mod Roots, and all the crated items from Forestry.

Items in the inventory can still be used to set icons/requirements, so it's not entirely unusable, but pretty inconvenient, in my opinion.

Proof: https://cdn.discordapp.com/attachments/300941293213712385/387878513455267842/2017-12-06_21.06.10.png

Using the latest (and only) version for 1.12.2

**Comment by canitzp** [comment]
It's a bit late for an answer now, but can you pls provide the image with another source? Alos this seems to be a modpack specific bug, cause when I test it, it works just fine
