### ISSUE TITLE
[1.12.2] Setting "required amount of parents" gets reset to "all" 

### ISSUE THREAD

**Issue by MainFreak** [lorddusk/HQM#376]
After restarting the game a quest I have set to only require 2 out of 3 possible parents gets reset to require all of them. Since two of those quests are connected as options it is impossible to complete all 3 quests and unlocking the next one without fixing this manually every time restart my game with Edit Mode, not at all if I was playing "legit" and not just editing things atm. 

Forge Version: 14.23.1.2562
HQM Version: HQM New Heights 1.12.x-5.2.0Alpha1

**Comment by noobanidus** [comment]
Does this still happen?

**Comment by noobanidus** [comment]
Yes, this is still an issue. It appears as though the parent requirement is only being written is useModifiedParentRequirement=true. That value is set to true if you manually update the requirements with the tool, but it's not saved to the quest file (as it shouldn't be, there's no need for it). However, when the parentRequirement is read in, the new auto-save doesn't save it to the file and effectively discards it.

Wow, that took a long time for someone to come along and actually look at it :( I'll push a fix shortly.
