### ISSUE TITLE
Crashing When using the Questbook

### ISSUE THREAD

**Issue by DrSquishie** [lorddusk/HQM#378]
Using Awakening pack on Twitch but happens with other packs. Upon using the quest book it will crash when opening tabs, closing, going back etc. Java and video drivers up to date. Have 8gb of ram, also tried reinstalling packs. 
https://pastebin.com/HjXbB3ik
Here are the logs but doesn't way much game ends without proper shutdown instant crash.

**Comment by canitzp** [comment]
i can't see any evidence that it has todo with HQM. If you think it is, then pls provide a valid crash report
