### ISSUE TITLE
no items, internal server crash on esc, crash from quests under open button, and more.

### ISSUE THREAD

**Issue by Fenekhu** [lorddusk/HQM#383]
I can't remember why but somehow I accidentally deleted HQM out of my mods folder. I immediately reinstalled the same version. when I went back into my world, I had some quests that just happened to be under the "open" button for a set. There's an annoying bug where if you click open and a quest is under it, it will open that quest. I hit escape and minecraft went unresponsive and I had to force close it (it wasn't going to come back.) I went back into the world and did the same thing and accidentally opened the quest underneath the open button again. When i hit the back button to go to the quests, it said shutting down internal server and went back to the server list. I finally clicked on part of the button that didn't have a quest under it. it went to the quests just like it normally does. when I went to change an item on the quests though, no items appear. neither the items in my inventory or items in the search thing. I basically cannot do anything. I know some of the issues are tagged with "no fix until rewrite" and I was wondering if the rewrite has happened yet. I'm currently using HQM-Beyond-1.12.x-5.2.0Alpha1. Also, A quick suggestion: it would be nice to have a way to customize the textures of the questbook itself without modifying the mod file (which curse doesn't allow). The error message for the unresponsive crash and the internal server crash are the same (i think) and here are [all of the lines after it](https://pastebin.com/dZuqfTxE)

the error is something about "the string is too long for this kind of encoding"

[esc crash error](https://pastebin.com/RxQM3Dsg)
![image](https://user-images.githubusercontent.com/7574714/40580784-1a781d3a-610c-11e8-821c-e0bbbd75df5b.png)

*EDIT* after testing it a little more I can't seem to figure out what makes it go unresponsive and what causes the internal server crash. I did the exact same thing I explained up there to get the pictures and log data and the effects were switched around. I tried them both again and then they both took me back to the main menu and then the next time it caused it to go unresponsive.

**Comment by canitzp** [comment]
I'm sorry to tell you that this can't be fixed before the rewrite is done

**Comment by canitzp** [comment]
I have blind fixed a bug in version 5.3.0, where a erroro message like your's is coming too. Maybe it is fixed with 5.3.0. Please test it and if not then reopen the issue

**Comment by canitzp** [comment]
You can use a texture pack to edit the hqm questbook textures ;D
