### ISSUE TITLE
Live count bug

### ISSUE THREAD

**Issue by Nightshaid** [lorddusk/HQM#388]
My world just got deleted while I still had 7 lives left. I am just a lotta bit pissed since I was working on that world for 3 days.

**Comment by canitzp** [comment]
I can't help with enough details, like versions of mc forge and hqm, your modpack and the quests. Also log files would be nice

**Comment by canitzp** [comment]
?

**Comment by canitzp** [comment]
Since I looked up the world deletion code, to find out that it doesn't work at all since the 1.8 ports, you're on an outdated version
