### ISSUE TITLE
HQM causing massive lag spikes D:

### ISSUE THREAD

**Issue by UltaVulta** [lorddusk/HQM#389]
Okay so when I made these in a singleplayer world they all worked just fine but when I came onto a server it gave me huge server time out-ing lag spike. The exact same problem as this: https://github.com/lorddusk/HQM/issues/318, however, this issue was never solved. This is 1.12.2

**Comment by UltaVulta** [comment]
I’m sorry for the poor detail. This takes place with loot bags with custom loot tables. I believe the lag is caused by limiting the amount of items given but each bag opened. I however, am not sure

**Comment by canitzp** [comment]
Like you said duplicate of #318
