### ISSUE TITLE
Reset progres on Party creating

### ISSUE THREAD

**Issue by astetyn** [lorddusk/HQM#393]
Hello,

Every time when someone on my server creates a Party, his game crashed and quests will be deleted. I have to repair it through data file and remove Teams file. When will be this Bug repair? Or is there some posibility to disallow Parties? Thanks.

**Comment by canitzp** [comment]
Please provide a crash-report from the person creating the party and maybe also a server log. Which versions are you using?

**Comment by canitzp** [comment]
?

**Comment by astetyn** [comment]
I was using the latest version and no error has been on server or client.When I checked the data file of the world, the nickname had party with some number next to it, but that party didnt exist on the server side.

**Comment by canitzp** [comment]
I just fixed an issue with a similar description and a proper crash report. #407 
If the next version (5.3.5) doesn't fix it, then please reopen this issue or create a new one
