### ISSUE TITLE
HQM quest limit inflection point

### ISSUE THREAD

**Issue by Llorx** [lorddusk/HQM#394]
Hi,

I would like to know what's the commit that allowed HQM to increase its quest limit, so I can try to create my own 1.7.10 build with those fixes.

Thank you!

**Comment by way2muchnoise** [comment]
Pretty sure it was because I rewrote the whole save/load handling.

**Comment by Llorx** [comment]
@way2muchnoise fine, found the commit. Can you confirm that [this commit](https://github.com/lorddusk/HQM/commit/4ed3c378a924cb51820b43879354aa6e9161a6a7) is the one that you are pointing out? Also, can you do a bit of back memory and tell me if you think that 1.7.10 can support it or it uses "modern" Minecraft thinghies?

PD: I'm checking it and it was a brutal work. Great job :-)

**Comment by way2muchnoise** [comment]
It indeed is that commit, and 1.7.10 should be capable of handling it. I just went from the binary format to a json format. Which needed a lot of new code.

**Comment by Llorx** [comment]
One question more. I'm almost done, but I'm stuck with one thing as I'm not used to Java so I'm a bit lost with changes between 1.7 and 1.8.

You have some lines in `hardcorequesting\io\adapter\QuestTaskAdapter.java` with

    GENERIC(QuestDataTask::construct),
    DEATH(QuestDataTaskDeath::construct),
    ITEMS(QuestDataTaskItems::construct),
    LOCATION(QuestDataTaskLocation::construct),
    MOB(QuestDataTaskMob::construct),
    REPUTATION_KILL(QuestDataTaskReputationKill::construct);

But they return this error:

    error: method references are not supported in -source 1.7

I don't want to remove the -source 1.7 thingy, so I would like to know if there's a way to convert those lines. I've already converted all lambdas and other method references you had, but I'm stuck with these.

**Comment by Llorx** [comment]
Just compiled it. I've noticed that the questbook is empty ¿Are the quests created with the old method lost? ¿Do quests needs to be created again?

**Comment by way2muchnoise** [comment]
If I recall correctly you need to use some addon to be able to export quests to json in an old world. And import that with the new version.

**Comment by Llorx** [comment]
Perfect!

**Comment by jahtim** [comment]
If you can make a merge request or just put your code in your branch ? @Llorx

**Comment by jahtim** [comment]
Umm, I found BlayzerQ's Backport from 1.9.4 into 1.7.10, I gonna try it.

[https://github.com/BlayzerQ/HQM/commit/dc6737f6d48928c86913a2a40333d8260df31180](url)
