### ISSUE TITLE
QDS crash

### ISSUE THREAD

**Issue by MrAsare** [lorddusk/HQM#396]
Ive tried using a hopper and an itemduct to submit items into the QDS.
[crash-2018-08-21_15.56.49-server.txt](https://github.com/lorddusk/HQM/files/2308198/crash-2018-08-21_15.56.49-server.txt)
There is the crash report for the hopper.
This makes it so that i cant enter the world anymore until i remove the hopper through NBT editor as i get the same crash every time. I had the hopper on top of the qds and when i put an item in the hopper my game instantly crashes and corrupts my save file, am i doing something wrong?? thanks

**Comment by canitzp** [comment]
It would be cool if you provide the quest and the item you tried to pump into. I have fixed this specific issue, but i want to test it more

**Comment by MrAsare** [comment]
The quest required item conduits from ender io to be submitted and consumed, 100 required.  Just tried on a vanilla mc chest also and i got this error which required 1 chest to be submitted.  [crash-2018-08-22_09.23.14-server.txt](https://github.com/lorddusk/HQM/files/2309304/crash-2018-08-22_09.23.14-server.txt)
 Also I cant seem to submit anything into the qds for any qds/consume task when I try liquids. .

**Comment by canitzp** [comment]
Ok. I tested it a lot and also reimplemented the liquid parts of the qds. After some more test I upload 5.3.3 as beta to curseforge. Any other suggestions for me?

**Comment by MrAsare** [comment]
Yes just a quick thing, does right clicking on a QDS by hand unbind the quest from it becauuse i can set a quest with the book and when i right click with my hand after it says that i havent bound a quest to it even though the texture shows the mushroom and it said i had binded it. Thanks

**Comment by canitzp** [comment]
The QDS has a lot of bugs. I notice you described behavior a lot, but i have no idea why it's happening

**Comment by MrAsare** [comment]
Last thing i noticed a couple of days ago. When i set a limit for quest group retrieval and then exit out of the book and go back the book the group retrieval limit is set back to zero. Was this a thing to stop the lag that happened after you put the limit?? thanks a lot for the help

**Comment by canitzp** [comment]
Ok I now tested it much more, but I still can't figure out why the hell the QDS needs a double bind to be bind correctly. I now only indicate it better, so that if the bound is lost, also the texture changes back to th non bound version.
@MrAsare are you around? I want to give you a version to test the given bugs

**Comment by MrAsare** [comment]
I am now i was travelling all day, sorry.

**Comment by canitzp** [comment]
@MrAsare here it is: http://puu.sh/BiS8H/ff2ecfc3b8.jar

**Comment by MrAsare** [comment]
Alright ill fiddle around with it and see if i find anything.

**Comment by canitzp** [comment]
have you found out something?

**Comment by MrAsare** [comment]
To bind a quest to the qds you need to right click twice. If you right click once the texture changes but right clicking by fist will say its not binded until you try again.

**Comment by canitzp** [comment]
I know, I told you this, but I can't fix it

**Comment by MrAsare** [comment]
I cant seem to submit liquids but items are submitting perfectly with no crashes.

**Comment by MrAsare** [comment]
Change task button doesn't seem to work either, i just end up deleting and making a new one.

**Comment by MrAsare** [comment]
Game just crashed when submitting a chest on a consume task. It worked before on its own but when i had a consume task requiring water, liquid tritium and chests, submitting the chest gave this 
[crash-2018-08-24_11.06.58-server.txt](https://github.com/lorddusk/HQM/files/2317922/crash-2018-08-24_11.06.58-server.txt)
Console gave this idk if this adds anything "[11:07:17] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded."
Also what ive found is that when i pick items to submit they work fine but the second i try submit a vanilla chest my game will crash and the world will corrupt.

**Comment by canitzp** [comment]
Ok, thank you for the investigation. I don't know when I have time for fixing this bug again, but when it happend then I give you a new test version

**Comment by Orimbo30FPS** [comment]
I have a problem with the quests:
I go into singleplayer, I open the book of quests, I go out by pressing Esc
The result comes out of the game with an error: A fatal error has occurred, this connection is terminated
Information about the crush here: https://gist.github.com/Orimbo30FPS/1d67a6795f1e5acfdaf489827cb4c696
