### ISSUE TITLE
Crash while loading world

### ISSUE THREAD

**Issue by dancc7t** [lorddusk/HQM#397]
Hello, one player of my pack has reported me having a crash while loading world, i asked him for the log and i saw hqm was causing it, once he removed hqm from the mods folder he could load the world again. I myself did not have this kind of problem, but i am afraid other players might have the same problem so i created this issue to know what might be the cause of this

Here is the [debug.log](https://drive.google.com/open?id=1V7_3odnY3kkiaE2OccAJ0UECgSfagptX)

**Versions**

HQM-1.12.2-5.3.2
Forge Mod Loader version 14.23.4.2756 for Minecraft 1.12.2

Thanks.

**Comment by canitzp** [comment]
I see a lot of these: ```[13:29:24] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181] 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181] 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?] 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] Caused by: java.lang.NullPointerException 	at mrriegel.stackable.tile.TilePile.getAllPileBlocks(TilePile.java:308) ~[TilePile.class:?] 	at mrriegel.stackable.tile.TilePile.change(TilePile.java:163) ~[TilePile.class:?] 	at mrriegel.stackable.tile.TilePile.func_145839_a(TilePile.java:214) ~[TilePile.class:?] 	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:331) ~[avj.class:?] 	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:760) ~[brz.class:?] 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?] 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?] 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181] 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181] 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?] 	... 9 more``` and that tells me that it isn't a HQM issue

**Comment by 4rz0** [comment]
I started the pack without Stackable and with HQM enabled.
Now the error mentioned above changed to the following:
https://www.hastebin.com/hihegapahe.rb

**Comment by canitzp** [comment]
@4rz0 The stacktrace you post is only the half truth, for the other half I need a complete crash report (recommendation) or log file.
@danikk14g You cross reference a issue with Stackable. I never said that is has something todo with it. The log snippet I copied from your log file references StorageNetwork as issue source

**Comment by dancc7t** [comment]
yes, i was wrong about that, but the problem is that i cannot reproduce the issue neither on my local instance or the version i downloaded from the pack, which makes it difficult to me to find the source of the problem.
