### ISSUE TITLE
Cannot Delete Location Task

### ISSUE THREAD

**Issue by josephflan** [lorddusk/HQM#40]
Every time I go to create a new location task a location is created called 'New' as usual with the coordinates 0,0,0. I try to change the location and instead a new location is created under the coordinates I tried to change it to. I cannot delete the pre-existing location with the delete tool.

Below is an example. I may be missing something but I am new to this mod.

I am running version 4.2.4 on 1.7.10
If this is not a bug, I apologize for wasting your time.
![image](https://cloud.githubusercontent.com/assets/10384473/10732155/a7c8cdfa-7bf0-11e5-9a30-9dffe1512d52.png)

**Comment by hilburn** [comment]
This is not a bug - it's a dummy entry that you can edit to add a new location task.

When you view the book as a user rather than an editor you won't see it
