### ISSUE TITLE
WHERE DOES HQM SAVES THE QUESTS AND MODIFICATIONS???HELP!!!

### ISSUE THREAD

**Issue by lord900** [lorddusk/HQM#409]
I'm on a single player game and I cannot get the hqm to save anything. I enter the world do all the quests, and click save all. I save and exit.

One I get back in the game, I open the HQM book....and all my work is gone. WHY?????? Where did it save it to? do I have to drag any files into the config folder?

ps. I am on Twitch Curse launcher, created my own custom profile.

**Comment by canitzp** [comment]
The quests are normally saved inside the config folder. There is a condif folder for "hqm" and inside it there is a "default" folder which contains all the current quests.
I don't know if Twitch Launcher is doing something wrong there, but if you're in editing mode and do everything correctly and click "save all" iside the quest book, then everything should be saved.

Sorry for the late reply
