### ISSUE TITLE
Quest Limit?

### ISSUE THREAD

**Issue by icyevilfantasy** [lorddusk/HQM#42]
I'm not sure, but i've not found any further information about this.

I'm creating a HQM-ModPack at the moment and i've 935 Quests ready so far. At this point i can't create more quests - is this a hard-limit or maybe a bug?

Is there any chance to increase this limit? - i need in sum about 1,5k for my mod-pack to be complete ;)

**Comment by Mario-Beck** [comment]
I'd like to know that as well.

**Comment by icyevilfantasy** [comment]
I've loaded an older revision of my quests.hqm with 929 Quests. 

I can reproduce this now ... i create 6 more quests so that i reach the 935 Quests and at this point i can't create more quests - even if i delete this 6 new ones.

There must be an internal counter or something else that prevents me from creating new quests.

**Comment by way2muchnoise** [comment]
@icyevilfantasy Could you upload the json extract for the quests somewhere? (if it is a bit delicate since it is unreleased we could figure out other ways, but that might involve dropping by on IRC) Cause I don't have the time to make 935 quests :p

**Comment by icyevilfantasy** [comment]
Of course i could give you me json-export for these quests but i think there is an easier wy to debug without any dependencies.

I've created a set named "Pool" and created 1 empty quest in there. Then export it to json ... edit this with an editor you like and copy+pasty a bunch (about 1023) quests in there.

After that you can remove this Quest-Set named "Pool" und reload it from the json file. You should quickly get to the limit of creating quests.

--------------

btw: i'm testing at the moment to create more than 1023 quests with these trick but after saving 1030 quests & reloading the whole game - a lot of my quests will be removed so that it's dropping from 1037 quests to about 127.

**Comment by icyevilfantasy** [comment]
give me some minutes ... i'll prepare the Pool.json for you ;)

**Comment by icyevilfantasy** [comment]
Following steps to reproduce:
- Create a `Pool.json` in your hqm config directory with the following content: http://pastebin.com/raw.php?i=BjD6H5sX
- Make sure you have an empty quest book (by deleting "quests.hqm" and the backup file)
- Make sure you starting in HQM edit-mode 
- Create a new world (in creative for editing the questbook)
- import the Pool.json with `/hqm load Pool`
- activate quest mode with `/hqm quest`
- open your quest book 
- go to the Pool Quest Set (you should have exactly 1021 quests in there)
- try to create a new quests
- you should be able to create 2 more quests and than it stops
- even if you are removing quest - you are unable to create new ones

**Comment by icyevilfantasy** [comment]
Further more:
- Rename the Quest Set "Pool" into "Pools"
- import the Pool.json with `/hqm load Pool` a second time
- now you should have about 2042 quests
- quit the game
- start the game 
- enter your world
- activate quest mode with `/hqm quest`
- open your quest book 
- the quests are dropped from about 2042 quests to about 1020 quests

**Comment by icyevilfantasy** [comment]
I'm not a Java-Pro but i think the bottleneck is:
- https://github.com/lorddusk/HQM/blob/master/src/main/java/hardcorequesting/network/DataBitHelper.java#L23
- https://github.com/lorddusk/HQM/blob/master/src/main/java/hardcorequesting/network/DataBitHelper.java#L118

I hope this will help a bit ...

**Comment by icyevilfantasy** [comment]
Any news/feedback on this issue? - maybe en ETA? ;)

**Comment by lorddusk** [comment]
Never ask for an ETA.

On Fri, Nov 6, 2015 at 4:31 PM, Tobias Sülzenbrück <notifications@github.com

**Comment by icyevilfantasy** [comment]
Sorry for that - i don't want to push anyone.

A simple feedback like "this won't be fixed" (maybe for technical reasons) or "this will be fixed - stay tuned" will be enough for now ;)

**Comment by lorddusk** [comment]
It might, it's already been upped once before as you can see in the code.
So upping it again might cause more problems than it solves.

On Fri, Nov 6, 2015 at 4:53 PM, Tobias Sülzenbrück <notifications@github.com
