### ISSUE TITLE
[Request] Location task for Y axis only.

### ISSUE THREAD

**Issue by SupremeMarshal** [lorddusk/HQM#420]
I want to have a quest with a task that ask to go to down to -1000Y for example (ignore the X and Z). It can be set for detecting the player X and ignore Y and Z as well, ect. If this is possible, it will be a great addition for my server that is to dig to the Earth's core. This can also be a great addition for a server with sky islands and having a quest that ask to go to the sky.

**Comment by noobanidus** [comment]
I'm not yet sure if I'm going to merge my biome/biome type tasks into the general location task, but I don't see any problem with setting additional flag for the location task which limits it to only being the Y value. Of all of the values, the Y value is the most recently.

To be honest, the location task itself is only really useful for quest sets that are taking place in a custom map.

**Comment by noobanidus** [comment]
I've merged this into #421.
