### ISSUE TITLE
Review all network messaging to ensure UTF conversion is split into chunks

### ISSUE THREAD

**Issue by noobanidus** [lorddusk/HQM#423]
This should happen for anything that has the potential to be long, specifically loot bags being sent via the QuestLine data.

The methods for splitting the data should get abstracted out and it should be done as seamlessly as possible.

**Comment by canitzp** [comment]
i rewrite the network traffic to use nbt while normal game flow. For Quest sync from server to client, I would probably use Base64 encoded jsons, so that they length is smaller than regular json

**Comment by noobanidus** [comment]
I thin kit's currently just using a straight string version of JSON for the QUest sync.

**Comment by canitzp** [comment]
Yeah currently implementation is a bit shitty, cause a too long string overflows the network capability. So we could send it as NBT or encoded to have a shorter string

**Comment by noobanidus** [comment]
In the meantime I'll just use the same approach I did to fixing the bug with the quest sizes that we have months ago... although I might clean up some of the code as there's a fair amount of re-use. Honestly, I think that must've been one of my first ACTUAL contributions to anything Minecraft mod-related.
