### ISSUE TITLE
Quests no syncing with 1.12.2 server (already tried #249 #368 #330 #319)

### ISSUE THREAD

**Issue by Heyo13579** [lorddusk/HQM#426]
im trying to create a server with hqm for 1.12.2 but no matter what i try whether it be changing configs making sure both files are exactly the same reloading the configs forcing a hqm config sync none of them have worked it still shows 0 quests the only thing that has loaded properly is the cover image

**Comment by noobanidus** [comment]
This is potentially an issue that I started experiencing just before Christmas but haven't had the time to fully look into yet. I'll try to get around to it tomorrow if I can finish beta testing something else.

**Comment by canitzp** [comment]
The test server version should work fine, but this isn't released yet

**Comment by Heyo13579** [comment]
any idea on when it will be release?
id like to launch my server within the month but cant till this issue is resolved

**Comment by canitzp** [comment]
When all major bugs are fixed and the field test has ended, so 1 or 2 Months

**Comment by Heyo13579** [comment]
does it work on any of the previous versions? can i revert to an old one to solve the issue?
i cant wait that long to launch the server

**Comment by canitzp** [comment]
The bug exist a long time, so probably 1.7 has a working version, sorry

**Comment by Heyo13579** [comment]
so was was looking into the mods code and it looks like you have the server and client proxies set up as Boolean and then have the other classes calling to it (correct me if i'm wrong i'm still somewhat new to java) wouldn't it be more stable to set all server side actions to one package/class (example below not great but gets my point across) i understand that it wouldn't be as compact but it be much easier to identify and resolve issues that occur.


`package com.mod.proxy;

import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public abstract interface IProxy
{
  public abstract void preInit(FMLPreInitializationEvent paramFMLPreInitializationEvent);
  
  public abstract void init(FMLInitializationEvent paramFMLInitializationEvent);
  
  public abstract void postInit(FMLPostInitializationEvent paramFMLPostInitializationEvent);
}

---------------------------------------------------------------------------------------------------------

package com.mod.proxy;

import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ServerProxy
  implements IProxy
{
  public void preInit(FMLPreInitializationEvent event) {}
  
  public void init(FMLInitializationEvent event) {}
  
  public void postInit(FMLPostInitializationEvent event) {}
}
`

**Comment by noobanidus** [comment]
This will be fixed in the rewrite/next release.
