### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by excelcrafter** [lorddusk/HQM#44]
minecraft - 1.7.10
forge - 1492
java - latest

crash log: http://pastebin.com/DqauUgex

**Comment by lorddusk** [comment]
what are you doing that it makes it crash? Give me some info....

**Comment by excelcrafter** [comment]
I tried that mod on server to make some quests, I was not able to. I didnt have any icons on the left side of the book. I decided to do quests in singleplayer then upload it. When I tried to make new quest, Minecraft crashed all the time.

**Comment by lorddusk** [comment]
First, Quest editing in MP is not available at this point ( if ever ). Second, it shouldn't do this. Give me the step-by-step run down please.

**Comment by excelcrafter** [comment]
Just a question. HQM will never work on server, right?

**Comment by lorddusk** [comment]
not for the foreseen future no.

**Comment by excelcrafter** [comment]
Thank you, I will remove it from pack, no use for it when it doesnt work on server.

**Comment by lorddusk** [comment]
If you are running a server with HQM quests, the server DOES need it though.
You cant make quests on SMP ( which I thought you were referring to )

**Comment by excelcrafter** [comment]
Yes, I was trying to make quests in singleplayer, but if its not working on server, no point to have it in modpack.

**Comment by lorddusk** [comment]
You need to make quests on singleplayer. you can play quests on multiplayer.
