### ISSUE TITLE
Change task behaviour difficult to understand

### ISSUE THREAD

**Issue by Funwayguy** [lorddusk/HQM#447]
Using the "Change Task" tool while editing a quest does not appear to make much of a visual indication that anything has changed (even the old task type name is retained). It is also not immediately clear that it is restricted to item based tasks. This restriction also makes it nigh impossible to replace a non-item task in the middle of a task listing without requiring users to delete all subsequent tasks and start over if they needed to.

I'd prefer to see this tool not only be more clear in its function but also remove the unnecessary restrictions. Losing the items stored on that task would be less of a problem then having to remake all the other tasks to preserve the ordering.

**Comment by noobanidus** [comment]
My current intent is to disable this for the duct_tape release as it serves no purpose other than confusing people. Technically it could be used to completely delete the task in that index and replace it with a new task based on the list, but I'm not sure how feasible that is. I'll look into it.
