### ISSUE TITLE
Break Block task doesn't work on many block types

### ISSUE THREAD

**Issue by Funwayguy** [lorddusk/HQM#449]
First noticed when block break tasks failed to detect any rail broken that wasn't in its default orientation (relevant if you want players to collection rails from mineshafts). This extends to many other kinds of blocks that have state dependent functionality and/or no 1-to-1 item block representation. Known affected blocks so far:

- Rails (all kinds) (only default state works)
- Doors (all kinds) (neither half works in single or double door setups)
- Redstone Dust (any orientation or power state)
- Off Redstone Torch
- Redstone repeaters
- Redstone comparators
- Lit Redstone Lamps (unlit works)
- Connected Tripwire Hooks (unconnected works)
- Placed String
- Inverted Trapdoors
- Inverted Slabs (all kinds)
- Inverted Stairs (all kinds)
- Lit Furnace (unlit works)
- Sideways Logs (all kinds) (upright works)
- Sideways Pillar Quartz (upright works)
- Sideways Bone Blocks (upright works)
- Sideways Hay Bale (upright works)
- Double Tallgrass (only the bottom works)
- Large Fern (only the bottom works)
- Sun Flower (only the bottom works)
- Snow Piles (only works if 1 layer deep)
- Sign Posts (all variants)
- Beds (all variants) (neither top or bottom half works)
- Skulls (all orientations and variants)
- Banners (all orientations and variants)
- Flower Pots (empty and filled)
- Brewing Stands (empty and filled)
- Cauldron (empty and filled)
- Vines (any orientation
- Placed Leaves (all variants) (only natural, non-decaying leaves work. Once logs are removed detection fails)
- QDS with task set

Note: I suspect the place block task may run into similar issues.

**Comment by noobanidus** [comment]
Progress so far: ![](https://i.imgur.com/HkyYzed.png)

Problem items:
- ~~Redstone and string (or anything that can be placed; Quark glowstone?)~~
- ~~Slabs in the upper slot~~
- ~~Lit furnaces~~
- ~~Redstone devices~~
- Everything else that I didn't test

**Comment by noobanidus** [comment]
All of the above work for block place tasks. I'll test the rest now.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/7dG1gka.png)

Due to an issue with data corruption/server sync mode, coloured beds are not currently working properly. Following need to be dealt with for PLACE tasks only:

- Colored beds
- Banners

I have not begun testing any of these with break events.

As far as I know, everything above affects block place events as well, but I will be re-testing them.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/OCRniPn.png)

Okay, signs, leaves and now flowerpots are stumping me again. I'll work on it more later.

**Comment by noobanidus** [comment]
Personal complaint (as this is what I): Faint Amaranth from Astral Sorcery.

**Comment by noobanidus** [comment]
So I just rewrote the whole thing as I'm done. The only actual override I had to make was for the flower pot. This is a much more reliable implementation, I feel like, although there will certainly be other mods which require custom mappings/functions to work properly...
