### ISSUE TITLE
Config Crash

### ISSUE THREAD

**Issue by GhostVamp** [lorddusk/HQM#45]
So, using the same modpack, with editmode=true game doesnt crash.
The second i change the editmode=false the game gives me this
http://pastebin.com/03fv3vcN
Any idea?

**Comment by lorddusk** [comment]
ssp or smp?

**Comment by GhostVamp** [comment]
ssp

**Comment by lorddusk** [comment]
walk me through it step by step as detailed as possible

**Comment by GhostVamp** [comment]
Start instance on HQM 4.3.2 - Everything goes as planned.
Change editmode=true to editmode=false
Open the same instance - Game gives that crash.

**Comment by GhostVamp** [comment]
I also get this when trying to create a world with editmode=false
http://pastebin.com/4KTkeTG8

**Comment by lorddusk** [comment]
update to 4.3.3

**Comment by GhostVamp** [comment]
Where could i find that? Curse only has 4.3.2.

**Comment by lorddusk** [comment]
ah you are running  431 not 432 according to the log... (i mixed up the versions in my head)

**Comment by GhostVamp** [comment]
I tried both versions. None of them works.

**Comment by lorddusk** [comment]
432 should fix the second log you posted?

**Comment by GhostVamp** [comment]
432 fixes it, but i think i found what's causing the problem.
I'm updating HQM from 423 to 432 and even if no question has problems, HQM cant read them on quest mode, only edit mode.

**Comment by GhostVamp** [comment]
Right. I have no idea what happened, but doing a fresh config install and then manually adding the quest.hqm file worked.
I'm totally lost on what happened.
