### ISSUE TITLE
Quest set titles using reserved filenames silently fails to save

### ISSUE THREAD

**Issue by Funwayguy** [lorddusk/HQM#450]
As the title suggests, using one of the Windows reserved filenames as a quest set title causes the entire set to silently fail to save and subsequently go missing entirely once the user reloads their world. This also has a destructive side effect of stopping any attempt to load subsequent sets, even if they're file safe and previously working, resulting even more collateral damage.

This also affects the export command which reports it saved when in actuality it has not.

**Comment by noobanidus** [comment]
> CON
PRN
AUX
NUL
COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM0
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT0

**Comment by noobanidus** [comment]
> < (less than)
> (greater than)
: (colon)
“ (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
\* (asterisk)
