### ISSUE TITLE
Using file unsafe symbols in quest set titles corrupts them and others

### ISSUE THREAD

**Issue by Funwayguy** [lorddusk/HQM#451]
Similar to the issue with reserved filenames, using any file unsafe symbol within a quest set title will cause the quest set to silently fail to save and go missing on reload. Collateral damage to subsequent quest sets is also still a massive problem.

As an added side effect to the lack of name sanitation, a user can use slashes within the name to manipulate the folder in which the set is actually exported to.

**Comment by duely** [comment]
While an issue, it's one that's been around for a while. Caveat emptor, basically, seeing as it's usually just pack makers doing these things. We should probably look out for it, but not necessarily do anything before rewrite.

**Comment by noobanidus** [comment]
I misunderstood what was involved.
