### ISSUE TITLE
HQM terminates server connection when book is closed or quest is chosen

### ISSUE THREAD

**Issue by jerjerje** [lorddusk/HQM#465]
I was trying to set up a server, but everytime I choose a quest or close the questbook I get thrown of the server with the message "A fatal error has occured, the connection is terminated". I have the ServerSnyc confic option enabled and am using the version HQM-1.12.x-5.3.5 (the newest version I could find). 
This is the error message I found in the server console:
[Error Message.txt](https://github.com/lorddusk/HQM/files/2817573/Error.Message.txt)

Because of the line "The string is too long for this encoding." it reminds me of #398

**Comment by noobanidus** [comment]
Yeah, this issue has been fixed and will be in the next release of HQM, hopefully sometime this month.
