### ISSUE TITLE
Empty items in bags causes soft lock on world load

### ISSUE THREAD

**Issue by Funwayguy** [lorddusk/HQM#467]
If a user sets one of the items in a bag group to be empty, HQM can save this as null in `bags.json`. Next time that world is attempted to load, `hardcorequesting.io.adapter.BagAdapter` gets stuck and soft locks the game. Manually opening the file and erasing all the NULL entries by hand is the only way to allow the world to load again.

![image](https://user-images.githubusercontent.com/6048596/52338142-4c2b3e80-2a55-11e9-9770-069f049cfaf3.png)

![image](https://user-images.githubusercontent.com/6048596/52338179-68c77680-2a55-11e9-8ae7-0f14ede6c2db.png)

EDIT: Assuming that users are able to migrate quests from older versions of Minecraft, handling `NULL` conversions to `ItemStack.EMPTY` will likely be necessary

**Comment by noobanidus** [comment]
Argh why

**Comment by way2muchnoise** [comment]
The life of `null` and `ItemStack.EMPTY`, long live legacy :D

**Comment by noobanidus** [comment]
I'm going to try to put some work into HQM over the weekend, was taking a bit of a break from it all. This should be relatively easy to resolve. Alternately we could just drop support for loot bags and make modpack makers use an addon with a better interface? 👯‍♂️

**Comment by noobanidus** [comment]
How did this happen? It's never supposed to be null...
