### ISSUE TITLE
Failed to load remote questing state from description.txt

### ISSUE THREAD

**Issue by astetyn** [lorddusk/HQM#485]
Hello,

I have made some quests in single player mode. I copied these quest sets to the server side config/hqm/default. I wiped my client side config and enable only server sync. When I join server, no quests or description are shown. This **Failed to load remote questing state from description.txt** I found in client side log. Where could be a problem?

- server sync enabled on both sides
- edit mode disabled
- questing mode enabled on both sides

When joined to the server, only _data, deaths, state and teams_ are synced to the client  _remote_ folder
Using version: HQM-1.12-5.4.0

**Comment by noobanidus** [comment]
First thing I would do would be to move the quests from `config/hqm/default` to `world/hqm`, as that's where the server is looking for them. The `default` and `remote` folders are purely client-side, IIRC. `default` is where quests are copied to when editing them, `remote` is where quests are synced to from the server. 

The server itself **should** be looking in `world/hqm/` for the files *to* sync to the client.

**Comment by astetyn** [comment]
Yes, the mod itself copied the the files from _default_ folder to the _world/hqm_. The quests are there now, but still not syncing with client side.

**Comment by noobanidus** [comment]
Are files being copied into the `remote` folder on the client?

**Comment by astetyn** [comment]
Only these. _Data, Deaths, State and Teams_ http://prntscr.com/mvgk8v

**Comment by noobanidus** [comment]
That is extremely strange. Is there anything in the error log to indicate that server sync isn't working when enabled?

**Comment by astetyn** [comment]
In client side log I found: `[13:01:14] [main/ERROR] [Hardcore Questing Mode]: Failed to load remote questing state from description.txt`
And in server log, everytime when someone joins, I found: `Hardcore Questing Mode: Requires version @VERSION@ but mod is not found on client.`
and on START server: `Hardcore Questing Mode]: Couldn't copy default files` (but there are already in worlds folder)

**Comment by astetyn** [comment]
I am an idiot. I didnt notice the config file in the config folder where I could set the server sync. Its working now. 
Sorry, my bad. Thanks for your time.

**Comment by noobanidus** [comment]
That's okay, that should've been made much clearer. Glad it was such a simple solution!
