### ISSUE TITLE
Mod not reading config file after recent update

### ISSUE THREAD

**Issue by Heyo13579** [lorddusk/HQM#486]
after the most recent update, the worlds for my modpack are no longer starting in hardcore mode even though its setup in the config options you have to turn it on manually im also unable to turn on edit mode for quests either. the quests are still there but im not able top alter anything about the actual config file and have it be reflected in game

**Comment by noobanidus** [comment]
It's possible I didn't make clear enough in CurseForge, but [there is a new config file now](https://old.reddit.com/r/feedthebeast/comments/atf7rd/new_release_hardcore_questing_mode_540/)  and you will have to copy over your old variables to that. Please check out the linked reddit post for more information.
