### ISSUE TITLE
Can't delete quest rewards

### ISSUE THREAD

**Issue by rockobonaparte** [lorddusk/HQM#487]
I was surprised today to find I couldn't delete quest rewards. I found out from an older quest, but delete didn't work for newer ones either. Procedure:
1. Create quest
2. Select to change item
3. Select the first quest rewards slot
4. Assign some item (I had used 8 clay)
5. Select Delete
6. Click on the quest reward. Nothing happens.

I'm doing changes locally; this is not on a server.

This is the first time in months that I think I've tried to do this, so I couldn't say how long this has been a thing.

Minecraft Version: 1.12.2
HQM Version: 1.12-5.4.0
Forge Version: 14.23.5.2820

**Comment by kirderf1** [comment]
This does not seem to be an issue in the latest 1.16 version of the mod.
