### ISSUE TITLE
[Feature Request] NEI integration

### ISSUE THREAD

**Issue by HenryLoenwind** [lorddusk/HQM#49]
Just support for R and U when hovering over an item would really be helpful. You almost always have to look up how to craft a required item, and closing the quest book (why doesn't the inventory key do that, btw?), opening your inventory, right-clicking into the search box and typing the name of the item (that you hopefully remembered correctly) is getting annoying very fast.

**Comment by Lohardt** [comment]
2nd, that would be awesome to have.

**Comment by lorddusk** [comment]
The GUI isn't supported by NEI, so making NEI work with HQM is quite the
task, it's still on my list, just not very high.

**Comment by HenryLoenwind** [comment]
Close the GUI, open another one with just a slot and itemstack, move the mouse over the slot and re-fire the keyboard event? Auto-close the mini-GUI when NEI returns control to it (and maybe even re-open the book).

Just a random idea.

**Comment by way2muchnoise** [comment]
@HenryLoenwind that would be one of the worst ways to implement it. If you have no clue how things work don't try to say clever stuff.

**Comment by hilburn** [comment]
I should have time tonight - I think I can probably get this working

**Comment by way2muchnoise** [comment]
@hilburn k then I won't spend time on it

**Comment by mrdeadlocked** [comment]
This would be fantastic!

**Comment by hilburn** [comment]
Update - think I have it, just need to do some more testing tomorrow

**Comment by hilburn** [comment]
Ok so, there are kind of 2 routes to solve this - one is much more invasive but allows NEI to re-open the quest book when you're done recipe surfing (honestly not sure that this won't break things, will need a fair amount of testing). Option B is far easier to implement, but means when you close the recipe gui you need to reopen the book.

Thoughts?

**Comment by lorddusk** [comment]
I think B is enough really. People need to close the book to look for a
recipe now, you took out the middle step.

**Comment by canilsen** [comment]
Option B seems fine yeah

**Comment by Lohardt** [comment]
Option B is super.

**Comment by HenryLoenwind** [comment]
no need to reopen the book in my eyes. I'm not sure I'd make it do it even if it was easy.

**Comment by lorddusk** [comment]
Will be in the 4.4 release tomorrow.
