### ISSUE TITLE
NullPointerExeption error while trying to break a specific block

### ISSUE THREAD

**Issue by noamsm** [lorddusk/HQM#491]
## Description:
I was trying to break an Ender IO conduit on my modded survival world. The conduit did not break and the game showed an error (See below).
I looked through the report and discovered that the NullPointerExeption was caused by HQM trying to trigger an OnBlockBreak event.

## Crash report:
https://paste.dimdev.org/tahogijede.mccrash

If you need more info please contact me!

**Comment by noobanidus** [comment]
I'm pretty sure I know what this is, I'll try to resolve it and put out a hotfix build presently.

**Comment by noobanidus** [comment]
Is there any chance you could try out this build for me? I don't have an environment set up with EnderIO in it to test it out myself, unfortunately: [HQM-1.12-5.4.0.jar.zip](https://github.com/lorddusk/HQM/files/3111939/HQM-1.12-5.4.0.jar.zip)

**Comment by noamsm** [comment]
Yes, that fixed it! thx

**Comment by noamsm** [comment]
Hello, I just wanted to know when are you going to post a fix for this?

**Comment by noobanidus** [comment]
It was at this moment I realised I had yet to upload the fix to CurseForge. My bad!

**Comment by noamsm** [comment]
Okey thanks for your help! 
btw, when you uploaded the mod you accidentally checked 1.11.2 instead of 1.12.2 in the supported versions area...

**Comment by noobanidus** [comment]
Thanks for the heads up, I fixed the version!
