### ISSUE TITLE
Like double click, when open set (v. 4.4.4 for minecraft 1.7.10)

### ISSUE THREAD

**Issue by KostyaKapitonov** [lorddusk/HQM#492]
v. 4.4.4 for minecraft 1.7.10
When you select any Set, and then press open button in the right-bottom corner, sometimes it may happen the bug. The problem is when the quest icon is under the open button - in this case it not just open the  set, but also open the quest ander the button. But it shouldn't.
Example:
1) https://pp.userapi.com/c845122/v845122830/2008f0/3J_wxGa6lR8.jpg
2) https://pp.userapi.com/c845122/v845122830/2008e6/DeX18jmivss.jpg
In this case the "Aluminium ingot" quest is under the open button, and it automatically opens when i press open button.

**Comment by noobanidus** [comment]
Unfortunately, 1.7.10 is no longer supported. This is fixed in the most recent version for 1.12.2.
