### ISSUE TITLE
Quest Book search function not working

### ISSUE THREAD

**Issue by Twixxler** [lorddusk/HQM#498]
I am trying to make quests and instead of grabbing the items and then having the in my inventory i try to search for them only to find that that function is broken. I am running on minecraft version 1.12.2

![image](https://user-images.githubusercontent.com/4095905/62825619-9c09d000-bb74-11e9-8ab4-33dfa0ef4385.png)

I have also used the latest build and and previous builds for this version and same things occurs

From playing on different modpacks the base screen in the search funtion is the base items vanilla minecraft has but that has changed to this.

![image](https://user-images.githubusercontent.com/4095905/62825647-f145e180-bb74-11e9-9609-5b2d8d94be35.png)

**Comment by Twixxler** [comment]
I can not see any base content from vanilla minecraft only from select few mods not sure if that would be a conflict between my mods causing this issue or if there is an issue with HQM not being compatible or something

**Comment by Twixxler** [comment]
So i figured out what the issue was. I removed 2 mods Roots & The Bewtweenlands, 1 of these 2 mods caused some type of issue that resulted in the above pictures/issues to occur.

**Comment by noobanidus** [comment]
That is extremely strange! There must be an item in those that's causing an error. Are you able to upload the `latest.log` from when the search wasn't working?
