### ISSUE TITLE
Quests not showing up on server

### ISSUE THREAD

**Issue by noamsm** [lorddusk/HQM#499]
# Issue Description
I made a server pack for my modpack and I realized that the quest book is empty.
The HQM folder on the server contains all the folders the client has, and the config option "ServerSync" is set to true on both the server and the client.
I also found out that the server doesn't generate the config folder automatically.

I realize that this might look like a duplicate of #249 , but because that post is so old by now I think it might be a different problem thus it deserves its own issue.

# Versions
Minecraft: 1.12.2
Forge: 14.23.5.2847
HQM: 1.12-5.4.0-hotfix1

# Files
[server.log](https://github.com/lorddusk/HQM/files/3774893/server.log)
[client.log](https://github.com/lorddusk/HQM/files/3774894/client.log)
[server config folder.zip](https://github.com/lorddusk/HQM/files/3774896/server.config.folder.zip)

**Comment by noobanidus** [comment]
Have you tried placing the HQM folder in the world folder as well? It's been a while since I worked on this and I don't quite remember how things go together, but it's possible the config isn't being copied out into the world folder.

**Comment by noamsm** [comment]
> 
> 
> Have you tried placing the HQM folder in the world folder as well? It's been a while since I worked on this and I don't quite remember how things go together, but it's possible the config isn't being copied out into the world folder.

The hqm folder is already in the world folder. I guess it copied them automaticly...

**Comment by PickleballKing** [comment]
I also had this problem but I have found a solution. If you go to the actual config file for HQM, not the folder, On line 58 there is an option to have the server sync with the client. This is false by default. Setting this to true should fix your problem.

**Comment by hoklai1997** [comment]
I'm also experiencing this issue
HQM 5.4.0
Forge 14.23.5.2847
Minecraft 1.12.2
I have the modpack on curseforge, although I was not able to upload the server file I created to use
https://www.curseforge.com/minecraft/modpacks/coven-undone

I've tried loading the server with the same HQM config that I use on the client side and nothing appeared (I did not check if the world file's HQM file was generated)

I've tried manually placing a 'hqm' folder in the world folder and then put all the contents of the client sides 'hqm/default' folder into it (so the server's world folder looks like 'world/hqm/{quest and reward jsons}'

I've tried manually placing a 'hqm/default' folder in the world folder and then put all the contents of the client sides 'hqm/default' folder into it (so the server's world folder looks like 'world/hqm/default/{quest and reward jsons}'

None of these have worked, if there are any other tests I can do, or info I can give, please let me know!

BTW, I really have loved HQM and am glad its being continued into the newer versions of minecraft!

**Comment by hoklai1997** [comment]
Update, the quest complete sound is still playing (at correct points, namely when I've done something that would've completed a quest) despite the quest book being empty, so it seems like it is keeping track of the right things, just the book is empty for whatever reason.

**Comment by kirderf1** [comment]
HQM for mc 1.12 is no longer being developed, so this issue is unlikely to be fixed for that version.
