### ISSUE TITLE
Errors appear when Mob Killing or Taming Quests are added

### ISSUE THREAD

**Issue by Flainity** [lorddusk/HQM#503]
We apparently faced this when we started to setup our quests. We don't know the exact reason for it, but for some reason, when mob quests are added and I try to fulfill them, the game throws an error + mobs don't drop anything besides exp.

https://paste.dimdev.org/lilefijube.mccrash
https://paste.dimdev.org/aqahozosuz.mccrash

Does anyone have an idea?

**Comment by canitzp** [comment]
It is a bug on our side. THank you for reporting

**Comment by kirderf1** [comment]
Can't find the issue on the latest version, and it appears that the links no longer work. The issue _might've_ been fixed since then. Is  this the case?
