### ISSUE TITLE
Quest book rollbacking and getting stuck

### ISSUE THREAD

**Issue by leevanf** [lorddusk/HQM#507]
Hello everyone!

So, a couple days ago, me and my friend decided to get back to a pretty old modpack we never finished (Agrarian Skies 1), playing on Twitch Launcher.

I booted the server up, and everything seemed normal. But the quest book did a rollback, and almost half of the quests I already had done were incomplete. So, I used the /hqm edit to auto complete them... and it didn't work. What was happening was:

- The OP book couldn't complete any quest, neither could I claim any reward;
- The normal book wouldn't detect anything, manual or via Quest Delivery system;
- I was the leader of the party, and tried to reset book for all the party + kick the other players + quitting from the party. In my screen and book, none of those ever happened, but for my friend on the server, all of the actions happened. His book was erased, he was kicked from the party and could create another one as usual. When checking the party list, the old party did not exist anymore, yet for me I was still there. I couldn't accept his invite and enter his new party.

The only thing that worked was erasing the players.dat from HardcoreQuesting folder, completely erasing all our progress in everything. We were a little bit annoyed by that, but whatever, we just wanted to play. I erased it, the hqm was disabled, booted the server, re-enabled questing mode and it was back to normal. Quests completing and party working.

But, the problem has striked again. My book rolled back to the exact same state that it was the first time it glitched (keep in mind that we did A LOT of new quests before the glitch happened again today), and I can't fix it without erasing the players.dat.

The only unusual thing I did today was going into the Nether, which is something I didn't do from the day it first glitched until now. Since I can't find a way to read the players.dat as text, I came here in hopes of some light.

Thanks,
Leevanf

**Comment by canitzp** [comment]
Well the modpack is for Minecraft 1.6.4 and so we won't do any updates to fix things. In a newer version of hqm the complete saving system was rewritten and this would have probably fixed your issue as well, but the modpack is just to old for us to make a update

**Comment by mainrs** [comment]
@canitzp I couldn't find the source code for the 1.6.4 version in this repository. At least there is no GitHub tag available. Does the source code still exist?

**Comment by canitzp** [comment]
@mainrs The oldest code is 1.7.10. The older versions weren't open source
