### ISSUE TITLE
Can I transfer this MOD to Chinese Website www.mcbbs.net ?

### ISSUE THREAD

**Issue by CuteLittleSky** [lorddusk/HQM#508]
Hi,Can I transfer this MOD to Chinese Website www.mcbbs.net ? I'll link here.
And this is Chinese Language(zh_cn.json):

[zh_cn.txt](https://github.com/lorddusk/HQM/files/5073518/zh_cn.txt)

**Comment by canitzp** [comment]
Please don't.
