### ISSUE TITLE
1.16.3 server crash

### ISSUE THREAD

**Issue by BedrockLegends** [lorddusk/HQM#512]
Not sure if the mod is client side or server as there is no where to find out, but heres a server crash
[crash-2020-10-09_15.08.19-fml.txt](https://github.com/lorddusk/HQM/files/5357284/crash-2020-10-09_15.08.19-fml.txt)

**Comment by canitzp** [comment]
Thie is indeed a server side crash related to HQM

**Comment by shedaniel** [comment]
Should be fixed in 5.5.1, please reopen the issue if it remains unfixed.
