### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by benbenlaw** [lorddusk/HQM#514]
[crash-2020-10-10_17.37.32-fml.txt](https://github.com/lorddusk/HQM/files/5359431/crash-2020-10-10_17.37.32-fml.txt)

**Comment by lorddusk** [comment]
This... Is not a bug report.
Please give more information.

**Comment by benbenlaw** [comment]
game will not start says there a problem with hqm

**Comment by benbenlaw** [comment]
turn out after quests saved the game doesnt load?

**Comment by benbenlaw** [comment]
in config/hqm/default/set removeing quest line from there makes the game load again

**Comment by shedaniel** [comment]
Can you send the json of the quest line?

**Comment by shedaniel** [comment]
Should be fixed in 5.5.1, please reopen the issue if it remains unfixed.

**Comment by benbenlaw** [comment]
can confirm is now working thanks for the update
