### ISSUE TITLE
quests keep changing

### ISSUE THREAD

**Issue by benbenlaw** [lorddusk/HQM#515]
when closing and reopening the game quest settings change settings from "requires all" to "requires specific amout"

**Comment by benbenlaw** [comment]
its not me then haha

**Comment by shedaniel** [comment]
Can you provide more information on where the settings is?

**Comment by benbenlaw** [comment]
yeah so if im on edit mode, the menu on the left click on required parents and all quests show as "requires specified amount" after a restart of the client. instead of "requires all"

**Comment by benbenlaw** [comment]
basically mean all quests are visable and can be done in any order which is not the intention i want. as i say it works fine unitl a restart to the client

**Comment by benbenlaw** [comment]
when set to requires all it works as intended but as i said after a client restart all quests go back to requiores specified amount

**Comment by shedaniel** [comment]
Thanks for reporting, I have tracked down the issue.

**Comment by benbenlaw** [comment]
thanks for fixing the bug means i can publish my quest pack now thanks
