### ISSUE TITLE
[Question] Backport to 1.15.2?

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [lorddusk/HQM#517]
Hello. This is more a question than an issue. Since this mod is reviving for 1.16.2/.3 (5.5.x): is there any chance for HQM 5.5.x being backported to 1.15.2? (at least Forge version since Fabric one was released in HQM: Fabric CurseForge page?)
I understand if you will not port it to 1.15.2 and close this issue, but it would be great to see this port, because there is no good questing solutions for 1.15.2 and some mods are still on it and doesn't want to port to 1.16.

**Comment by kirderf1** [comment]
At this point in time, I highly doubt that this is gonna happen at all
