### ISSUE TITLE
[crash]Game crashes with the latest fabric api

### ISSUE THREAD

**Issue by MarinaMarissa** [lorddusk/HQM#518]
[crash-2020-10-23_21.32.30-client.zip](https://github.com/lorddusk/HQM/files/5429765/crash-2020-10-23_21.32.30-client.zip)

**Comment by canitzp** [comment]
You are missing the cloth api mod. This is a mandatory dependency for the Fabric version of HQM

**Comment by MarinaMarissa** [comment]
> You are missing the cloth api mod. This is a mandatory dependency for the Fabric version of HQM

It works nice now. Thanks a lot.
