### ISSUE TITLE
HQM loading mods error.

### ISSUE THREAD

**Issue by bblewitt** [lorddusk/HQM#521]
**Minecraft version:** 1.16.3
**HQM version:** 5.5.3 - Forge

**Issue:**
Updated forge to the latest (1.16.3 - 34.1.35) and get a screen that shows 

Error loading mods 1 error has occurred during loading
Hardcore Questing Mode (hardcorequesting) has failed to load correctly
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge

**Forge versions that testing has been done on**
34.1.28 -> 34.1.35 - Issue
34.1.27 - complete crash of the game will not load anything (possible unrelated)
34.1.25 - Working

**Reports**
https://paste.ee/p/l8EfA - 34.1.35
https://paste.ee/p/KRMgo - 34.1.28

**Comment by Unhook** [comment]
Any idea on when you'll be able to look into this? It's what's preventing me from moving to newer forge versions.

**Comment by shedaniel** [comment]
Sorry for the delay, I have fixed this issue in 5.5.4
