### ISSUE TITLE
[1.16.3] 'Save all' menu doesn't fit on screen

### ISSUE THREAD

**Issue by Unhook** [lorddusk/HQM#522]
Part of the 'save all' menu isn't visible. See the screenshot below
![image](https://user-images.githubusercontent.com/58952619/97791820-c7903480-1bd6-11eb-97bc-5e0023174acf.png)

**Comment by canitzp** [comment]
Which HQM vereion and screen size do you use?

**Comment by Unhook** [comment]
Version 5.5.3 (latest)
24 inch monitor, aspect ratio is 16:9

**Comment by canitzp** [comment]
Please tell us the exaxt resolution minecraft uses. You can dind this when opening the f3 menu.
Also which gui scale setting are you using

**Comment by Unhook** [comment]
![image](https://user-images.githubusercontent.com/58952619/97807182-a45d9780-1c5f-11eb-88a1-9503cd0302c3.png)

My GUI scale is set to auto/4. I've tested and it only seems to be an issue when you have GUI scale set to auto/4.

**Comment by shedaniel** [comment]
We could shift the screen to the left a bit, but Minecraft guis lack horizontal space so that's a bit annoying

**Comment by kirderf1** [comment]
Taking inspiration from vanilla, when a screen with a recipe book (such as the furnace screen) is too small, the recipe book menu will render over the actual screen instead of to the left of it. If we change the save menu to initially be closed, we could do something similar to that.
