### ISSUE TITLE
Can not register to a locked registry using [HQM-1.16.2+5.5.3-forge]

### ISSUE THREAD

**Issue by Dacarian** [lorddusk/HQM#523]
Wanted to install HQM to add some custom quest lines to my 1.16.3 sever, but since adding it I'm not even able to launch the game? :s Anyone know how to fix this issue? I tried using all the 1.16.3 version on curseforge and received the same error - I can't update to 1.16.4 as 80% of the mods on my sever don't work with that version 

[crash-2020-11-19_14.39.18-fml.txt](https://github.com/lorddusk/HQM/files/5567441/crash-2020-11-19_14.39.18-fml.txt)

**Comment by shedaniel** [comment]
Update to the latest version of HQM on CurseForge, it is going to work from 1.16.2 and above
