### ISSUE TITLE
[Enhancement] Add ability to easily move questlines

### ISSUE THREAD

**Issue by Unhook** [lorddusk/HQM#524]
It would be nice to easily be able to move questlines (e.g. by clicking on an arrow like in Better Questing). With moving questlines I mean e.g. switching out questline 1 with questline 3 in the image below.

![image](https://user-images.githubusercontent.com/58952619/99909006-2c2a4500-2ce6-11eb-8f67-3969ff97b6d8.png)

**Comment by kirderf1** [comment]
Related to this issue is #489, which targets the same problem, but has a different suggested solution.

**Comment by canitzp** [comment]
Even tho this issue is different to #489 I'll close it because it is a duplicate
