### ISSUE TITLE
HQM [1.12.2] disconnecting clients on server after a while

### ISSUE THREAD

**Issue by Desynq** [lorddusk/HQM#525]
After playing on the server for a while, some players would get disconnected after interacting with the quest book whatsoever.

teams.json appears to cause the crash after a while; wiping its data fixes it
[teams.txt](https://github.com/lorddusk/HQM/files/5599138/teams.txt)
Disconnect message in server console
[message.txt](https://github.com/lorddusk/HQM/files/5599139/message.txt)

**Comment by canitzp** [comment]
Sorry but 1.12 is not supported anymore. We can barely give support for 1.16 and so there aren't any time resources to dig through 1.12 too
