### ISSUE TITLE
Cannot move quest from Singleplayer to Server

### ISSUE THREAD

**Issue by KantilDoombringer** [lorddusk/HQM#534]
I have tried every solution listed that I could find and none of it works. The server loads fine, but the client side game crashes upon opening the quest book.

May I please ask for detailed instructions on how to move the quests from singleplayer to a server in 1.16.4?

**Comment by shedaniel** [comment]
You will want to share the crash log

**Comment by KantilDoombringer** [comment]
[crash-2021-02-01_01.54.46-client.txt](https://github.com/lorddusk/HQM/files/5902527/crash-2021-02-01_01.54.46-client.txt)

**Comment by kirderf1** [comment]
The crash had to do with task logic meant to be done server-side being performed client-side, which should be fixed with #564.
