### ISSUE TITLE
Blank Quest Book

### ISSUE THREAD

**Issue by Malephus** [lorddusk/HQM#541]
I am hosting a 1.16.5 mod pack utilizing HQM on my desktop and opening the game to my husband via LAN. His quest book is currently showing as the attached image. We've destroyed the book, spawned one creatively, recreated it with the recipe and made sure the server_sync on both our instances showed as true. Is there anything else I may be missing?
![blank quest book_1 1 1](https://user-images.githubusercontent.com/78990912/107837953-54ab6380-6d58-11eb-93c0-fb26068b5361.jpg)

thanks,
Mal

**Comment by afolk2** [comment]
I'm currently having this exact issue. A quick and dirty solution just worked for me. If I exit the LAN game and start a single player, open the quest book, and then log back into the LAN world it updates.

**Comment by kirderf1** [comment]
It appears that server_sync is only applied for dedicated servers, meaning that no such syncronization happens for LAN-worlds. I'm guessing that's your problem.
