### ISSUE TITLE
Repeatable quest broken

### ISSUE THREAD

**Issue by Warbringer12** [lorddusk/HQM#544]
forge: 1.16.5
HQM Version: 1.16.2+5.5.6

1. Have a repeatable quest in quest book
2. Complete repeatable quest
3. Wait for time to go down to 0 to reset quest
4. Quest Don't Reset

**Comment by Winddbourne** [comment]
I'm experiencing this too.  This vital quest in my pack is on negative days until reset now. 

![2021-03-26_01 40 44](https://user-images.githubusercontent.com/24589533/112587751-8b06e480-8dd4-11eb-808f-b7c288a83dcd.png)

**Comment by canitzp** [comment]
Fixed by 7b001be

**Comment by MSandro** [comment]
When will the new version with the fix be released? I hope very soon.

**Comment by lorddusk** [comment]
When it's ready, be patient.
