### ISSUE TITLE
Random Crashes When Using Quest Book

### ISSUE THREAD

**Issue by RedgeLive** [lorddusk/HQM#545]
Forge : v1.12.2 Reccomended
HQM : v5.4.0 Hotfix1

I am experiencing random crashes while using the Quest Book on a server. There is no specific event that triggers a crash. Simply leaving the book open and doing nothing may result in a crash. Following is the logs of one instance of a crash:

![image](https://user-images.githubusercontent.com/82788927/115172303-f9b52600-a092-11eb-876b-6e33e416de54.png)

I can provide a full mod list, or any other information if it could help. Thank you!

**Comment by canitzp** [comment]
Sorry but 1.12 is not supported anymore. We can barely give support for 1.16 and so there aren't any time resources to dig through 1.12 too
