### ISSUE TITLE
Cant Create Party

### ISSUE THREAD

**Issue by cjscott15** [lorddusk/HQM#549]
Im playing Per Fabrica Ad Astra and i have the quest book but it doesnt give me an option to create a party.
![Capture](https://user-images.githubusercontent.com/41179083/122943261-7935ce80-d33c-11eb-8d02-e0df99f3e839.PNG)

**Comment by kirderf1** [comment]
Unable to replicate the problem when running just HQM. Which mod version does this issue appear on?

**Comment by canitzp** [comment]
Per Fabrica Ad Astra is a pretty old pack and doesn't seem to be supported by the author anymore. Also it is a 1.7.10 modpack, so we can't support you at all.
