### ISSUE TITLE
[Fabric] how to execute commands as server? Player has no permission.

### ISSUE THREAD

**Issue by MSandro** [lorddusk/HQM#560]
Hello.
How can I execute a command as server? Because if I start a new world with "Allow Cheats"=false, the player has no permission to execute a quest command which should unlock his inventory.
![image](https://user-images.githubusercontent.com/10937159/129338514-90e32d68-251a-40d5-8eb1-d28dda493ebd.png)
and why is the command output visible in the Chat? Can I disable this?
And is there an config option for executiong commands as server?

**Comment by canitzp** [comment]
So for your second question, you probably see the executed commands because it is enabled in the server.properties and you're operator

**Comment by kirderf1** [comment]
This is not logging info for server operators, but rather the direct feedback to command executors, so the problem is entirely in how command rewards are resolved.
