### ISSUE TITLE
A Crash with Consume Quest

### ISSUE THREAD

**Issue by CCCClear** [lorddusk/HQM#578]
A crash will occur when selecting a target item while editing a consume quest.
The fabric 5.5.6 version I used before does not have this problem. When I update it to 5.5.9 version, this problem will occur, and the crash report shows: "Empty Fluid Volume's must have an amount of 0!”

**Comment by kirderf1** [comment]
A crashlog could help speed up the process if you can bring one here.

**Comment by kirderf1** [comment]
Got to it myself now, a crashlog is no longer needed.
