### ISSUE TITLE
1.12.2 needs a update really bad making party crashes HQM and game

### ISSUE THREAD

**Issue by thediggyman** [lorddusk/HQM#581]
Maker of "Path of the druid" modpack and youtuber. Just want to give you a heads up, when a party is made and friends join party HQM. game crashes after working on next quest. So everyone has to complete their own quest and not make a party or lose game. No funises

**Comment by thediggyman** [comment]
on Technic launcher or Curse.... Technic has server download D&D based modpack so it makes it hard for friends to join the party and have fun

**Comment by kirderf1** [comment]
While HQM has started getting bugfixes again, that only goes for the latest minecraft versions (currently 1.16 and soon 1.17). It is unlikely to be fixed for 1.12 as that is simply too old of a version.
Though if anything, you could provide a crashlog for me to check if the crash might be avoided without an update, or if it is still present and fixable in the modern version.

**Comment by canitzp** [comment]
@thediggyman Like kirderf1 said, please provide a log and crash-report.
It is important to know if this is still present in the current release versions and maybe a 1.12.2 hotfix isn't impossible after all.
