### ISSUE TITLE
[Fabric 1.17.1] crash when connecting 2 quests

### ISSUE THREAD

**Issue by MSandro** [lorddusk/HQM#582]
I've tried the new Beta of HQM for MC 1.17.1 but it is useless. It crashes with no crash report (Exit status 0) when connecting 2 quests (set the requred quest)

**Comment by morottao** [comment]
I had the same problem: https://paste.ee/p/4xwAm

**Comment by MSandro** [comment]
Not fixed in HQM-1.17.1-5.6.1-fabric

**Comment by kirderf1** [comment]
Did not show up in testing for me. @MSandro Can you provide a crashlog/stacktrace/log?

**Comment by Chuunkyz** [comment]
i got this too. i tried a lot of times and my game don't crash now, but i can't see the links at all between the quests.

**Comment by Chuunkyz** [comment]
also quests that requires other ones to be completed don't work at all, you can still click them and see them.

**Comment by kirderf1** [comment]
Oh, looks like 5.6.1 was unintentionally built without the changes from #583. A new version should be up in not too long.

**Comment by kirderf1** [comment]
5.6.2 should have the changes meant to fix this.

**Comment by MSandro** [comment]
Yes 5.6.2 seems to work fine at the first look
