### ISSUE TITLE
1.16.5 Fabric Blocks Disappear Bug

### ISSUE THREAD

**Issue by CCCClear** [lorddusk/HQM#590]
1.16.5 Fabric, in 5.5.11, the first craft table or enchantment table (there may be other blocks as well) will disappear when it is placed. I don't know if this is caused by mod conflict, but this problem won't happen again after I replaced the old version. 
Since there is no crash, I can't provide crash report. 
If you have any clue, you can try to solve it. This problem will only occur after version 5.5.6, and there may be no way to solve it.
 I just reported it because I found it.

**Comment by kirderf1** [comment]
Sounds similar to an issue I came across while porting to 1.17 (fixed with 6044d15400c602bbaad949f88bdcb9bee24a09bd). It might be fixed if we backport that.

**Comment by kirderf1** [comment]
This should be fixed with 5.5.12. Can you confirm?

**Comment by CCCClear** [comment]
It doesn't seem to be fixed.
Sorry for not replying.

**Comment by kirderf1** [comment]
Hmm, can confirm that it's still an issue in the release. It is however fixed in dev. Might be a mistake during version building, similarly to what happened with 5.6.1.

**Comment by kirderf1** [comment]
After some delay, 5.5.13 is now up with the fix. I tested the release outside of dev, so it should not be missing the fix this time.

**Comment by CCCClear** [comment]
I tested it as soon as you posted it and it did fix the problem, thank you.
