### ISSUE TITLE
Error in Creative tab

### ISSUE THREAD

**Issue by Tsyklop** [lorddusk/HQM#60]
I opened HQM tab in creative mode. And there are no items. 
![2015-11-09_12 18 23](https://cloud.githubusercontent.com/assets/6783568/11031281/094fba0c-86dc-11e5-83d5-78654806b011.png)

**Comment by lorddusk** [comment]
Which version?

**Comment by Tsyklop** [comment]
oo. sorry, HQM-The Journey-4.4.0.

**Comment by lorddusk** [comment]
Hmm, Will take a look, fix probably later tonight then.

**Comment by way2muchnoise** [comment]
I don't have the issue in my dev env
![](http://puu.sh/lfxFN/493a64baaf.png)

**Comment by suprememiners** [comment]
This bug could be caused by another mod or texture pack not showing the items or icons.
Are the items there @Tsyklop but just invisable or are they just not there?

**Comment by Tsyklop** [comment]
@suprememiners just invisable

**Comment by lorddusk** [comment]
Disable your resource pack and check again please.

**Comment by Tsyklop** [comment]
@lorddusk Before updating mod everything was normal.

**Comment by lorddusk** [comment]
That's not what I asked ;). Please check without resource pack, and if that works, give me a link to the resource pack.

**Comment by Tsyklop** [comment]
@lorddusk defscape x64 + faitful32 modded

**Comment by lorddusk** [comment]
So without resource pack it's normal?

**Comment by Tsyklop** [comment]
@lorddusk I check still

**Comment by Tsyklop** [comment]
i turn off my resoursepack and problem still exists

**Comment by lorddusk** [comment]
Any errors in your console log about it?

**Comment by Tsyklop** [comment]
@lorddusk nope.
