### ISSUE TITLE
How to trans local quests to server quests?

### ISSUE THREAD

**Issue by twilightsg** [lorddusk/HQM#608]
I make all quests on my local computer but now I found I can't move the quests from my computer to server by simpley copy ans paste the root of config/hqm all files
So how can I move all quests to my server?

**Comment by kirderf1** [comment]
You'd start by transferring the quest data from `config/hqm` to the corresponding folder on the server. After that, you need to enable `SERVER_SYNC` in the hqm config on the server, and you should be fine.

**Comment by twilightsg** [comment]
> You'd start by transferring the quest data from `config/hqm` to the corresponding folder on the server. After that, you need to enable `SERVER_SYNC` in the hqm config on the server, and you should be fine.

Thank you a lot, this perfectly sovled my issue.
