### ISSUE TITLE
BUG: Possible Memory Leak/Lag issue with Quest Book 1.17.1

### ISSUE THREAD

**Issue by ididthat** [lorddusk/HQM#610]
It may be a conflict with one of the performance mods I have installed, but if I have the quest book in my hotbar or hand, the FPS drops about 20%. I thought that was the only thing so I wasn't too worried, but after trying to debug it, I noticed the pie chart in the f3 menu had hand consistently going up in usage any time the quest book was in hand. It's not incredibly fast, but compared to the fact that I hold other items and it rapidly goes down, it seems worrying.

Initially I thought it might just be the texture had a transparency issue or something with my shaders (i dont really know how most of this works) so I made a resource pack to change it to a book and quill, the lag still is there. I can try to provide screenshots or videos of it happening but I haven't seen anyone mention it so I'm posting this here.

Edit: funnily enough, the resourcepack to change its texture seems to make it worse

**Comment by kirderf1** [comment]
That seems rather important. Are there any comparable items which it does or does not happen to? (Such as the op quest book and other HQM items) How consistent is it? If it's sufficiently consistent, can you figure out the smallest combination of mods eith which the issue is present?

**Comment by ididthat** [comment]
So I feel a bit silly not disabling everything first and trying just the performance mods, but I found the issue. I disabled the mod [Item Model Fix](https://www.curseforge.com/minecraft/mc-mods/item-model-fix) and it's working perfectly now. I had added that to help with some edges on things like torches, but I guess it creates a conflict with the models here somehow. I had been trying to dig for a possible way to make a hotkey to open the quest book as a temporary fix, but I know nothing about modding to even start that.

As for the items affected, it was any of the books, and hearts. If you added one to each slot of your hotbar, it got worse as more were added. I'm still not sure how changing the texture made it worse, the code for your model seemed similar enough to the stock ones when I copied over the book and quill code to the resource pack. Again though, I have no experience here, just trying to help out

**Comment by kirderf1** [comment]
Alright, in that case I'm guessing that the issue is in Item Model Fix, and that our item models triggered some sort of edge case which caused the issue to happen.

Because of the nature of the mod, I'd suggest that you also open an issue on their repository, as they may have a better understanding of what's happening.
