### ISSUE TITLE
1.12.2 the HQM homepage of does not support Chinese input

### ISSUE THREAD

**Issue by VillagerGold** [lorddusk/HQM#625]
For example, the HQM home page of 1.12.2 does not support Chinese input. Restart the game after Chinese input, and you will see that Chinese has become garbled

**Comment by kirderf1** [comment]
The 1.12.2 version of HQM is not being updated anymore. If the issue is still present in HQM for 1.16.5 or 1.17.1, I can get it fixed for those versions.
