### ISSUE TITLE
How do I fix these 3 problems with hqm in the pack simply magic 2?

### ISSUE THREAD

**Issue by yuri70072** [lorddusk/HQM#629]
I tried playing the "simply magic 2" pack with a friend and the ip had the word "ngrok" written on it, and I had these following issues:
1. My hqm book had no quests, and I couldn't create any parties
2. How do I turn off hqm mode? Or how do I work around the lives limit?
3. My friend's pc crashes when someone opens a loot bag, how do I 
work around this? I didn't try hosting the world yet,the pack's dev didn't answer my message and the hqm dev hasn't logged in around 2 months ago.
How do I solve these issues?  Thanks for the help

**Comment by kirderf1** [comment]
Looked it up, and for reference, the modpack in question seem to be for minecraft 1.10.

1. For older hqm versions, you may need to change some hqm config values to make it work on servers. In particular, there exists an option called "ServerSync".
2. There should be a command that you can use to disable lives. Looks like it might be "/hqm hardcore disable" for your version
3. While the crashlog most likely will give more insight into the crash, there will most likely not be a new hqm version for that minecraft version to fix it. There might be a way to avoid the crash without updating hqm, but that depends very much on the crash in question.

**Comment by yuri70072** [comment]
> Looked it up, and for reference, the modpack in question seem to be for minecraft 1.10.
> 
> 1. For older hqm versions, you may need to change some hqm config values to make it work on servers. In particular, there exists an option called "ServerSync".
> 2. There should be a command that you can use to disable lives. Looks like it might be "/hqm hardcore disable" for your version
> 3. While the crashlog most likely will give more insight into the crash, there will most likely not be a new hqm version for that minecraft version to fix it. There might be a way to avoid the crash without updating hqm, but that depends very much on the crash in question.

Thanks a lot! Was looking for the answer for days

**Comment by yuri70072** [comment]
it still doesn't work,and I googled how to use /hqm load and I tried but it didn't work and I got a text saying I don't have permission even with cheats enabled and I read a text saying that I need edit mode, how do I enable this mode?

**Comment by kirderf1** [comment]
Looks like a number of commands used permission level 3. Could it be that you have  lower permission level assigned to you?
To verify if you set it up right, what's the value for the config options which you believe are relevant?
Edit mode has to do with quest pack editing, which I assume is not what you're trying to do.
