### ISSUE TITLE
4.4.0 null for reputation

### ISSUE THREAD

**Issue by tgstyle** [lorddusk/HQM#63]
Title says it all.

**Comment by lorddusk** [comment]
it really doesn't.

**Comment by Katrix-** [comment]
Happened with me as well. When loading a existing set of quests, where the reputation would go, I just see hqm.rep.null instead.

![2015-11-09_20 37 25](https://cloud.githubusercontent.com/assets/11007080/11044365/bb81ebe2-8721-11e5-887d-eee986fbcd49.png)

**Comment by way2muchnoise** [comment]
What is it supposed to be like?

**Comment by tgstyle** [comment]
Really? No offense but if you guys are supporting the mod you should know how it works =)
![2015-11-09_12 41 51](https://cloud.githubusercontent.com/assets/5832709/11044478/645f7646-86df-11e5-85c0-1dea81644d6b.png)

**Comment by tgstyle** [comment]
This is what it should look like, it should display the reputation that the individual has earned as a reward.

**Comment by way2muchnoise** [comment]
I know how it works but I don't know what your quests/reputations look like.

**Comment by tgstyle** [comment]
4.4.0 for me where it says technically inclined in this screen, says hqm.rep.null as stated by Katrix

**Comment by lorddusk** [comment]
Null for reputation is as descriptive as Butter for peanut butter.

**Comment by hilburn** [comment]
@tgstyle insulting people, even if you put a stupid fucking smiley face at the end and say "no offense", is not a really good way to motivate us to fix things

**Comment by tgstyle** [comment]
Wow take a chill Hilburn.

**Comment by lorddusk** [comment]
He has a point there. Although I don't agree with his choice of words, he has a point...

**Comment by tgstyle** [comment]
It seems it was just a misunderstanding between what way2muchnoise was asking and what I understood.

**Comment by tgstyle** [comment]
Thanks!
