### ISSUE TITLE
Request: Script creation / compatibility

### ISSUE THREAD

**Issue by JTBWatchDog** [lorddusk/HQM#630]
The ability to create scripts that can run upon task completion, i.e in the case of the Origins mod being present, a script that gets the player's Origin/Origin Class and reveals origin/class specific sets depending on player Origin and Class.

**Comment by kirderf1** [comment]
Based on the proposed usage, it sounds more like a request for mod interaction with Origins, than scripting in general. Is there a particular reason that this should be done with scripts?

**Comment by JTBWatchDog** [comment]
The reason why I had the idea it could be done with scripts is because I thought it would be much easier. Rather than doing direct integration with Origins, a script could simply run `/origin get @p origins:origin` & `/origin get @p origins:class`, read the results, and based off of that reveal specific Sets.

**Comment by JTBWatchDog** [comment]
The way I envision this working is through the ability to load .jar files written by quest makers upon certain conditions, i.e completing or starting a quest/task/set. 
I haven't looked through the source code much (I'm not too familiar with MC modding yet, working on it but I'm busy and don't have much time) so I honestly only have a rough idea of how difficult or time-consuming this could be to implement.

**Comment by kirderf1** [comment]
I'm not confident if quest visibility should be handled the way you're suggesting, but I will look into it some more later.
However, I can say that I believe that an addon mod is much more appropriate for these kind of integrations.
For one, it is much easier to support addons in hqm than to support scripts.
Also, a script is restricted to whatever hqm can make available to the script, while an addon can use the api of another mod directly.
