### ISSUE TITLE
[1.18.1 Fabric] Entities and Advancements do not show

### ISSUE THREAD

**Issue by itsdinkd** [lorddusk/HQM#632]
When selecting a modded entity or advancement, it just says "new" still and does not give any information that that is the required entity/advancement needed.

![image](https://user-images.githubusercontent.com/35115304/146657727-c53b32b0-b070-4067-bd1b-f770a7d3d2a1.png)

and when you go to edit the information, it shows what you selected

![image](https://user-images.githubusercontent.com/35115304/146657730-214ed77a-b6f2-4d28-9200-72283ed2416a.png)

**Comment by kirderf1** [comment]
"New" is the default name for those tasks, and you are meant to change the name manually to whatever fits. I'm gonna interpret  this as a feature request for a default name that changes based on the selected mob/advancement.

**Comment by itsdinkd** [comment]
> "New" is the default name for those tasks, and you are meant to change the name manually to whatever fits. I'm gonna interpret this as a feature request for a default name that changes based on the selected mob/advancement.

Oohhhh okay. I didn't know you could use the text tool on that. Interesting approach. Yeah I'd say feature request for sure then.

Also, is there anyway you can add in some text modification allowing Bold or Italic? Maybe through minecraft color codes? 

Either way, thank you for updating to 1.18 love the mod.
