### ISSUE TITLE
[Feature Request 1.18.1] Support Item Tags

### ISSUE THREAD

**Issue by itsdinkd** [lorddusk/HQM#635]
I recommend adding Tag support, ie; #fabric:swords 

This way, you can create 1 quest to where if the player has/crafted any item within that item tag, instead of needing to create multiple quests and then using the option quest link. this would save a lot of time. 

Maybe a simple way to support it is by having a 'advanced' option when you select a item where its a text field and you can enter the item tag(s) there instead of picking out items within the gui

**Comment by canitzp** [comment]
This should replace the OreDictionary Support and is a important change.

**Comment by itsdinkd** [comment]
I was thinking more for fabric but yes forge should have it as well.

**Comment by canitzp** [comment]
In a previous update, OreDictionary support was removed in favor of tags (does also work on fabric), so this issue is resolved.
