### ISSUE TITLE
[1.18.1 Forge] No items appearing in search

### ISSUE THREAD

**Issue by itsdinkd** [lorddusk/HQM#639]
As shown in screenshot, nothing is appearing when searching for items .. Seems to be a forge only bug as this does not happen in 1.18.1 fabric. I've searched numerous items, nothing pops up. even with no search text in the field

![image](https://user-images.githubusercontent.com/35115304/147795514-10f44daf-af80-4128-b3f2-2a3e7c511f54.png)

**Comment by kirderf1** [comment]
Tried it out and while I did find some problems, the search still worked most of the time.
As such, I suspect that I'm not getting the same problem that you're getting, and that there is some sort of error happening during the search, or while constructing the caches.
@itsdinkd Can you look through your logs and see if there's any errors/exceptions/stack traces that might be related to your problem?

**Comment by canitzp** [comment]
Can't confirm in 1.19.4 and since no comment was given this can be closed.
