### ISSUE TITLE
[1.18.1] Crash When Clicking on "Edit Reward Bag" Button

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#645]
Hello! 

I just had a crash while clicking on the button to make or edit reward bags:

https://pastebin.com/gkBXjmrd

MC: 1.18.1
Forge: 39.0.63
HQM: 5.9.1

Thank you!

**Comment by canitzp** [comment]
Oh thank you for the report.
Just after looking at could you try and redownload the .jar file? 
I'll also inform the current maintainer.

**Comment by kirderf1** [comment]
It is possible that the jar file is damaged, so you should try and redownload the jar to see if that solves it.
Just in case, I tried replicating it with the same HQM and forge versions, but didn't get a crash.

**Comment by PrelawAverage** [comment]
I have this same problem, my game crashes when pressing edit text on reward bags

**Comment by kirderf1** [comment]
@PrelawAverage do you have a crashlog to share from your crash?
