### ISSUE TITLE
The Questbook Changes the NBT of the Item

### ISSUE THREAD

**Issue by CCCClear** [lorddusk/HQM#654]
As shown in the picture, after selecting the item, enter the game again, the NBT of the item in the questbook will be changed.
Not only enchant books, but other items that have numbers in their NBT.
Version: HQM - 1.16.5-5.5.16 - fabri
![2022-04-13_23 01 45](https://user-images.githubusercontent.com/44665051/163213333-5f66e829-467d-4f5f-ad9f-595cfaafb4da.png)
![2022-04-13_23 02 28](https://user-images.githubusercontent.com/44665051/163213342-0bb372d6-e0ee-4dc7-adb2-6fff821951b7.png)
c

**Comment by kirderf1** [comment]
Sounds like the same issue as #649. It's part of a larger issue of storing nbt data in json. I do have an idea for a fix that involves changing the save format for items in HQM-data, but I have not yet had time to try and implement it.

**Comment by kirderf1** [comment]
Forgot to mention it. The fix was backported in b9a5443b4261d492755efbc60158761f8f61d64b and is now available in [HQM-1.16.5-5.5.17](https://www.curseforge.com/minecraft/mc-mods/hardcore-questing-mode/files/3753566).
