### ISSUE TITLE
[1.12 forge] config\hqm is empty

### ISSUE THREAD

**Issue by inlanoche** [lorddusk/HQM#658]
I have tried removing all other mods, and having only this one in.  The only thing created in the HQM config folder is a remote folder with a few JSON files.  This now does not allow me to enter edit mode, so I cannot work my mod.   I know that 1.12 is old, but rebuilding my mod that includes a few mods that have not made it past 1.12.
If I can get a copy of these config files, I think I can go from there.

**Comment by canitzp** [comment]
You can enter edit mode anytime with "/hqm edit" on a singleplayer world.
There are no tasks if it is a fresh install
