### ISSUE TITLE
HQM 1.19.2 Forge 43.2.0 Crash

### ISSUE THREAD

**Issue by KarishaDel** [lorddusk/HQM#671]
Ello.
Let me start by saying I LOVE THIS MOD. I have been playing mod packs with this mod in it for years and now I would like to try my hand at making my own quests. I am trying to make my own quest but crashing quite a bit. Mainly whenever I use the search functions or have the game open in the HQM editor. The search function doesn't work at all. I am not sure if I am having mod comparability issues but the crash has the HQM mod. Please help.

![Untitled](https://user-images.githubusercontent.com/70070043/212496583-2c532362-77ca-472d-86cf-9d4f404e449d.jpg)

[crash-2023-01-14_15.53.38-client.txt](https://github.com/lorddusk/HQM/files/10418821/crash-2023-01-14_15.53.38-client.txt)
[crash-2023-01-14_14.51.40-server.txt](https://github.com/lorddusk/HQM/files/10418822/crash-2023-01-14_14.51.40-server.txt)
[crash-2023-01-14_14.39.26-server.txt](https://github.com/lorddusk/HQM/files/10418823/crash-2023-01-14_14.39.26-server.txt)

[latest.log](https://github.com/lorddusk/HQM/files/10418826/latest.log)

**Comment by kirderf1** [comment]
These all all different forms of `NoClassDefFoundError`/`ClassNotFoundException` for classes which really shouldn't be gone, akin to #640 and #645. I've recently noticed the search issue myself, but I'll need more information related to those crashes. Are you getting those crashes consistently? Focusing on one particular crash, can you give some steps that someone else can use to recreate the crash? If you redownload the mod file from curseforge, does that have any influence on the crash?

**Comment by KarishaDel** [comment]
Wow! Thanks for the quick reply!

This is a custom mod pack and yes, I am crashing consistently. I have the mod pack origin so first I have to pick a race in which I pick faerie, then I load into the world. First is that the book doesn't appear in my inventory when creating a new world which I have enabled to do so I cheat it in. Then I can type and add quests. It might be a time thing. Like I just ran it 2 times and I crashed both. The first time is when I was trying to save changes and the second time I was just clicking an item in my inventory to add as a reward. I got 2 different crash reasons. I have no clue.

[Testing Server Pack Mods.zip](https://github.com/lorddusk/HQM/files/10418872/Testing.Server.Pack.Mods.zip)

1.
[crash-2023-01-14_16.44.42-client.txt](https://github.com/lorddusk/HQM/files/10418899/crash-2023-01-14_16.44.42-client.txt)

2.
[crash-2023-01-14_16.49.07-server.txt](https://github.com/lorddusk/HQM/files/10418900/crash-2023-01-14_16.49.07-server.txt)

**Comment by kirderf1** [comment]
Hmm, so the search issue I encountered in dev was also relating to a `NoClassDefFoundError`. However that only happened that one time, and not on subsequent launches. I'll check out the pack you just shared now and see if I can learn anything more.

**Comment by KarishaDel** [comment]
So. I am no longer crashing as long as I dont try to do too much too fast. Thank you for the assistance. I am excited to use this mod!

**Comment by kirderf1** [comment]
After a bunch of testing, I think it might be caused by the text search in the pick item menu. My guess so far is that the threading of that text search *somehow* messes with the class loader in some cases, leaving it in a state to cause a crash in various other parts of the code afterwards. I don't understand the class loading system to tell if that is actually the issue or how it happened in detail, but I think I should move on with #607 and see if that solves it.
