### ISSUE TITLE
Tooltips Show Partly Offscreen

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#675]
Hello!

When working with some items that have a longer tooltip, they will appear offscreen and are unreadable. When attempting to use a line-break in the lang file to fix this, HQM will show a broken character instead:

![image](https://user-images.githubusercontent.com/10309699/218976588-37922123-11e1-490c-8831-54a7975ea073.png)
![image](https://user-images.githubusercontent.com/10309699/218976858-5e4c73ed-c64c-466a-b625-2a5d60f6762c.png)

The line break works normally in the inventory: 
![image](https://user-images.githubusercontent.com/10309699/218976957-3fce84b3-93c5-413c-bf4a-4c1b7fd726f0.png)

Is there a possibility a tooltip wrapper could be added to condense a tooltip and not allow it to go offscreen?

Thanks!
Darkosto

MC: 1.18.2
Forge: 40.2.0
HQM: 5.11.2

**Comment by Mrbysco** [comment]
From testing the call to `gui.renderTooltipL` over in [QuestRewardsGraphics#drawRewardMouseOver](https://github.com/lorddusk/HQM/blob/1.18/common/src/main/java/hardcorequesting/common/client/interfaces/graphic/QuestRewardsGraphic.java#L264) doesn't work correctly. 
Changing the call to `gui.renderComponentTooltip` seems to properly wrap the tooltip.
I could whip up a PR if wanted :)

**Comment by kirderf1** [comment]
Fixed in [HQM-1.18.2-5.11.3-forge](https://www.curseforge.com/minecraft/mc-mods/hardcore-questing-mode/files/4550829).
