### ISSUE TITLE
[1.12.2] NullPointerException on explicit save in edit mode from writeQuestList

### ISSUE THREAD

**Issue by KisaragiEffective** [lorddusk/HQM#677]
**Reproduce step**:
1. download HQM-1.12-5.4.0-hotfix1.jar from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/hardcore-questing-mode)
2. launch it with Forge build 2860
3. type `/hqm edit`
4. type `/hqm op`
5. create set
6. create quest
7. click save button on top right

**Environment**:

* Minecraft: 1.12.2
* HQM: 1.12-5.4.0-hotfix1
* Forge: 1.12.2-forge-14.23.5.2860

**Crash reports**: [crash-2023-03-30_16.19.49-client.txt](https://github.com/lorddusk/HQM/files/11109127/crash-2023-03-30_16.19.49-client.txt) (sorry, not minimized)

**Comment by kirderf1** [comment]
Sorry, but the 1.12.2 version of HQM is not being maintained or updated anymore.

**Comment by KisaragiEffective** [comment]
It's OK, thank you for responding :)

**Comment by KisaragiEffective** [comment]
Sorry, that was my fatal! It seems that I've duplicated set or somehow making collision for quest identifier, which may not supposed to be.
