### ISSUE TITLE
I can't create anything in my server !

### ISSUE THREAD

**Issue by AidenSuzuno** [lorddusk/HQM#678]
![image](https://github.com/lorddusk/HQM/assets/131491397/8f4c8f73-b6ad-4b66-9b2c-7aad11f84289)

Can someone help me please ? I turned the Use-Editor to true instead of false, it's supposed to work...

**Comment by canitzp** [comment]
It is not supported to create quests on a server or a lan world (which is a server as well). This is due to limitation regarding syncing between clients.

**Comment by AidenSuzuno** [comment]
> It is not supported to create quests on a server or a lan world (which is a server as well). This is due to limitation regarding syncing between clients.

Oh...So I can't at all ? That's too bad, it was the only mod available on curseforge...

**Comment by kirderf1** [comment]
Not in a multiplayer setting, no. But it should be usable in singleplayer.
