### ISSUE TITLE
[4.4.0] Some bugs I noticed when updating

### ISSUE THREAD

**Issue by canilsen** [lorddusk/HQM#68]
http://i.imgur.com/1maDlPr.png

Frontpage doesn't register reputation etc properly. Reputation is still stored properly, and quests giving + rep points still seems unaffected. It's just the front page.

**Comment by lorddusk** [comment]
Duplicate of #63

**Comment by canilsen** [comment]
I should probably check closed section too, didn't expect it to be fixed this fast! Sorry for the inconvenience.
