### ISSUE TITLE
HQM LAN NOT WORKING(Tried with essential mod server as well)

### ISSUE THREAD

**Issue by YepMc** [lorddusk/HQM#682]
I really need help with this I tried playing LAN with my family and friends and every time it shows that the HQM book is empty for them, but for me it works, The mod pack is ROUGH CRAFThttps://www.curseforge.com/minecraft/modpacks/theboyswithguns-tbwg
Thats the link to it. I made the modpack, the version is 1.12.2.

**Comment by kirderf1** [comment]
It might be that you need to turn on the "server sync" option in HQM's config if you haven't already.

**Comment by YepMc** [comment]
> 

Ill try that

**Comment by YepMc** [comment]
> 

It didnt work, my friend joined the server and it still says 0 quests

**Comment by kirderf1** [comment]
You could check if there's an error in the log that gives a hint on why it's not working.
Otherwise, you could try sending them a copy of the quest data and see if it can be loaded locally instead of synced over the network.
I can't help much beyond that due to the age of that version of the mod.

**Comment by YepMc** [comment]
> You could check if there's an error in the log that gives a hint on why it's not working. Otherwise, you could try sending them a copy of the quest data and see if it can be loaded locally instead of synced over the network. I can't help much beyond that due to the age of that version of the mod.

What do you mean by copy of the uest data/loaded loacally

**Comment by kirderf1** [comment]
The quests are defined in files in a particular folder in your minecraft folder. The idea would be to send a copy of them manually to your other players, put them in their corresponding folder, and see if that does it.

While it of course would be better if the mod managed to sync them over network on its own, I vaguely recall that you *might* be able to do this way instead in those older versions of HQM.

**Comment by YepMc** [comment]
> The quests are defined in files in a particular folder in your minecraft folder. The idea would be to send a copy of them manually to your other players, put them in their corresponding folder, and see if that does it.
> 
> While it of course would be better if the mod managed to sync them over network on its own, I vaguely recall that you _might_ be able to do this way instead in those older versions of HQM.

Do you remember which folder
<img width="482" alt="Screenshot 2023-08-14 145107" src="https://github.com/lorddusk/HQM/assets/78672020/60f16765-b1e1-46f4-8d14-18fdbb48d155">

**Comment by kirderf1** [comment]
`config/hqm`, and then it looks like it'd be in one of the folders in there. In code (https://github.com/lorddusk/HQM/blob/1.12/src/main/java/hardcorequesting/io/SaveHandler.java) I see references to a "default" folder and a "remote" folder. The remote folder, in particular, insinuates by name that it might be used for quests when connected to a remote server. So that might be a good place to try copying the quests to for the other players.

**Comment by YepMc** [comment]
> `config/hqm`, and then it looks like it'd be in one of the folders in there. In code (https://github.com/lorddusk/HQM/blob/1.12/src/main/java/hardcorequesting/io/SaveHandler.java) I see references to a "default" folder and a "remote" folder. The remote folder, in particular, insinuates by name that it might be used for quests when connected to a remote server. So that might be a good place to try copying the quests to for the other players.

Late response but bro this is a real issue in my modpack, im playing with friends and communities it would be best if there could be a better way to do this, is there anyway i could like convert this hqm to like a different mod like better questing, or FTB questing.

**Comment by canitzp** [comment]
Sorry for the issues you have. I don't know if there is any 3rd-party application to convert hqm quests to other quest mods formants, but I doubt it.
Since the version you're playing is not supported anymore and the last response is that long ago, I'll close this issue.
