### ISSUE TITLE
[1.12.2][Bug] The shared reward system is buggy

### ISSUE THREAD

**Issue by YepMc** [lorddusk/HQM#683]
So basically if as a partly leader I accept reward, only I receive the rewards and the members get nothing. My modpack link is https://legacy.curseforge.com/minecraft/modpacks/theboyswithguns-tbwg

**Comment by kirderf1** [comment]
There seems to be a "All in party get rewards" config option, but if that doesn't work, I don't think I can help much because of how old that version of the mod is.

**Comment by YepMc** [comment]
> There seems to be a "All in party get rewards" config option, but if that doesn't work, I don't think I can help much because of how old that version of the mod is.

The version is 1.12.2, and that option is enabled

**Comment by canitzp** [comment]
Check if that config is enabled on the server and the client.
Sadly if that doesn't help, we aren't fixing issues in this old version anymore.
