### ISSUE TITLE
[1.19.4] [BUG] Quest book half-resets on server for some players.

### ISSUE THREAD

**Issue by Xerses707** [lorddusk/HQM#684]
Hello, I'm running a lightly modded server with this mod installed and the quest book sometimes half-resets. 

What I mean by that is that the book resets all progress, however the internal data still remembers that players have completed those quest so it refuses to allow them to manually detect and reclaim the quest even when according to the percentiles and the way the quest icon is glowing in the book it should be "incomplete"

I looked in the data.json for the world and I found that it was tracking that the quest had been completed and claimed by the players, even though the book showed that nothing had been completed nor claimed.

I would really love and appreciate some help with this. Also, thank you for making such a wonderful questing mod :)

**Comment by kirderf1** [comment]
Was able to reproduce the issue in dev. There was an internal crash on the client/player-side. I had apparently made a mistake in #672. I had changed quest data parsing to require the quest instance, but I didn't make sure that quests were loaded before quest data client side. In fact, quest data is apparently loaded first. I'll get on making a fix for this.

**Comment by kirderf1** [comment]
HQM 5.14.1 should fix the issue.

**Comment by Xerses707** [comment]
Thank you so much! I truly do appreciate it!
