### ISSUE TITLE
Ore dictionary detection in 1.16.5

### ISSUE THREAD

**Issue by Jess-37** [lorddusk/HQM#685]
I am creating a modpack in 1.16.5, which uses this mod for the questline. For items such as copper ingots, multiple mods add these and share the same ore dictionary definition. However, the only options when setting a detection task are fuzzy detection or NBT independent detection (and those options with tags, and precise detection). I previously have only used the 1.12.2 version of this mod which has the ore dictionary, has this been removed? And how can I get Ores to be universal for the quest detection?

Additionally, in 1.16.5 I don't think the search bar works for finding items to create a quest, I can only add them if they are in my inventory.
![Copper_detection](https://github.com/lorddusk/HQM/assets/90870621/8bf010ce-9c35-41bf-8769-7bfb44761eda)

**Comment by canitzp** [comment]
Tags were introduced in 1.13 and OreDictionary was removed in favor of tags.

The search bar issue is known, but I couldn't reproduce it ever

**Comment by Jess-37** [comment]
The "tag and nbt independent detection" worked, thank you!

I can provide config files or a mod list if that helps?
