### ISSUE TITLE
Click to open a chapter also opens a quest underneath it

### ISSUE THREAD

**Issue by nanderson11** [lorddusk/HQM#69]
At the chapter select screen, clicking the Open button on the right page of the book to open the chapter will also open a quest page if the quest is located underneath the Open button. A good example of this is the Regrowth modpack, in chapters What the World is Built From and The Life of the World. Note that you need to unlock some quests to test this in Regrowth. I tested this with both HQM 4.3.2, which is what comes with the latest version of Regrowth, and with HQM 4.4.1 and it happens in both versions.

**Comment by way2muchnoise** [comment]
I think it still happens in 1.9+

**Comment by noobanidus** [comment]
This still occasioanlly happens in 1.12.2.

**Comment by noobanidus** [comment]
Okay, this is completely reproducible in 1.12.2 and the latest version of HQM duct_tape branch.
