### ISSUE TITLE
1.20.1 [Question] In regard to the UUID in the json.

### ISSUE THREAD

**Issue by Xerses707** [lorddusk/HQM#698]
I have multiple quest that involve completing advancements. 
In the json file I noticed there is a UUID there. Is that a UUID for the advancement provided by the base game / mods that have advancements, or is it the UUID of the quest and has nothing to do with the fact the quest is advancement based? I have an interesting issue and I don't know if it is this mod or if it is another mod causing it. The UUID is the same for some of the (quests/advancements whichever one it is) causing 2 separate quest to be completed at the same time.

**Comment by canitzp** [comment]
The UUID are only for the quests. Advancements are stored as default Minecraft resource path (minecraft:getting_started).

Two quests having the same UUID is nearly impossible, when you haven't changed things in the json files by yourself.
I recommend you delete on of the quests and recreate it. 
Right now I'm not sure if we check if a quest UUID is already in use. If not it is technically possible that a UUID is generated twice, but very very unlikely. (seems to be about one in a billion, you can google that for more information).

**Comment by Xerses707** [comment]
Well if it’s a 1 in a billion chance I just broke a world record 😂

So far I’ve found around 5-7 sets of quest with this issue. Interestingly enough the advancements that always conflict are from Alex’s mobs and Alex’s caves respectively. (Like, Lorem Ipsum from Alex’s Caves and Blindsided from Alex’s mobs have the same UUID). I don’t know how HQM decides to give the UUID out, but the fact that they’re both mods from the same mod author could be something.

I’ll do what you recommended tho and I’ll just remake one quest from each problem set! Hopefully that’ll work, I’ll do it likely over the weekend.

**Comment by canitzp** [comment]
I looked into the code, and it is not possible for HQm to assign the same UUID to multiple quests, there is a check to prevent it!

Therefor I don't have any clue, what problem you have.

**Comment by Xerses707** [comment]
Interesting! Well I hope doing what you recommended works. Maybe it had to do with the way that I input everything. I would make every single quest box first and then do each step one by one for each box. I’ll comment again once I do it and let y’all know if it worked or not.

**Comment by Xerses707** [comment]
Deleting and recreating worked! (At least for the one I tried it on).

I’ll fix everything up in my modpack sometime this week but I got a report due tomorrow 😅

Thank you for the help!
