### ISSUE TITLE
[4.4.1] Players information screen links not showing their name

### ISSUE THREAD

**Issue by tgstyle** [lorddusk/HQM#70]
![2015-11-10_10 05 36](https://cloud.githubusercontent.com/assets/5832709/11069439/5b38de36-8793-11e5-824c-3a6005b04d01.png)
showing hqm.questBook.moreinfo
![2015-11-10_10 05 55](https://cloud.githubusercontent.com/assets/5832709/11069519/b516ffa0-8793-11e5-9038-2b6f0f149222.png)
Lower right corner on this screen showing hqm.deathMenu*

**Comment by lorddusk** [comment]
Paging @way2muchnoise
