### ISSUE TITLE
Game crashes when loading quests

### ISSUE THREAD

**Issue by quincylennard** [lorddusk/HQM#75]
I'm trying to uploading the quest set JSON in [this pastebin](/http://pastebin.com/8ssnAbUw) to my quest book in an FTB Horizons: Daybreaker save. Whenever I try to do this, however, the game crashes, and upon restarting it the quest is locked without any prerequisites, and trying to open the locked quest set in edit mode results in the game crashing again. 

[Here's the crash report, using HQM v4.3.3.](/http://pastebin.com/tshSbeQQ) I've gotten similar behavior with versions 4.3.0, 4.3.1, and 4.3.2 as well.

**Comment by lorddusk** [comment]
Could you try the latest version?
