### ISSUE TITLE
[feature request] perform command block string

### ISSUE THREAD

**Issue by Divineaspect** [lorddusk/HQM#79]
I'd like to request this most magical of features. The ability to have a command block style string executed as a quest reward, or by a trigger quest. This would greatly enhance compatibility with every other mod which uses commands, and make the scope of command block magic and techniques available to the HQM author.

**Comment by lorddusk** [comment]
You can already do this technically. Triggerblock > Commandblock.

**Comment by Divineaspect** [comment]
Requires chunkloaded blocks, and also has a hard time telling which player
activated it.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by way2muchnoise** [comment]
Implemented in #134
