### ISSUE TITLE
[Feature request] perform quest button.

### ISSUE THREAD

**Issue by Divineaspect** [lorddusk/HQM#81]
Scratching an earlier pitch made before caffeine kicked in.

I would like a way to indicate the choice to complete a quest. This would simplify reputation quests which require a particular level, and which apply negative reputation. This may also or alternately be considered a bug in reputation.

As things stand now they automatically trigger, and if they can instantaneously repeat, they do so.

For example I have a reputation called Treasury, which represents the money to spend on special resources. 
I have a quest which provides a choice of 4 special stones (marble, granite, limestone, and Andesite), requires treasury reputation of 10, and which costs you 1 reputation from your treasury to complete. if I perform a quest which raises my reputation to 10, it immediately performs the quest, reducing the reputation to nine.

While I can see the uses for decaying or increasing reputation over time based hidden effects, it does get in the way of using reputation as currency. Such as is used in Banished and Blightfall.

**Comment by lorddusk** [comment]
#82
