### ISSUE TITLE
Crash with Quests

### ISSUE THREAD

**Issue by SkullyGamingMC** [lorddusk/HQM#84]
When searching in the Quest Book's search bar for items as I was making a Quest, I had a random crash, with no report generated. Upon startup everything was fine, but whenever I create a world or log into a world I crash and get this report (deleting all my Quests I had made solved this, but now I have to re-do them and I've gotten this entire issue 3 times) [insert a link to a paste of the crash log]

**Comment by Katrix-** [comment]
Before HQM crashes it usually makes a version of the quest data before the crash happened. Can't you restore from that. Also, from someone that have had this happen a lot. KEEP BACKUPS.

**Comment by MJRLegends** [comment]
Yeah many of the people playing my mod pack get this, i cant seem to find a fix to this apart from deleting the players quest data which resets them.

**Comment by way2muchnoise** [comment]
@SkullyGamingMC Please use pastebin or alike to post a log. Just dumping it here clutters the issue and makes it way harder to read

**Comment by MJRLegends** [comment]
Here is the crash im getting which is the same as @SkullyGamingMC issue http://pastebin.com/aQFMBUwh

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten for 1.9+, this should resolve this issue
