### ISSUE TITLE
Problems with HQM 4.4.1

### ISSUE THREAD

**Issue by MJRLegends** [lorddusk/HQM#85]
Im having problems with text not showing correctly and showing the unlocalized name versions see below from screenshots.

Also im having issues changing any quest task within the quest book. It says it has changed and adds a change to the changes/save section on the right but when you go back into the quest its not changed. 

See below for screenshots on both of theses....

Text Issues Screenshots: 
![image](https://cloud.githubusercontent.com/assets/8526321/11171631/d240bdd4-8bec-11e5-8f07-d13ac047478d.png)

![image](https://cloud.githubusercontent.com/assets/8526321/11171661/1fe30f06-8bed-11e5-9928-5d4e8876fddf.png)

![image](https://cloud.githubusercontent.com/assets/8526321/11171662/24249c24-8bed-11e5-9b9a-44931b45d84e.png)

Changing the quest task: 
Before change:
![image](https://cloud.githubusercontent.com/assets/8526321/11171636/e45544ae-8bec-11e5-8448-14345051caed.png)

Changing: 
![image](https://cloud.githubusercontent.com/assets/8526321/11171643/f30006b0-8bec-11e5-8ab6-039ea91f158f.png)

After Change: 
![image](https://cloud.githubusercontent.com/assets/8526321/11171650/00be9280-8bed-11e5-8799-0ee45131f50b.png)

**Comment by lorddusk** [comment]
you're changing a detection task into a detection task... Also the localization will be fixed tommorow morning.

**Comment by way2muchnoise** [comment]
Localizations things already fixed in f911d5bf079210ea92649794ae8fef8572f69d95 and 6412707696495247efefa8ecb3cf7f217a796a40

**Comment by MJRLegends** [comment]
No im trying to change a crafting task to a detection task???

**Comment by lorddusk** [comment]
Not according to the buttons in the questbook

**Comment by lorddusk** [comment]
Changing a tasktype WILL NOT CHANGE the description on the right side of the book. That's where your confusion comes in.

**Comment by MJRLegends** [comment]
Yeah i see it now but i the text should be changed if you change the task. :D but thanks. When will there be a download for the Localizations fix on curse?

**Comment by lorddusk** [comment]
within 24 hours.

Also, no it shouldn't change, what if people typed something in there? They
would lose the text when they change...

**Comment by MJRLegends** [comment]
OK thanks and yeah i suppose.

**Comment by MJRLegends** [comment]
Also not sure if this is a problem from the mod side and not HQM but the Items/Blocks dont show up in the hqm book with textures from the "Sync" mod but they do show up fine in NEI and creative menus.

Let me know if you need a screenshot.

**Comment by lorddusk** [comment]
Sure throw me a screenshot. I might know what it is and if it is, I'll yell at the creator of sync.

**Comment by MJRLegends** [comment]
Ok give me 5 mins

**Comment by MJRLegends** [comment]
![image](https://cloud.githubusercontent.com/assets/8526321/11171781/c50e2b7a-8bf0-11e5-884a-d1a51de9ae04.png)

**Comment by lorddusk** [comment]
Yeah as I thought, he or she did something with the rendering it's not our fault, I'll go yell at the creator...

**Comment by MJRLegends** [comment]
Ok thanks and also have you heard of the bug with HQM where if they are running a mod pack version containing the hqm mod and they have made progress completing quests but when the mod pack is updated and it contains changing to the quests. Some people cant load there worlds and it gets stuck when loading the dimensions. The only way to fix the not loading problem is to delete the quest book progress for the world.
