### ISSUE TITLE
Crash on world load with updated Quests on server 

### ISSUE THREAD

**Issue by cauliflower69** [lorddusk/HQM#86]
http://pastebin.com/CCLX6LPk

**Comment by lorddusk** [comment]
Gaddamnit people... I can't do anything with just a short description and a crashlog... Give me more information. What did you do that made this happen? Have you tried to reproduce the bug? FOR THE LOVE OF ALL THAT IS HOLY.

**Comment by cauliflower69** [comment]
Ok we updated the HQM Quests from v11 to v11hotfix https://www.reddit.com/r/TestPackPleaseIgnore/comments/3ieifr/aaronhowser1s_hqm_pack/

The pack loads fine in SP but upon update on the server the only way to get it to launch is to remove the HQM player data

**Comment by lorddusk** [comment]
See, was that so hard?  Next time, do it immediately. 

Now, have you tried to reproduce the bug? Is it always the same? 

Any idea why it might crash on MP and not on SP?

**Comment by cauliflower69** [comment]
I really don't like your tone. I am attempting to help you with feedback and all I get is this poor attitude. The only difference between my first and second post was that I specified which Quest set I updated.

Yes, I have tried to replace the bug with backups of the playerdata and it's always the same thing.

The playerdata in SP wouldn't have all the players past progress so I think that's why it's not crashing there.

**Comment by lorddusk** [comment]
I'm just sick of people not filing any information what so ever when reporting bugs, we don't know what is happening just from logs alone... Logs are an addition that helps us identify the problem, not the issue itself.

**Comment by cauliflower69** [comment]
I understand just didn't see the need to write a chapter about what happened when the OP title says it all. If you need any other information please let me know.

**Comment by lorddusk** [comment]
The title says absolutely nothing of how it happened. What did you update?
Quests? You have no idea how many things you can update in quests, tasks,
add quests, remove quests, change text. Just to name a few.

A good report has as MUCH information you can provide. The more information
you give us, the easier it is for us to identify and solve the problem. The
more we need to ask, the more time it takes and it might even turn us off
of the issue because no information was given.

I just took this as an example. Look at #87, that's not much text, but
provides much more information than just a title and a crash log.

**Comment by cauliflower69** [comment]
I personally didn't update the quests myself. I will ask Aaron to give a more detailed synopsis of what he changed which should help identify the issue.

**Comment by GreatOrator** [comment]
For what it is worth, I have seen this happen in my pack and it is usually because one or more quests created no longer exists.  Example, created 15 quests, during an update I remove one and add a new one, previous quests data on a server no longer works and have to reset it.

**Comment by cauliflower69** [comment]
Yeah thats makes sense

**Comment by MJRLegends** [comment]
This have been a problem for a long time

**Comment by lorddusk** [comment]
This is also a problem which we CAN'T reproduce ourselves, so testing anything is impossible.

**Comment by MJRLegends** [comment]
Yeah it's a random bug and doesn't happen every time so yeah it's hard to reproduce

**Comment by lorddusk** [comment]
`Yeah it's a random bug and doesn't happen every time so yeah it's *IMPOSSIBLE* to reproduce`
FTFY

**Comment by cauliflower69** [comment]
I'm sure there is someway to reproduce it, it's just we don't know how so impossible it isn't. I see your charm and wit are on the up and up.

**Comment by lorddusk** [comment]
Thanks.

**Comment by GreatOrator** [comment]
So for me every time I remove quests or remove quests and add new ones, existing servers/single player worlds crash on load unless they remove the hqm player file.  does not happen in my dev world as it is keeping track of everything while in edit mode, and this only happens once they try to open the quest book after changes to the hqm.

Simply updating the quests themselves never causes this, only when some are removed.

**Comment by cauliflower69** [comment]
Could you maybe post a before crash after crash playerdata & quest data ?

**Comment by GreatOrator** [comment]
I will see if I have one still, last time it happened was a few months ago and since my server when there are changes like that I force a restart to avoid it. and it is client side it happens

**Comment by SirWilli** [comment]
To add: If it doesn't crashes it auto resets the quests. Is this intended?

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten for 1.9+, this should resolve this issue
