### ISSUE TITLE
[4.4.1] Cannot set cooldown, or interval repeat times on quests

### ISSUE THREAD

**Issue by tgstyle** [lorddusk/HQM#87]
If I set it to 1 day then click OK
![2015-11-16_10 06 35](https://cloud.githubusercontent.com/assets/5832709/11188874/4aa875fc-8c4a-11e5-8f36-c1f471891083.png)
This is what happens
![2015-11-16_10 06 50](https://cloud.githubusercontent.com/assets/5832709/11188891/569a1550-8c4a-11e5-99af-b1f2f804848c.png)
This happens on changing existing cooldowns or on new quests, it does not save the changes.

Opening the quest again to set a cooldown time shows 0.

**Comment by lorddusk** [comment]
I'll look into it, thanks.
