### ISSUE TITLE
[Suggestion] Disable Questing and Hardcore Mode Ingame

### ISSUE THREAD

**Issue by Dream-Master** [lorddusk/HQM#89]
You can only enable hardcore Mode or Questing mod ingame

/hqm quest
/hqm hardcore

I suggest to give us a ingame disable funktion because i dont know how i can disabled now hardcore mode (wrongly enabled on the Server)

**Comment by Dream-Master** [comment]
Ok i delete the config and restart the Server that works for me now but a option ingame would be better,

**Comment by suprememiners** [comment]
I dont think you need to delete it, just change the config, theres an option in there for enabling the mode and you can just change it to false.

**Comment by Dream-Master** [comment]
@suprememiners 
sure you do it this way too but than you have to shutdown the Server and kick all Players.
It would be easy more to have a ingame option. 
@lorddusk 
Not sure why the Modmakers not answering to implement this or not.
When i typing hqm they give the available commands but this looks like this.
![hqm](https://cloud.githubusercontent.com/assets/2970688/11266675/6a130200-8ea6-11e5-9708-e4dc44eb9271.jpg)

**Comment by lorddusk** [comment]
your server doesn't understand < and >. $e is < and $f is >. 

At the time there is no way to disable hardcore or questing mode when enabled.

**Comment by Dream-Master** [comment]
Is there any chance to implement this in future Version or not?

**Comment by lorddusk** [comment]
maybe.
