### ISSUE TITLE
Auto Save/Load json files

### ISSUE THREAD

**Issue by SirWilli** [lorddusk/HQM#90]
Would be great if the json files get auto saved after clicking on save in edit mode and auto loaded when you start the game.

@hilburn

**Comment by way2muchnoise** [comment]
Just to know, what would be the use case for this?

**Comment by SirWilli** [comment]
With that multiple users can work on quest changes, do "offline" changes, accept pull request from others and more without to use /hqm save/load for each chapter every the time.

**Comment by lorddusk** [comment]
and what is wrong with using /hqm save all or load all?

**Comment by SirWilli** [comment]
Nothing is wrong with it, it is just cumbersome. With the manually save/load you never really know what's up to date.

**Comment by lorddusk** [comment]
And with the automatic you do?
I would say the other way around is the case...

I don't see any added worth in it being automatic...
