### ISSUE TITLE
/hqm load - doesn't update chapter names and descriptions

### ISSUE THREAD

**Issue by SirWilli** [lorddusk/HQM#91]
Changing the name or description of a chapter in the json file and loading it doesn't update it in game.

**Comment by suprememiners** [comment]
Have you loaded the correct file or loaded all of the json files?

It might just be that you are loading a file that is not editing the quest book as there is nothing there to change.

**Comment by SirWilli** [comment]
To make sure I edited a quest too which got updated after loading

**Comment by way2muchnoise** [comment]
Chapter names can't be updated since those get used to identify the chapter, but I fixed the description no updating.

**Comment by SirWilli** [comment]
Thanks!
