### ISSUE TITLE
Crash with OreDict permutation cycling

### ISSUE THREAD

**Issue by CrusherTechnologies** [lorddusk/HQM#95]
Now when I change HQM to detect items to ore dictionary instead of precise I try to save and it crashes.
http://pastebin.com/dTfWGze6
Crash report.
Using version 4.4.2

**Comment by way2muchnoise** [comment]
What item are you using?

**Comment by CrusherTechnologies** [comment]
I am using Thermal foundation copper ingot.ID: 4404:64 -- <ThermalFoundation:material:64>

**Comment by way2muchnoise** [comment]
Does this still happen in the latest version? If so could you provide a new log? Also what version of Forge are you using?

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Make a new issue if this still happens.
