### ISSUE TITLE
Ticking Error Crash

### ISSUE THREAD

**Issue by vagaprime** [lorddusk/HQM#97]
Was updating and adding new quest to my modpack after updating Hardcore questing mod. I had saved the quests that I had changed before starting to add more quests to one of my quest lines. The crash happened after saving the quest text and setting the tasks.

http://pastebin.com/Bee6j6Ry

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving, loading and networking are rewritten for 1.9+, this should resolve this issue
