### ISSUE TITLE
[Feature Request] Text boxes, Copy/Paste Quests, Move Chapters

### ISSUE THREAD

**Issue by awade33** [lorddusk/HQM#98]
Text Boxes - A way to be able to put bits of text on quest pages. Whether it be little notes or lore I think it'd be a nice little addition

Copy/Paste Quests - Pretty self explanatory but I would be nice to just copy and paste a quest (maybe chapters too but probably not as high a priority) instead of having to do a lot switching back and forth remembering what to add

Moving Chapters - It would be really nice to be able to move chapters in the content page without having to export them all, delete them and then reimport

Hotkeys - I realise this will be very low priority but adding hotkeys would be a very helpful user-improvement. Things like adding reputation to a lot of quests requires a lot of time just clicking which could be drastically shortened by adding a few hotkeys, either configurable through the minecraft settings but only usable in the book so key-conflicts shouldn't be an issue, or your own settings page

**Comment by way2muchnoise** [comment]
I think all but the text boxes are implemented at this point in the 1.9 version. As you can do most of it with the json format. If some of the implementations aren't what you had in mind you can go ahead and make a new issue. But could you split those up so it isn't one big issue with multiple suggestions.
